import { q } from "./_build";

export const D1_QUESTIONS = [
  // l0101 tables/types/indexes
  q({ id: "q-l0101-1", domainId: "d1", moduleId: "m01", lessonId: "l0101", difficulty: "beginner",
    prompt: "A reporting query scans and aggregates 50 million rows of a sales fact table. Which index type best fits this analytic workload?",
    options: [["a", "A nonclustered rowstore index on every column"], ["b", "A clustered columnstore index"], ["c", "A heap with no index"], ["d", "A unique constraint"]],
    correct: ["b"],
    explanation: "Columnstore indexes store data by column with heavy compression and batch-mode execution, ideal for scanning/aggregating large row counts. Rowstore indexes suit OLTP seeks, not big analytic scans." }),
  q({ id: "q-l0101-2", domainId: "d1", moduleId: "m01", lessonId: "l0101", difficulty: "beginner",
    prompt: "How many clustered indexes can a single table have?",
    options: [["a", "Zero or one"], ["b", "Exactly one, always"], ["c", "One per column"], ["d", "Unlimited"]],
    correct: ["a"],
    explanation: "A table has at most one clustered index (it defines physical row order). A table without one is a heap, so the answer is zero or one." }),
  q({ id: "q-l0101-3", domainId: "d1", moduleId: "m01", lessonId: "l0101", difficulty: "beginner", type: "single",
    prompt: "Which data type is the recommended modern choice for storing date and time with high precision?",
    options: [["a", "DATETIME"], ["b", "SMALLDATETIME"], ["c", "DATETIME2"], ["d", "TIMESTAMP"]],
    correct: ["c"],
    explanation: "DATETIME2 offers a larger range and configurable fractional-second precision, and is preferred over legacy DATETIME. In SQL Server, TIMESTAMP is a rowversion, not a datetime." }),

  // l0102 specialized tables
  q({ id: "q-l0102-1", domainId: "d1", moduleId: "m01", lessonId: "l0102",
    prompt: "A compliance requirement states that financial records must be tamper-evident and cryptographically verifiable. Which table type satisfies this?",
    options: [["a", "Temporal table"], ["b", "Ledger table"], ["c", "Memory-optimized table"], ["d", "Graph table"]],
    correct: ["b"],
    explanation: "Ledger tables provide cryptographically verifiable, tamper-evident history. Temporal tables keep history but are not tamper-proof." }),
  q({ id: "q-l0102-2", domainId: "d1", moduleId: "m01", lessonId: "l0102",
    prompt: "Which clause enables automatic full history tracking for point-in-time queries?",
    options: [["a", "WITH (MEMORY_OPTIMIZED = ON)"], ["b", "WITH (SYSTEM_VERSIONING = ON)"], ["c", "WITH (LEDGER = ON)"], ["d", "AS NODE"]],
    correct: ["b"],
    explanation: "System-versioned temporal tables use WITH (SYSTEM_VERSIONING = ON) and support FOR SYSTEM_TIME queries." }),
  q({ id: "q-l0102-3", domainId: "d1", moduleId: "m01", lessonId: "l0102",
    prompt: "You need to model and query many-to-many relationships (who follows whom). Which combination fits best?",
    options: [["a", "External tables + OPENROWSET"], ["b", "NODE and EDGE tables + MATCH"], ["c", "Temporal tables + FOR SYSTEM_TIME"], ["d", "Ledger tables + verification"]],
    correct: ["b"],
    explanation: "Graph NODE/EDGE tables queried with MATCH are designed for relationship/network traversal." }),

  // l0103 JSON (flagship)
  q({ id: "q-l0103-1", domainId: "d1", moduleId: "m01", lessonId: "l0103",
    prompt: "Which function extracts a scalar value from a JSON document in SQL Server?",
    options: [["a", "JSON_QUERY"], ["b", "JSON_VALUE"], ["c", "OPENJSON"], ["d", "FOR JSON"]],
    correct: ["b"],
    explanation: "JSON_VALUE returns a scalar. JSON_QUERY returns an object/array fragment; OPENJSON shreds into rows." }),
  q({ id: "q-l0103-2", domainId: "d1", moduleId: "m01", lessonId: "l0103",
    prompt: "You must filter thousands of rows by a JSON attribute quickly on SQL Server. What is the recommended approach?",
    options: [["a", "Create a GIN index on the JSON column"], ["b", "Promote the path to a computed column and index it"], ["c", "Add a full-text index on the JSON"], ["d", "Nothing; JSON paths are auto-indexed"]],
    correct: ["b"],
    explanation: "SQL Server can't index inside a JSON blob directly; promote the hot path to a computed column and index that. GIN is PostgreSQL's approach." }),
  q({ id: "q-l0103-3", domainId: "d1", moduleId: "m01", lessonId: "l0103", type: "codeReading",
    prompt: "Given the query, what does it return per product?",
    code: "SELECT p.ProductId, t.[value] AS tag\nFROM dbo.Product p\nCROSS APPLY OPENJSON(p.Attributes, '$.tags') t;",
    options: [["a", "One row per product with the whole tags array"], ["b", "One row per tag per product"], ["c", "Only the first tag"], ["d", "An error; OPENJSON needs a WITH clause"]],
    correct: ["b"],
    explanation: "OPENJSON over an array with CROSS APPLY yields one row per array element, so you get one row per tag per product." }),
  q({ id: "q-l0103-4", domainId: "d1", moduleId: "m01", lessonId: "l0103", type: "single",
    prompt: "Which statement about PostgreSQL jsonb vs SQL Server json is TRUE?",
    options: [["a", "Both require computed/generated columns to index document contents"], ["b", "PostgreSQL jsonb can be indexed directly with a GIN index"], ["c", "SQL Server json supports the @> containment operator"], ["d", "Neither can store nested objects"]],
    correct: ["b"],
    explanation: "PostgreSQL jsonb supports GIN indexes over the whole document, whereas SQL Server (like MySQL) needs a promoted computed/generated column to index a path." }),
  q({ id: "q-l0103-5", domainId: "d1", moduleId: "m01", lessonId: "l0103", type: "single",
    prompt: "Which SQL Server 2025 feature improves JSON storage and validation compared to nvarchar(max)?",
    options: [["a", "The native json data type"], ["b", "The XML data type"], ["c", "sql_variant"], ["d", "VARBINARY(MAX)"]],
    correct: ["a"],
    explanation: "SQL Server 2025 adds a native json data type storing an optimized binary form with validation, preferred over the nvarchar(max) + ISJSON pattern." }),

  // l0104 constraints
  q({ id: "q-l0104-1", domainId: "d1", moduleId: "m01", lessonId: "l0104", difficulty: "beginner",
    prompt: "In SQL Server, how many NULLs does a UNIQUE constraint permit in a single-column key?",
    options: [["a", "None"], ["b", "Exactly one"], ["c", "Unlimited"], ["d", "One per session"]],
    correct: ["b"],
    explanation: "SQL Server treats NULLs as equal for UNIQUE, allowing only one NULL. This differs from some other engines." }),
  q({ id: "q-l0104-2", domainId: "d1", moduleId: "m01", lessonId: "l0104", difficulty: "beginner",
    prompt: "Which referential action deletes child rows automatically when the parent is deleted?",
    options: [["a", "NO ACTION"], ["b", "SET NULL"], ["c", "CASCADE"], ["d", "SET DEFAULT"]],
    correct: ["c"],
    explanation: "ON DELETE CASCADE removes dependent child rows automatically." }),
  q({ id: "q-l0104-3", domainId: "d1", moduleId: "m01", lessonId: "l0104",
    prompt: "You re-enable a foreign key WITH NOCHECK. What is the consequence for the optimizer?",
    options: [["a", "The constraint becomes 'not trusted' and existing data isn't validated"], ["b", "All existing data is re-validated"], ["c", "The FK is dropped"], ["d", "Nothing changes"]],
    correct: ["a"],
    explanation: "WITH NOCHECK leaves the constraint untrusted; the optimizer can't rely on it and existing rows aren't validated. WITH CHECK re-validates and marks it trusted." }),

  // l0105 sequences
  q({ id: "q-l0105-1", domainId: "d1", moduleId: "m01", lessonId: "l0105", difficulty: "beginner",
    prompt: "You need a single number space shared across several tables. Which object fits best?",
    options: [["a", "IDENTITY column"], ["b", "SEQUENCE"], ["c", "UNIQUEIDENTIFIER default"], ["d", "CHECK constraint"]],
    correct: ["b"],
    explanation: "A SEQUENCE is schema-scoped and can feed multiple tables with NEXT VALUE FOR, unlike a table-bound IDENTITY." }),
  q({ id: "q-l0105-2", domainId: "d1", moduleId: "m01", lessonId: "l0105",
    prompt: "Which engine (as of 8.0) has no standalone SEQUENCE object and emulates it with AUTO_INCREMENT?",
    options: [["a", "PostgreSQL"], ["b", "Oracle"], ["c", "MySQL"], ["d", "SQL Server"]],
    correct: ["c"],
    explanation: "MySQL lacks a standalone SEQUENCE object; PostgreSQL, Oracle, and SQL Server all provide CREATE SEQUENCE." }),

  // l0106 partitioning
  q({ id: "q-l0106-1", domainId: "d1", moduleId: "m01", lessonId: "l0106", difficulty: "advanced",
    prompt: "Which operation moves an entire partition in or out of a table almost instantly (metadata-only)?",
    options: [["a", "BULK INSERT"], ["b", "ALTER TABLE ... SWITCH"], ["c", "MERGE"], ["d", "DBCC SHRINKFILE"]],
    correct: ["b"],
    explanation: "ALTER TABLE ... SWITCH is a metadata-only operation, the basis of the sliding-window archival pattern." }),
  q({ id: "q-l0106-2", domainId: "d1", moduleId: "m01", lessonId: "l0106", difficulty: "advanced",
    prompt: "For partition elimination to speed up queries, the partition key should be:",
    options: [["a", "A random GUID"], ["b", "The column queries frequently filter on"], ["c", "Any nullable column"], ["d", "The primary key only"]],
    correct: ["b"],
    explanation: "The optimizer eliminates partitions based on predicates on the partition key, so partition on the column your queries filter by (often a date)." }),

  // l0201 views
  q({ id: "q-l0201-1", domainId: "d1", moduleId: "m02", lessonId: "l0201", difficulty: "beginner",
    prompt: "What is required to create an indexed (materialized) view in SQL Server?",
    options: [["a", "WITH SCHEMABINDING and a unique clustered index"], ["b", "A nonclustered index only"], ["c", "READ_ONLY option"], ["d", "A temporal clause"]],
    correct: ["a"],
    explanation: "Indexed views require WITH SCHEMABINDING plus a UNIQUE CLUSTERED INDEX; results are then stored and auto-maintained." }),
  q({ id: "q-l0201-2", domainId: "d1", moduleId: "m02", lessonId: "l0201",
    prompt: "Which is a valid reason to use a view?",
    options: [["a", "To store data physically by default"], ["b", "To restrict which columns/rows users can access"], ["c", "To replace the need for indexes"], ["d", "To bypass permissions"]],
    correct: ["b"],
    explanation: "Views can act as a security/abstraction layer by exposing only certain columns/rows. A standard view stores no data." }),

  // l0202 functions
  q({ id: "q-l0202-1", domainId: "d1", moduleId: "m02", lessonId: "l0202",
    prompt: "Which function form generally gives the optimizer the best cardinality estimates?",
    options: [["a", "Multi-statement table-valued function"], ["b", "Inline table-valued function"], ["c", "Scalar UDF without inlining"], ["d", "Extended stored procedure"]],
    correct: ["b"],
    explanation: "Inline TVFs expand like a view so the optimizer reasons about them directly; multi-statement TVFs historically produce poor estimates." }),
  q({ id: "q-l0202-2", domainId: "d1", moduleId: "m02", lessonId: "l0202",
    prompt: "Which SQL Server feature can automatically improve performance of eligible legacy scalar UDFs?",
    options: [["a", "Scalar UDF inlining"], ["b", "Auto-shrink"], ["c", "Instant file initialization"], ["d", "Lock escalation"]],
    correct: ["a"],
    explanation: "Scalar UDF inlining (Intelligent Query Processing, 2019+) inlines eligible scalar functions for large speedups." }),

  // l0203 procs/triggers
  q({ id: "q-l0203-1", domainId: "d1", moduleId: "m02", lessonId: "l0203",
    prompt: "A DML trigger inserts into an audit table but only records one row even when 10 rows are updated. What is the likely cause?",
    options: [["a", "The trigger uses row-by-row logic instead of the inserted/deleted tables"], ["b", "Triggers can only see one row ever"], ["c", "The audit table lacks an index"], ["d", "AFTER triggers don't fire on UPDATE"]],
    correct: ["a"],
    explanation: "Triggers fire once per statement; you must process all rows via the inserted/deleted pseudo-tables set-based, not assume a single row." }),
  q({ id: "q-l0203-2", domainId: "d1", moduleId: "m02", lessonId: "l0203",
    prompt: "Which trigger type makes an otherwise non-updatable view updatable?",
    options: [["a", "AFTER INSERT"], ["b", "INSTEAD OF"], ["c", "DDL trigger"], ["d", "Logon trigger"]],
    correct: ["b"],
    explanation: "INSTEAD OF triggers replace the DML operation and are commonly used to make complex views updatable." }),

  // l0301 CTEs
  q({ id: "q-l0301-1", domainId: "d1", moduleId: "m03", lessonId: "l0301",
    prompt: "A recursive CTE keeps running far past the expected depth. Which option limits recursion depth?",
    options: [["a", "OPTION (MAXRECURSION n)"], ["b", "SET ROWCOUNT n"], ["c", "TOP (n)"], ["d", "OPTION (RECOMPILE)"]],
    correct: ["a"],
    explanation: "OPTION (MAXRECURSION n) caps recursion (default 100; 0 = unlimited)." }),
  q({ id: "q-l0301-2", domainId: "d1", moduleId: "m03", lessonId: "l0301",
    prompt: "A recursive CTE must contain which two parts?",
    options: [["a", "An anchor member and a recursive member joined by UNION ALL"], ["b", "Two anchor members"], ["c", "A PIVOT and an UNPIVOT"], ["d", "A CROSS APPLY and OUTER APPLY"]],
    correct: ["a"],
    explanation: "Recursive CTEs use an anchor member, UNION ALL, and a recursive member that references the CTE." }),

  // l0302 window functions
  q({ id: "q-l0302-1", domainId: "d1", moduleId: "m03", lessonId: "l0302",
    prompt: "You need a running total of sales ordered by date. Which clause produces it?",
    code: "SUM(Amount) OVER (ORDER BY SaleDate ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)",
    options: [["a", "It produces a running total"], ["b", "It produces the grand total on every row"], ["c", "It errors without PARTITION BY"], ["d", "It returns NULLs"]],
    correct: ["a"],
    explanation: "A frame of UNBOUNDED PRECEDING to CURRENT ROW yields a cumulative running total." }),
  q({ id: "q-l0302-2", domainId: "d1", moduleId: "m03", lessonId: "l0302",
    prompt: "Which ranking function always returns unique, gapless numbers within a partition?",
    options: [["a", "RANK"], ["b", "DENSE_RANK"], ["c", "ROW_NUMBER"], ["d", "NTILE"]],
    correct: ["c"],
    explanation: "ROW_NUMBER is always unique. RANK leaves gaps after ties; DENSE_RANK has no gaps but repeats values for ties." }),
  q({ id: "q-l0302-3", domainId: "d1", moduleId: "m03", lessonId: "l0302",
    prompt: "LAST_VALUE returns the current row's value rather than the partition's last. Why?",
    options: [["a", "LAST_VALUE is broken"], ["b", "The default frame ends at CURRENT ROW"], ["c", "You must add PARTITION BY"], ["d", "It needs DISTINCT"]],
    correct: ["b"],
    explanation: "The default frame is UNBOUNDED PRECEDING to CURRENT ROW; set ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING to get the true last value." }),

  // l0303 json functions
  q({ id: "q-l0303-1", domainId: "d1", moduleId: "m03", lessonId: "l0303",
    prompt: "Which clause serializes a query result set into a JSON array of objects?",
    options: [["a", "FOR JSON PATH"], ["b", "FOR XML AUTO"], ["c", "OPENJSON"], ["d", "STRING_AGG"]],
    correct: ["a"],
    explanation: "FOR JSON PATH (or AUTO) serializes result rows to JSON — often used to build model payloads in RAG." }),
  q({ id: "q-l0303-2", domainId: "d1", moduleId: "m03", lessonId: "l0303",
    prompt: "Which function aggregates values from multiple rows into a single JSON array?",
    options: [["a", "JSON_VALUE"], ["b", "JSON_ARRAYAGG"], ["c", "JSON_QUERY"], ["d", "ISJSON"]],
    correct: ["b"],
    explanation: "JSON_ARRAYAGG aggregates row values into a JSON array; JSON_OBJECTAGG builds an object." }),

  // l0304 regex/fuzzy
  q({ id: "q-l0304-1", domainId: "d1", moduleId: "m03", lessonId: "l0304",
    prompt: "You must deduplicate customer names with minor typos. Which function is most appropriate?",
    options: [["a", "REGEXP_LIKE"], ["b", "JARO_WINKLER_DISTANCE"], ["c", "SOUNDEX only"], ["d", "JSON_VALUE"]],
    correct: ["b"],
    explanation: "JARO_WINKLER favors common prefixes and is well-suited to person names; EDIT_DISTANCE also helps for general typos." }),
  q({ id: "q-l0304-2", domainId: "d1", moduleId: "m03", lessonId: "l0304",
    prompt: "Which is a real SQL Server 2025 regular-expression function?",
    options: [["a", "REGEX_MATCH"], ["b", "REGEXP_REPLACE"], ["c", "PATINDEX_REGEX"], ["d", "MATCH_RECOGNIZE"]],
    correct: ["b"],
    explanation: "REGEXP_REPLACE (and REGEXP_LIKE, REGEXP_SUBSTR, REGEXP_SPLIT_TO_TABLE, etc.) are part of the new regex family." }),

  // l0305 graph/error handling
  q({ id: "q-l0305-1", domainId: "d1", moduleId: "m03", lessonId: "l0305", difficulty: "advanced",
    prompt: "Inside a CATCH block, which check should you perform before rolling back?",
    options: [["a", "@@ROWCOUNT"], ["b", "XACT_STATE()"], ["c", "@@IDENTITY"], ["d", "SCOPE_IDENTITY()"]],
    correct: ["b"],
    explanation: "XACT_STATE() tells you whether the transaction is committable (1), none (0), or doomed (-1). A doomed transaction can only be rolled back." }),
  q({ id: "q-l0305-2", domainId: "d1", moduleId: "m03", lessonId: "l0305", difficulty: "advanced",
    prompt: "Which operator performs graph pattern matching over NODE and EDGE tables?",
    options: [["a", "JOIN"], ["b", "MATCH"], ["c", "APPLY"], ["d", "MERGE"]],
    correct: ["b"],
    explanation: "MATCH expresses graph patterns like p-(likes)->p2 over NODE/EDGE tables." }),

  // l0401 copilot enablement
  q({ id: "q-l0401-1", domainId: "d1", moduleId: "m04", lessonId: "l0401", difficulty: "beginner",
    prompt: "Which practice reduces the security risk of using AI-assisted coding tools with SQL?",
    options: [["a", "Paste production data into prompts for better answers"], ["b", "Review generated SQL for injection and least privilege before running"], ["c", "Always run generated SQL as sysadmin"], ["d", "Disable code review"]],
    correct: ["b"],
    explanation: "Treat AI suggestions as drafts: review for parameterization, injection risk, and least-privilege, and keep sensitive data out of prompts." }),
  q({ id: "q-l0401-2", domainId: "d1", moduleId: "m04", lessonId: "l0401", difficulty: "beginner",
    prompt: "Copilot in Fabric provides AI assistance primarily for which context?",
    options: [["a", "On-prem Active Directory management"], ["b", "Data workloads within Microsoft Fabric"], ["c", "Windows kernel debugging"], ["d", "Email spam filtering"]],
    correct: ["b"],
    explanation: "Copilot in Fabric assists with data workloads inside Microsoft Fabric." }),

  // l0402 models/instructions
  q({ id: "q-l0402-1", domainId: "d1", moduleId: "m04", lessonId: "l0402",
    prompt: "What is the purpose of a GitHub Copilot instruction file?",
    options: [["a", "To store database passwords"], ["b", "To give Copilot persistent project context and conventions"], ["c", "To compile T-SQL"], ["d", "To replace source control"]],
    correct: ["b"],
    explanation: "Instruction files (e.g., .github/copilot-instructions.md) encode durable conventions/guardrails so you don't repeat them each prompt." }),
  q({ id: "q-l0402-2", domainId: "d1", moduleId: "m04", lessonId: "l0402",
    prompt: "In a Copilot chat session, enabling MCP tool options lets the assistant:",
    options: [["a", "Call external tools via the Model Context Protocol"], ["b", "Bypass authentication"], ["c", "Format the hard drive"], ["d", "Disable the model"]],
    correct: ["a"],
    explanation: "MCP tool options let the assistant invoke external tools exposed over the Model Context Protocol." }),

  // l0403 MCP endpoints
  q({ id: "q-l0403-1", domainId: "d1", moduleId: "m04", lessonId: "l0403", difficulty: "advanced",
    prompt: "Which MCP server endpoints are explicitly called out in the DP-800 blueprint?",
    options: [["a", "Microsoft SQL Server and Fabric lakehouse"], ["b", "Redis and MongoDB"], ["c", "Kafka and RabbitMQ"], ["d", "S3 and DynamoDB"]],
    correct: ["a"],
    explanation: "The blueprint names Microsoft SQL Server and Fabric lakehouse MCP server endpoints." }),
  q({ id: "q-l0403-2", domainId: "d1", moduleId: "m04", lessonId: "l0403", difficulty: "advanced",
    prompt: "What is the recommended way to secure an MCP endpoint connection?",
    options: [["a", "Hardcode an admin password"], ["b", "Managed Identity with least-privilege scope"], ["c", "Open it to the public internet"], ["d", "Disable logging"]],
    correct: ["b"],
    explanation: "Authenticate MCP endpoints with Managed Identity, scope permissions tightly, and log tool invocations." }),
];
