import { q } from "./_build";

export const D3_QUESTIONS = [
  // l0901 external models
  q({ id: "q-l0901-1", domainId: "d3", moduleId: "m09", lessonId: "l0901",
    prompt: "Which T-SQL statement registers an external AI model for in-database use?",
    options: [["a", "CREATE EXTERNAL MODEL"], ["b", "CREATE MODEL TABLE"], ["c", "CREATE ASSEMBLY"], ["d", "CREATE EXTERNAL TABLE"]],
    correct: ["a"],
    explanation: "CREATE EXTERNAL MODEL registers a model (embedding or chat) with its endpoint and credentials for use in T-SQL." }),
  q({ id: "q-l0901-2", domainId: "d3", moduleId: "m09", lessonId: "l0901",
    prompt: "When choosing an external model, which factors matter for DP-800?",
    type: "multi",
    options: [["a", "Modality (text/multimodal)"], ["b", "Language coverage"], ["c", "Size (latency/cost)"], ["d", "The server's CPU brand"]],
    correct: ["a", "b", "c"],
    explanation: "Evaluate models by modality, language, size, and structured-output support; CPU brand is irrelevant to model selection." }),

  // l0902 embedding maintenance
  q({ id: "q-l0902-1", domainId: "d3", moduleId: "m09", lessonId: "l0902", difficulty: "advanced",
    prompt: "Which approach efficiently re-embeds only rows whose source text changed?",
    options: [["a", "Re-embed the entire corpus nightly"], ["b", "Use Change Tracking to find changed rows, then re-embed those"], ["c", "Never update embeddings"], ["d", "Delete and recreate the table daily"]],
    correct: ["b"],
    explanation: "Change Tracking identifies changed rows so you re-embed only what changed, avoiding full-corpus reprocessing." }),
  q({ id: "q-l0902-2", domainId: "d3", moduleId: "m09", lessonId: "l0902", difficulty: "advanced",
    prompt: "Which is a valid embedding-maintenance method named in the 2026 blueprint?",
    type: "multi",
    options: [["a", "Table triggers"], ["b", "CDC"], ["c", "Microsoft Foundry"], ["d", "Defragmenting the disk"]],
    correct: ["a", "b", "c"],
    explanation: "Triggers, Change Tracking, CDC, CES, Azure Functions, Logic Apps, and Microsoft Foundry are listed methods; disk defrag is unrelated." }),

  // l0903 chunking/embedding
  q({ id: "q-l0903-1", domainId: "d3", moduleId: "m09", lessonId: "l0903", difficulty: "advanced",
    prompt: "Which columns should you embed for semantic search over support articles?",
    options: [["a", "The article title and body"], ["b", "The numeric article ID"], ["c", "The created timestamp"], ["d", "The internal status code"]],
    correct: ["a"],
    explanation: "Embed the columns carrying meaning (title, body). IDs, timestamps, and codes don't add semantic value." }),
  q({ id: "q-l0903-2", domainId: "d3", moduleId: "m09", lessonId: "l0903", difficulty: "advanced",
    prompt: "Why chunk long documents before embedding?",
    options: [["a", "To fit model context limits and preserve focused meaning per vector"], ["b", "To make files smaller on disk"], ["c", "Because vectors can't store decimals"], ["d", "It is never recommended"]],
    correct: ["a"],
    explanation: "Chunking (often with overlap) keeps each vector focused and within model limits, improving retrieval over a single diluted whole-doc vector." }),

  // l1001 full-text
  q({ id: "q-l1001-1", domainId: "d3", moduleId: "m10", lessonId: "l1001",
    prompt: "Which predicate supports precise phrase and proximity keyword search?",
    options: [["a", "CONTAINS"], ["b", "LIKE only"], ["c", "VECTOR_DISTANCE"], ["d", "JSON_VALUE"]],
    correct: ["a"],
    explanation: "CONTAINS supports precise full-text searches (phrases, proximity, inflectional forms); FREETEXT is looser meaning-based." }),
  q({ id: "q-l1001-2", domainId: "d3", moduleId: "m10", lessonId: "l1001",
    prompt: "When is full-text search preferable to vector search?",
    options: [["a", "When exact keywords/phrases must match"], ["b", "When you need semantic similarity"], ["c", "For image embeddings"], ["d", "Never"]],
    correct: ["a"],
    explanation: "Full-text excels at exact terms/phrases; vector search excels at semantic similarity. Hybrid combines both." }),

  // l1002 vector (flagship)
  q({ id: "q-l1002-1", domainId: "d3", moduleId: "m10", lessonId: "l1002", difficulty: "advanced",
    prompt: "Which function computes similarity between two embeddings in SQL Server?",
    options: [["a", "VECTOR_DISTANCE"], ["b", "DIFFERENCE"], ["c", "SOUNDEX"], ["d", "JSON_VALUE"]],
    correct: ["a"],
    explanation: "VECTOR_DISTANCE(metric, a, b) returns the distance for cosine, euclidean, or dot metrics." }),
  q({ id: "q-l1002-2", domainId: "d3", moduleId: "m10", lessonId: "l1002", difficulty: "advanced",
    prompt: "To get the most similar rows with cosine distance, how should you order results?",
    options: [["a", "ORDER BY distance ASC"], ["b", "ORDER BY distance DESC"], ["c", "ORDER BY NEWID()"], ["d", "No ordering needed"]],
    correct: ["a"],
    explanation: "Smaller distance means more similar, so order ascending and take the top-k." }),
  q({ id: "q-l1002-3", domainId: "d3", moduleId: "m10", lessonId: "l1002", difficulty: "advanced",
    prompt: "For a very large corpus needing fast search with slight accuracy trade-off, choose:",
    options: [["a", "ENN (exact) full scan"], ["b", "ANN with a DiskANN index"], ["c", "A full-text index"], ["d", "A columnstore index"]],
    correct: ["b"],
    explanation: "ANN with DiskANN trades a little recall for large speedups at scale; ENN is exact but scans everything." }),
  q({ id: "q-l1002-4", domainId: "d3", moduleId: "m10", lessonId: "l1002", difficulty: "advanced",
    prompt: "Which is the usual default metric for text embeddings?",
    options: [["a", "cosine"], ["b", "hamming"], ["c", "jaccard"], ["d", "levenshtein"]],
    correct: ["a"],
    explanation: "Cosine distance is the common default for text embeddings." }),
  q({ id: "q-l1002-5", domainId: "d3", moduleId: "m10", lessonId: "l1002", difficulty: "advanced",
    prompt: "Which PostgreSQL capability is the closest equivalent to SQL Server's VECTOR type and ANN indexing?",
    options: [["a", "pgvector with HNSW/IVFFlat indexes"], ["b", "hstore"], ["c", "PostGIS"], ["d", "ltree"]],
    correct: ["a"],
    explanation: "pgvector adds a vector type, distance operators, and HNSW/IVFFlat ANN indexes." }),
  q({ id: "q-l1002-6", domainId: "d3", moduleId: "m10", lessonId: "l1002", difficulty: "advanced",
    prompt: "Two embeddings can be compared with VECTOR_DISTANCE only if they:",
    options: [["a", "Have the same dimension and come from the same model"], ["b", "Are in different tables"], ["c", "Use different metrics"], ["d", "Are stored as JSON"]],
    correct: ["a"],
    explanation: "Vectors must share dimension and originate from the same embedding model to be comparable." }),

  // l1003 hybrid/rrf
  q({ id: "q-l1003-1", domainId: "d3", moduleId: "m10", lessonId: "l1003", difficulty: "advanced",
    prompt: "Reciprocal rank fusion combines results by:",
    options: [["a", "Averaging raw scores from each system"], ["b", "Summing 1/(k + rank) across ranked lists"], ["c", "Taking only the vector results"], ["d", "Random selection"]],
    correct: ["b"],
    explanation: "RRF sums 1/(k + rank) per document across lists, so it needs no score calibration between systems." }),
  q({ id: "q-l1003-2", domainId: "d3", moduleId: "m10", lessonId: "l1003", difficulty: "advanced",
    prompt: "Hybrid search combines which two approaches?",
    options: [["a", "Full-text (keyword) and vector (semantic)"], ["b", "Two full-text indexes"], ["c", "Two columnstore scans"], ["d", "Backup and restore"]],
    correct: ["a"],
    explanation: "Hybrid search fuses keyword (full-text) and semantic (vector) retrieval, often via RRF." }),

  // l1004 evaluating search
  q({ id: "q-l1004-1", domainId: "d3", moduleId: "m10", lessonId: "l1004", difficulty: "advanced",
    prompt: "Tuning an ANN index is fundamentally a trade-off between:",
    options: [["a", "Recall and latency"], ["b", "Backup size and CPU"], ["c", "Color and font"], ["d", "Rows and columns"]],
    correct: ["a"],
    explanation: "ANN parameters trade recall (accuracy) against latency (speed); measure both on representative queries." }),
  q({ id: "q-l1004-2", domainId: "d3", moduleId: "m10", lessonId: "l1004", difficulty: "advanced",
    prompt: "How should you evaluate search quality?",
    options: [["a", "On representative real queries, measuring recall and latency"], ["b", "Only with a single toy query"], ["c", "By counting rows in the table"], ["d", "By checking disk temperature"]],
    correct: ["a"],
    explanation: "Evaluate on representative queries and measure recall and latency; confirm hybrid actually beats single-method retrieval." }),

  // l1101 RAG endpoint
  q({ id: "q-l1101-1", domainId: "d3", moduleId: "m11", lessonId: "l1101", difficulty: "advanced",
    prompt: "Which stored procedure calls an external model REST endpoint from T-SQL?",
    options: [["a", "sp_invoke_external_rest_endpoint"], ["b", "sp_executesql"], ["c", "xp_cmdshell"], ["d", "sp_send_dbmail"]],
    correct: ["a"],
    explanation: "sp_invoke_external_rest_endpoint calls external REST APIs (including models) from T-SQL with a JSON payload." }),
  q({ id: "q-l1101-2", domainId: "d3", moduleId: "m11", lessonId: "l1101", difficulty: "advanced",
    prompt: "What problem does RAG primarily address?",
    options: [["a", "Grounding LLM answers in your data to reduce hallucination"], ["b", "Compressing backups"], ["c", "Indexing images"], ["d", "Encrypting connections"]],
    correct: ["a"],
    explanation: "RAG retrieves relevant data and supplies it as context so the model answers from facts, reducing hallucination." }),
  q({ id: "q-l1101-3", domainId: "d3", moduleId: "m11", lessonId: "l1101", difficulty: "advanced", type: "ordering",
    prompt: "Order the steps of a SQL-native RAG pipeline.",
    options: [["retrieve", "Retrieve top-k rows via vector/hybrid search"], ["json", "Convert rows to JSON"], ["call", "Call the model via sp_invoke_external_rest_endpoint"], ["extract", "Extract the model's answer"]],
    correct: ["retrieve", "json", "call", "extract"],
    explanation: "RAG order: retrieve relevant rows, serialize to JSON, call the model with a grounded prompt, then extract the response." }),

  // l1102 RAG json/responses
  q({ id: "q-l1102-1", domainId: "d3", moduleId: "m11", lessonId: "l1102", difficulty: "advanced",
    prompt: "How should AI-generated (natural-language-to-SQL) queries be executed safely?",
    options: [["a", "Directly as sysadmin for convenience"], ["b", "Validated, read-only, least-privilege, with destructive statements blocked"], ["c", "Without any review"], ["d", "Only at night"]],
    correct: ["b"],
    explanation: "Treat generated SQL as untrusted: validate (e.g., allow only SELECT), run as least-privilege read-only (reinforced by RLS), and block DDL/DML." }),
  q({ id: "q-l1102-2", domainId: "d3", moduleId: "m11", lessonId: "l1102", difficulty: "advanced",
    prompt: "Which functions convert rows to JSON for a model and then extract the model's answer?",
    options: [["a", "FOR JSON to build the payload; JSON_VALUE/OPENJSON to extract"], ["b", "BULK INSERT and BCP"], ["c", "PIVOT and UNPIVOT"], ["d", "STUFF and REPLACE only"]],
    correct: ["a"],
    explanation: "FOR JSON shapes the payload sent to the model; JSON_VALUE/OPENJSON parse the JSON response." }),
];
