import { q } from "./_build";

export const D2_QUESTIONS = [
  // l0501 encryption
  q({ id: "q-l0501-1", domainId: "d2", moduleId: "m05", lessonId: "l0501", difficulty: "advanced",
    prompt: "A requirement states that even DBAs must never see credit-card numbers in plaintext. Which feature meets this?",
    options: [["a", "Transparent Data Encryption"], ["b", "Always Encrypted"], ["c", "Dynamic Data Masking"], ["d", "Row-Level Security"]],
    correct: ["b"],
    explanation: "Always Encrypted encrypts on the client; keys never reach the server, so DBAs cannot see plaintext. TDE only protects data at rest and is transparent to admins." }),
  q({ id: "q-l0501-2", domainId: "d2", moduleId: "m05", lessonId: "l0501", difficulty: "intermediate",
    prompt: "What do secure enclaves add to Always Encrypted?",
    options: [["a", "Automatic backups"], ["b", "Richer server-side operations (e.g., range, pattern) on encrypted columns"], ["c", "Compression"], ["d", "Replication"]],
    correct: ["b"],
    explanation: "Secure enclaves allow certain comparisons/computations (pattern matching, range) on Always Encrypted data inside a protected memory region." }),
  q({ id: "q-l0501-3", domainId: "d2", moduleId: "m05", lessonId: "l0501", difficulty: "beginner",
    prompt: "Which feature encrypts the entire database at rest, transparently to queries?",
    options: [["a", "TDE"], ["b", "Always Encrypted"], ["c", "DDM"], ["d", "RLS"]],
    correct: ["a"],
    explanation: "Transparent Data Encryption encrypts data files at rest and is transparent to applications and queries." }),

  // l0502 DDM
  q({ id: "q-l0502-1", domainId: "d2", moduleId: "m05", lessonId: "l0502", difficulty: "beginner",
    prompt: "Which statement about Dynamic Data Masking is correct?",
    options: [["a", "It encrypts the stored data"], ["b", "It masks values in results for users lacking UNMASK, but data is stored in clear"], ["c", "It replaces Row-Level Security"], ["d", "It prevents all inference of the real values"]],
    correct: ["b"],
    explanation: "DDM is presentation-layer masking; underlying data is unchanged, and privileged users (UNMASK) see real values. It is not encryption and can be inferred without proper controls." }),
  q({ id: "q-l0502-2", domainId: "d2", moduleId: "m05", lessonId: "l0502", difficulty: "beginner",
    prompt: "Which permission lets a user see unmasked values?",
    options: [["a", "SELECT"], ["b", "UNMASK"], ["c", "CONTROL SERVER"], ["d", "VIEW DEFINITION"]],
    correct: ["b"],
    explanation: "The UNMASK permission reveals real values behind Dynamic Data Masking." }),

  // l0503 RLS (flagship)
  q({ id: "q-l0503-1", domainId: "d2", moduleId: "m05", lessonId: "l0503", difficulty: "advanced",
    prompt: "In SQL Server RLS, which predicate type silently removes rows from SELECT results?",
    options: [["a", "BLOCK predicate"], ["b", "FILTER predicate"], ["c", "CHECK constraint"], ["d", "DENY"]],
    correct: ["b"],
    explanation: "FILTER predicates apply to reads and silently exclude rows; BLOCK predicates restrict writes." }),
  q({ id: "q-l0503-2", domainId: "d2", moduleId: "m05", lessonId: "l0503", difficulty: "advanced",
    prompt: "An RLS predicate function must be:",
    options: [["a", "A multi-statement TVF"], ["b", "An inline TVF with SCHEMABINDING"], ["c", "A scalar UDF"], ["d", "A stored procedure"]],
    correct: ["b"],
    explanation: "RLS predicate functions must be inline table-valued functions WITH SCHEMABINDING for correctness and performance." }),
  q({ id: "q-l0503-3", domainId: "d2", moduleId: "m05", lessonId: "l0503", difficulty: "advanced",
    prompt: "Which stored procedure sets a read-only tenant id for the connection to drive an RLS predicate?",
    options: [["a", "sp_executesql"], ["b", "sp_set_session_context"], ["c", "sp_addrolemember"], ["d", "sp_configure"]],
    correct: ["b"],
    explanation: "sp_set_session_context with @read_only = 1 sets a value (e.g., TenantId) the predicate reads via SESSION_CONTEXT and that can't be overwritten." }),
  q({ id: "q-l0503-4", domainId: "d2", moduleId: "m05", lessonId: "l0503", difficulty: "advanced",
    prompt: "A tenant can't read other tenants' rows but can INSERT rows with another tenant's id. What's missing?",
    options: [["a", "A FILTER predicate"], ["b", "A BLOCK predicate"], ["c", "A clustered index"], ["d", "TDE"]],
    correct: ["b"],
    explanation: "A FILTER predicate handles reads; you also need a BLOCK predicate (AFTER INSERT/UPDATE) to prevent writing rows outside the tenant's scope." }),
  q({ id: "q-l0503-5", domainId: "d2", moduleId: "m05", lessonId: "l0503", difficulty: "advanced",
    prompt: "You must implement per-tenant row filtering on MySQL, which has no native RLS. What's the correct approach?",
    options: [["a", "Use CREATE SECURITY POLICY"], ["b", "Expose filtered views and revoke base-table access"], ["c", "Use DBMS_RLS"], ["d", "Enable ROW LEVEL SECURITY on the table"]],
    correct: ["b"],
    explanation: "MySQL has no engine-level RLS; the standard pattern is filtered views plus revoking base-table privileges. DBMS_RLS is Oracle; SECURITY POLICY is SQL Server; ENABLE ROW LEVEL SECURITY is PostgreSQL." }),

  // l0504 permissions/passwordless
  q({ id: "q-l0504-1", domainId: "d2", moduleId: "m05", lessonId: "l0504",
    prompt: "A user is a member of two roles: one GRANTs SELECT, one DENYs SELECT on the same table. What happens?",
    options: [["a", "SELECT is allowed"], ["b", "SELECT is denied"], ["c", "Depends on order"], ["d", "Error"]],
    correct: ["b"],
    explanation: "DENY overrides GRANT, so the user cannot SELECT." }),
  q({ id: "q-l0504-2", domainId: "d2", moduleId: "m05", lessonId: "l0504",
    prompt: "What is the recommended way for an app to connect to Azure SQL without storing secrets?",
    options: [["a", "SQL login with a shared password"], ["b", "Managed Identity with Microsoft Entra authentication"], ["c", "A connection string in the repo"], ["d", "Anonymous access"]],
    correct: ["b"],
    explanation: "Passwordless access via Microsoft Entra + Managed Identity avoids stored secrets and is the recommended pattern." }),

  // l0505 auditing/endpoints
  q({ id: "q-l0505-1", domainId: "d2", moduleId: "m05", lessonId: "l0505", difficulty: "advanced",
    prompt: "How should you secure an AI model endpoint that SQL calls?",
    options: [["a", "Embed an API key in the T-SQL"], ["b", "Use Managed Identity"], ["c", "Disable TLS"], ["d", "Allow anonymous access"]],
    correct: ["b"],
    explanation: "Secure model endpoints with Managed Identity to avoid stored keys; scope access tightly." }),
  q({ id: "q-l0505-2", domainId: "d2", moduleId: "m05", lessonId: "l0505", difficulty: "advanced",
    prompt: "Data API builder endpoints should enforce authorization how?",
    options: [["a", "Globally allow all"], ["b", "Per-entity, per-role permissions"], ["c", "Only at the network layer"], ["d", "Not at all; DAB is internal"]],
    correct: ["b"],
    explanation: "DAB supports per-entity, per-role authorization; combine with authentication and network limits." }),

  // l0601 config
  q({ id: "q-l0601-1", domainId: "d2", moduleId: "m06", lessonId: "l0601",
    prompt: "Which command changes per-database settings like MAXDOP?",
    options: [["a", "ALTER DATABASE SCOPED CONFIGURATION"], ["b", "sp_configure only"], ["c", "DBCC FREEPROCCACHE"], ["d", "SET STATISTICS IO ON"]],
    correct: ["a"],
    explanation: "ALTER DATABASE SCOPED CONFIGURATION sets database-level options such as MAXDOP and legacy cardinality estimation." }),
  q({ id: "q-l0601-2", domainId: "d2", moduleId: "m06", lessonId: "l0601",
    prompt: "What does the database compatibility level primarily control?",
    options: [["a", "Backup compression"], ["b", "Which optimizer behaviors/features are enabled"], ["c", "Disk sector size"], ["d", "Network protocol"]],
    correct: ["b"],
    explanation: "Compatibility level governs optimizer behaviors and feature availability, letting you adopt changes safely." }),

  // l0602 isolation
  q({ id: "q-l0602-1", domainId: "d2", moduleId: "m06", lessonId: "l0602", difficulty: "advanced",
    prompt: "Which isolation level prevents phantom reads?",
    options: [["a", "READ UNCOMMITTED"], ["b", "READ COMMITTED"], ["c", "REPEATABLE READ"], ["d", "SERIALIZABLE"]],
    correct: ["d"],
    explanation: "SERIALIZABLE prevents phantoms; REPEATABLE READ prevents non-repeatable reads but not phantoms." }),
  q({ id: "q-l0602-2", domainId: "d2", moduleId: "m06", lessonId: "l0602", difficulty: "advanced",
    prompt: "You want consistent reads without readers blocking writers in a read-heavy OLTP database. What should you enable?",
    options: [["a", "READ UNCOMMITTED / NOLOCK"], ["b", "Read Committed Snapshot Isolation (RCSI)"], ["c", "SERIALIZABLE"], ["d", "Table locks"]],
    correct: ["b"],
    explanation: "RCSI uses row versioning so reads see a consistent committed version without blocking writers, unlike NOLOCK which permits dirty reads." }),
  q({ id: "q-l0602-3", domainId: "d2", moduleId: "m06", lessonId: "l0602", difficulty: "advanced",
    prompt: "Which anomaly can occur under READ UNCOMMITTED?",
    options: [["a", "Dirty reads"], ["b", "No anomalies"], ["c", "Only phantoms"], ["d", "Deadlocks are eliminated"]],
    correct: ["a"],
    explanation: "READ UNCOMMITTED permits dirty reads (seeing uncommitted changes)." }),

  // l0603 plans/dmvs/query store
  q({ id: "q-l0603-1", domainId: "d2", moduleId: "m06", lessonId: "l0603", difficulty: "advanced",
    prompt: "A query regressed after a plan change. Which feature lets you pin the previously good plan?",
    options: [["a", "Query Store (force plan)"], ["b", "DBCC CHECKDB"], ["c", "sp_who2"], ["d", "Full-text index"]],
    correct: ["a"],
    explanation: "Query Store captures plan history and lets you force a specific (good) plan to fix regressions." }),
  q({ id: "q-l0603-2", domainId: "d2", moduleId: "m06", lessonId: "l0603", difficulty: "advanced",
    prompt: "Which DMV helps find currently executing requests and their blockers?",
    options: [["a", "sys.dm_exec_requests"], ["b", "sys.tables"], ["c", "sys.databases"], ["d", "sys.columns"]],
    correct: ["a"],
    explanation: "sys.dm_exec_requests shows active requests including blocking_session_id." }),
  q({ id: "q-l0603-3", domainId: "d2", moduleId: "m06", lessonId: "l0603", difficulty: "advanced",
    prompt: "A big discrepancy between estimated and actual row counts in a plan usually indicates:",
    options: [["a", "Perfect statistics"], ["b", "A cardinality estimation problem (e.g., stale stats)"], ["c", "A network error"], ["d", "Nothing important"]],
    correct: ["b"],
    explanation: "Large estimated-vs-actual gaps point to cardinality estimation issues such as stale/missing statistics or non-sargable predicates." }),

  // l0604 blocking/deadlocks
  q({ id: "q-l0604-1", domainId: "d2", moduleId: "m06", lessonId: "l0604", difficulty: "advanced",
    prompt: "Which strategy most directly prevents many deadlocks?",
    options: [["a", "Accessing objects in a consistent order across transactions"], ["b", "Longer transactions"], ["c", "Removing all indexes"], ["d", "Using READ UNCOMMITTED everywhere"]],
    correct: ["a"],
    explanation: "Consistent object access order avoids the circular wait that causes deadlocks; shorter transactions and good indexing also help." }),
  q({ id: "q-l0604-2", domainId: "d2", moduleId: "m06", lessonId: "l0604", difficulty: "advanced",
    prompt: "How do you capture deadlock details for analysis?",
    options: [["a", "Extended Events deadlock graph"], ["b", "sp_help"], ["c", "SELECT @@VERSION"], ["d", "DBCC SHRINKDATABASE"]],
    correct: ["a"],
    explanation: "Extended Events capture the deadlock graph, showing the processes, resources, and victim." }),

  // l0701 sql db projects
  q({ id: "q-l0701-1", domainId: "d2", moduleId: "m07", lessonId: "l0701",
    prompt: "What artifact does building a SQL Database Project produce, and how is it deployed?",
    options: [["a", "A dacpac deployed by diffing against the target"], ["b", "A .bak restored to the server"], ["c", "A CSV imported by BULK INSERT"], ["d", "A .exe that runs migrations in order"]],
    correct: ["a"],
    explanation: "SQL Database Projects build a dacpac; deployment compares the model to the target and applies the difference declaratively." }),
  q({ id: "q-l0701-2", domainId: "d2", moduleId: "m07", lessonId: "l0701",
    prompt: "Which project format is the modern, cross-platform recommendation?",
    options: [["a", "SDK-style"], ["b", "Classic .dtsx"], ["c", ".rdl"], ["d", ".bacpac only"]],
    correct: ["a"],
    explanation: "SDK-style SQL projects are the current recommended, cross-platform format." }),

  // l0702 source control
  q({ id: "q-l0702-1", domainId: "d2", moduleId: "m07", lessonId: "l0702",
    prompt: "Where should static/reference (lookup) data live in a SQL Database Project?",
    options: [["a", "In production only"], ["b", "In source control, typically as post-deployment scripts"], ["c", "In a spreadsheet"], ["d", "It cannot be versioned"]],
    correct: ["b"],
    explanation: "Reference data is versioned in the project, usually via post-deployment scripts, so environments stay consistent." }),
  q({ id: "q-l0702-2", domainId: "d2", moduleId: "m07", lessonId: "l0702",
    prompt: "Which practice enforces review before schema changes merge?",
    options: [["a", "Pull requests with branch policies"], ["b", "Committing directly to main"], ["c", "Emailing scripts"], ["d", "Disabling CI"]],
    correct: ["a"],
    explanation: "Pull requests plus branch policies require review/checks before merging changes." }),

  // l0703 testing/secrets
  q({ id: "q-l0703-1", domainId: "d2", moduleId: "m07", lessonId: "l0703",
    prompt: "Where should database connection secrets be stored for a deployment pipeline?",
    options: [["a", "In the SQL project files"], ["b", "In a secret store (e.g., Key Vault / pipeline secrets)"], ["c", "In a README"], ["d", "In the dacpac"]],
    correct: ["b"],
    explanation: "Secrets belong in a managed secret store referenced at deploy time, never committed to the project." }),
  q({ id: "q-l0703-2", domainId: "d2", moduleId: "m07", lessonId: "l0703",
    prompt: "An integration test for a database change typically runs against:",
    options: [["a", "A deployed copy of the schema"], ["b", "The source .sql files only"], ["c", "Production during business hours"], ["d", "A spreadsheet mock"]],
    correct: ["a"],
    explanation: "Integration tests exercise a deployed schema to validate real behavior end to end." }),

  // l0704 drift/pipelines
  q({ id: "q-l0704-1", domainId: "d2", moduleId: "m07", lessonId: "l0704", difficulty: "advanced",
    prompt: "Schema drift is best described as:",
    options: [["a", "The deployed database diverging from the source-controlled model"], ["b", "Index fragmentation"], ["c", "Slow queries"], ["d", "A backup failure"]],
    correct: ["a"],
    explanation: "Schema drift is when the target database no longer matches the project's declared model." }),
  q({ id: "q-l0704-2", domainId: "d2", moduleId: "m07", lessonId: "l0704", difficulty: "advanced", type: "multi",
    prompt: "Which controls gate production database deployments? (Select all that apply.)",
    options: [["a", "Branch policies"], ["b", "Approvals"], ["c", "Code owners"], ["d", "Disabling all reviews"]],
    correct: ["a", "b", "c"],
    explanation: "Branch policies, approvals, and code owners all gate deployments; disabling reviews would remove the control." }),

  // l0801 DAB config
  q({ id: "q-l0801-1", domainId: "d2", moduleId: "m08", lessonId: "l0801",
    prompt: "In Data API builder, what does an 'entity' represent?",
    options: [["a", "A physical server"], ["b", "A mapped database object (table/view/proc) exposed via the API"], ["c", "A user account"], ["d", "A backup file"]],
    correct: ["b"],
    explanation: "A DAB entity maps a database object and its permissions to REST/GraphQL endpoints." }),
  q({ id: "q-l0801-2", domainId: "d2", moduleId: "m08", lessonId: "l0801",
    prompt: "How is Data API builder primarily configured?",
    options: [["a", "By hand-writing a REST service in C#"], ["b", "Through a configuration file (dab-config.json)"], ["c", "Via SSMS wizards only"], ["d", "By editing system tables"]],
    correct: ["b"],
    explanation: "DAB is configuration-driven via a config file defining the data source and entities." }),

  // l0802 rest/graphql
  q({ id: "q-l0802-1", domainId: "d2", moduleId: "m08", lessonId: "l0802",
    prompt: "Which capabilities can DAB entities be configured with to improve efficiency?",
    type: "multi",
    options: [["a", "Caching"], ["b", "Pagination"], ["c", "Filtering"], ["d", "Automatic index rebuilds"]],
    correct: ["a", "b", "c"],
    explanation: "DAB supports caching, pagination, searching, and filtering. Index maintenance is a database concern, not a DAB entity setting." }),
  q({ id: "q-l0802-2", domainId: "d2", moduleId: "m08", lessonId: "l0802",
    prompt: "Besides tables, DAB can expose which objects?",
    options: [["a", "Only tables"], ["b", "Views and stored procedures, plus GraphQL relationships"], ["c", "Only stored procedures"], ["d", "Only GraphQL, never REST"]],
    correct: ["b"],
    explanation: "DAB can expose tables, views, and stored procedures, and configure GraphQL relationships." }),

  // l0803 azure monitor
  q({ id: "q-l0803-1", domainId: "d2", moduleId: "m08", lessonId: "l0803",
    prompt: "Which Azure Monitor component provides end-to-end request and dependency tracing?",
    options: [["a", "Application Insights"], ["b", "Log Analytics"], ["c", "Azure Backup"], ["d", "Azure Policy"]],
    correct: ["a"],
    explanation: "Application Insights provides distributed tracing of requests and dependencies, including AI service calls." }),
  q({ id: "q-l0803-2", domainId: "d2", moduleId: "m08", lessonId: "l0803",
    prompt: "Which service stores telemetry you query with KQL?",
    options: [["a", "Log Analytics"], ["b", "Blob Storage"], ["c", "Service Bus"], ["d", "Key Vault"]],
    correct: ["a"],
    explanation: "Log Analytics workspaces store telemetry queried with Kusto Query Language (KQL)." }),

  // l0804 change handling
  q({ id: "q-l0804-1", domainId: "d2", moduleId: "m08", lessonId: "l0804", difficulty: "advanced",
    prompt: "You need lightweight detection of which rows changed (not full history) to drive re-processing. Which feature fits?",
    options: [["a", "Change Data Capture"], ["b", "Change Tracking"], ["c", "TDE"], ["d", "Query Store"]],
    correct: ["b"],
    explanation: "Change Tracking is lightweight and reports which rows changed; CDC captures full before/after history at higher cost." }),
  q({ id: "q-l0804-2", domainId: "d2", moduleId: "m08", lessonId: "l0804", difficulty: "advanced",
    prompt: "Which option reacts to table changes with serverless code?",
    options: [["a", "Azure Functions with SQL trigger binding"], ["b", "DBCC CHECKDB"], ["c", "sp_configure"], ["d", "A clustered index"]],
    correct: ["a"],
    explanation: "Azure Functions with the SQL trigger binding run code in response to table changes, enabling event-driven workflows." }),
];
