import type { Domain, Module } from "@/lib/types";

/**
 * DP-800 curriculum structure, mapped to the official "skills measured"
 * outline (as of March 12, 2026).
 * Source: https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/dp-800
 * Accessed 2026-07-28.
 */

export const DOMAINS: Domain[] = [
  {
    id: "d1",
    order: 1,
    code: "D1",
    title: "Design and develop database solutions",
    weight: "35-40%",
    summary:
      "Design database objects, build programmability objects, write advanced T-SQL, and use AI-assisted developer tools.",
    accent: "--sky-cyan",
    moduleIds: ["m01", "m02", "m03", "m04"],
  },
  {
    id: "d2",
    order: 2,
    code: "D2",
    title: "Secure, optimize, and deploy database solutions",
    weight: "35-40%",
    summary:
      "Secure data, tune performance, ship changes with SQL Database Projects, and integrate with Azure services.",
    accent: "--hub-green",
    moduleIds: ["m05", "m06", "m07", "m08"],
  },
  {
    id: "d3",
    order: 3,
    code: "D3",
    title: "Implement AI capabilities in database solutions",
    weight: "25-30%",
    summary:
      "Work with external models and embeddings, build intelligent search, and implement retrieval-augmented generation.",
    accent: "--corgi-orange",
    moduleIds: ["m09", "m10", "m11"],
  },
];

export const MODULES: Module[] = [
  {
    id: "m01",
    domainId: "d1",
    order: 1,
    code: "01",
    title: "Design and implement database objects",
    summary: "Tables, specialized tables, JSON columns, constraints, sequences, and partitioning.",
    officialSkills: [
      "Design and implement tables, including data types, size, columns, indexes, and column store indexes",
      "Design and implement specialized tables, including in-memory, temporal, external, ledger, and graph",
      "Design and implement JSON columns and indexes",
      "Design and implement database constraints, including PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, and DEFAULT",
      "Design and implement SEQUENCES",
      "Design and implement partitioning for tables and indexes",
    ],
    lessonIds: ["l0101", "l0102", "l0103", "l0104", "l0105", "l0106"],
  },
  {
    id: "m02",
    domainId: "d1",
    order: 2,
    code: "02",
    title: "Implement programmability objects",
    summary: "Views, scalar and table-valued functions, stored procedures, and triggers.",
    officialSkills: [
      "Create views",
      "Create scalar functions",
      "Create table-valued functions",
      "Create stored procedures",
      "Create triggers",
    ],
    lessonIds: ["l0201", "l0202", "l0203"],
  },
  {
    id: "m03",
    domainId: "d1",
    order: 3,
    code: "03",
    title: "Write advanced T-SQL code",
    summary: "CTEs, window functions, JSON functions, regex, fuzzy matching, graph queries, and error handling.",
    officialSkills: [
      "Write common table expressions (CTEs)",
      "Write queries that include window functions",
      "Write queries that include JSON functions (JSON_OBJECT, JSON_ARRAY, OPENJSON, JSON_VALUE, ...)",
      "Write queries that include regular expressions (REGEXP_LIKE, REGEXP_REPLACE, ...)",
      "Write queries that include fuzzy string matching (EDIT_DISTANCE, JARO_WINKLER_DISTANCE, ...)",
      "Write graph queries that use the MATCH operator",
      "Write correlated queries",
      "Implement error handling",
    ],
    lessonIds: ["l0301", "l0302", "l0303", "l0304", "l0305"],
  },
  {
    id: "m04",
    domainId: "d1",
    order: 4,
    code: "04",
    title: "Design SQL solutions by using AI-assisted tools",
    summary: "GitHub Copilot, Copilot in Fabric, model and MCP tool configuration, and MCP server endpoints.",
    officialSkills: [
      "Interpret security impact of using AI-assisted tools",
      "Enable GitHub Copilot and Microsoft Copilot in Fabric",
      "Configure model and Model Context Protocol (MCP) tool options in a Copilot chat session",
      "Create and configure GitHub Copilot instruction files",
      "Connect to MCP server endpoints, including Microsoft SQL Server and Fabric lakehouse",
    ],
    lessonIds: ["l0401", "l0402", "l0403"],
  },
  {
    id: "m05",
    domainId: "d2",
    order: 1,
    code: "05",
    title: "Implement data security and compliance",
    summary: "Encryption, Dynamic Data Masking, Row-Level Security, permissions, auditing, and secure endpoints.",
    officialSkills: [
      "Design and implement data encryption, including Always Encrypted and column-level encryption",
      "Design and implement Dynamic Data Masking",
      "Design and implement Row-Level Security (RLS)",
      "Design and implement object-level permissions",
      "Implement secure database access, including passwordless",
      "Implement auditing",
      "Secure model endpoints, including Managed Identity",
      "Secure GraphQL, REST, and MCP endpoints",
    ],
    lessonIds: ["l0501", "l0502", "l0503", "l0504", "l0505"],
  },
  {
    id: "m06",
    domainId: "d2",
    order: 2,
    code: "06",
    title: "Optimize database performance",
    summary: "Configuration, isolation levels and concurrency, execution plans and DMVs, blocking and deadlocks.",
    officialSkills: [
      "Recommend database configurations",
      "Preserve data integrity and consistency by using transaction isolation levels and concurrency controls",
      "Evaluate query performance by using execution plans, DMVs, Query Store, and Query Performance Insight",
      "Identify and resolve query performance issues, including blocking and deadlocks",
    ],
    lessonIds: ["l0601", "l0602", "l0603", "l0604"],
  },
  {
    id: "m07",
    domainId: "d2",
    order: 3,
    code: "07",
    title: "Implement CI/CD by using SQL Database Projects",
    summary: "SQL Database Projects, source control, testing, secrets, schema drift, and deployment pipelines.",
    officialSkills: [
      "Design and implement a testing strategy, including unit tests and integration tests",
      "Create and manage reference/static data in source control",
      "Create, build, and validate database models by using SQL Database Projects (SDK-style)",
      "Configure source control; manage branching, pull requests, and conflict resolution",
      "Implement secrets management",
      "Detect schema drift by using SQL Database Projects",
      "Update a project and deploy changes; implement deployment pipeline controls",
    ],
    lessonIds: ["l0701", "l0702", "l0703", "l0704"],
  },
  {
    id: "m08",
    domainId: "d2",
    order: 4,
    code: "08",
    title: "Integrate SQL solutions with Azure services",
    summary: "Data API builder, REST/GraphQL endpoints, Azure Monitor, and change handling (CDC, CT, CES).",
    officialSkills: [
      "Create configuration files for Data API builder (DAB)",
      "Configure entities for REST and GraphQL, including caching, pagination, searching, and filtering",
      "Configure and implement DAB deployment",
      "Recommend Azure Monitor configurations, including Application Insights and Log Analytics",
      "Handle changes by using CES, CDC, Change Tracking, Azure Functions with SQL trigger binding, or Logic Apps",
    ],
    lessonIds: ["l0801", "l0802", "l0803", "l0804"],
  },
  {
    id: "m09",
    domainId: "d3",
    order: 1,
    code: "09",
    title: "Design and implement models and embeddings",
    summary: "External models, embedding maintenance methods, chunking, and generating embeddings.",
    officialSkills: [
      "Evaluate external models, including multimodal, multilanguage, sizes, and structured output",
      "Create and manage external models",
      "Choose an embedding maintenance method (triggers, Change Tracking, Azure Functions, Logic Apps, CDC, CES, Microsoft Foundry)",
      "Identify which columns to include in embeddings",
      "Design and implement chunks for embeddings",
      "Generate embeddings",
    ],
    lessonIds: ["l0901", "l0902", "l0903"],
  },
  {
    id: "m10",
    domainId: "d3",
    order: 2,
    code: "10",
    title: "Design and implement intelligent search",
    summary: "Full-text, vector data type and indexes, ANN vs ENN, hybrid search, and RRF.",
    officialSkills: [
      "Choose from full-text, semantic vector, and hybrid search",
      "Implement full-text search",
      "Design for vector data, including vector data type, vector indexes, and size",
      "Use vector-related types and functions (VECTOR_NORMALIZE, VECTOR_DISTANCE, VECTORPROPERTY, VECTOR_SEARCH)",
      "Choose between ANN and ENN; evaluate vector index types and metrics",
      "Implement vector search, hybrid search, and reciprocal rank fusion (RRF)",
      "Evaluate performance of vector and hybrid search",
    ],
    lessonIds: ["l1001", "l1002", "l1003", "l1004"],
  },
  {
    id: "m11",
    domainId: "d3",
    order: 3,
    code: "11",
    title: "Design and implement retrieval-augmented generation (RAG)",
    summary: "RAG use cases, sp_invoke_external_rest_endpoint, JSON conversion, and handling model responses.",
    officialSkills: [
      "Identify use cases for RAG",
      "Create a prompt by using the sp_invoke_external_rest_endpoint stored procedure",
      "Convert structured data to JSON for language model processing",
      "Send results to a language model and extract language model responses",
    ],
    lessonIds: ["l1101", "l1102"],
  },
];

export const EXAM_META = {
  code: "DP-800",
  title: "Developing AI-Enabled Database Solutions",
  credential: "Microsoft Certified: SQL AI Developer Associate",
  durationMinutes: 120,
  passingScore: 700,
  skillsAsOf: "March 12, 2026",
  platforms: ["SQL Server 2025", "Azure SQL", "SQL databases in Microsoft Fabric"],
  studyGuideUrl:
    "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/dp-800",
  certificationUrl:
    "https://learn.microsoft.com/en-us/credentials/certifications/developing-ai-enabled-database-solutions/",
};
