import type { Question } from '../types';

/**
 * GH-200 domain 1 practice bank — Author and manage workflows (20
 * questions). Triggers, dispatch and call inputs, job graphs, environment
 * files, service containers, matrix strategy, anchors, contexts, tooling,
 * caching, outputs, and summaries. Mix: 13 single, 3 multi, 4 coding items
 * (matrix and context fill-ins, a GITHUB_OUTPUT spot-the-bug, and a
 * workflow-lifecycle ordering).
 */
export const questions: Question[] = [
  {
    id: 'gh200-d1-q01',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-triggers',
    kind: 'single',
    stem: 'A release team wants a workflow to run every weekday at 03:30 UTC. Which `on:` block does that?',
    options: [
      '`on:\n  timer: 03:30 weekdays`',
      "`on:\n  cron: '30 3 * * 1-5'`",
      "`on:\n  schedule:\n    - cron: '30 3 * * 1-5'`",
      '`on:\n  schedule:\n    - timer: 03:30 UTC`',
    ],
    answerIndex: 2,
    explanation:
      'Timed workflows use `schedule` with a list of `cron` strings in minute-hour-day-month-weekday order, so `30 3 * * 1-5` fires at 03:30 UTC Monday through Friday. There is no `timer` key, and `cron` never sits directly under `on`.',
    docId: 'workflow-events',
  },
  {
    id: 'gh200-d1-q02',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-triggers',
    kind: 'single',
    stem: 'Tests should run on pushes, but only when something under `src/` or `tests/` changes. Which filter does that?',
    options: [
      '`on:\n  push:\n    branches: [src/**, tests/**]`',
      '`on:\n  push:\n    paths: [src/**, tests/**]`',
      '`on:\n  push:\n    paths-ignore: [src/**, tests/**]`',
      '`on:\n  push:\n    filters: [src/**, tests/**]`',
    ],
    answerIndex: 1,
    explanation:
      '`paths` narrows a push trigger to commits that touch the given globs — a docs-only change will not start the workflow. `paths-ignore` is the inverse (run unless these change), and `branches` filters by ref name, never by file path.',
    docId: 'workflow-events',
  },
  {
    id: 'gh200-d1-q03',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-dispatch-call-inputs',
    kind: 'single',
    stem: 'A maintenance workflow gets a manual trigger, and whoever starts it must pick the target environment from a fixed list of three names. Which `workflow_dispatch` input fits?',
    options: [
      'An input with `type: list`',
      'An input with `type: choice` plus an `options:` list',
      'An input with `type: enum`',
      'An input with `type: boolean` rendered as a dropdown',
    ],
    answerIndex: 1,
    explanation:
      'For a fixed shortlist, `choice` is the type: it renders a dropdown built from its `options` list, so the environment is picked from exactly the values you allow. `boolean`, `string`, `number`, and `environment` are the other supported types — there is no `list` or `enum`.',
    docId: 'workflow-syntax',
  },
  {
    id: 'gh200-d1-q04',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-dispatch-call-inputs',
    kind: 'single',
    stem: 'A reusable workflow declares a required `deploy-key` secret. A caller wants to forward everything it can see without naming secrets one by one. Which call does that?',
    options: [
      '`uses:` the workflow with `secrets: all`',
      '`uses:` the workflow with `secrets: env`',
      '`uses:` the workflow with `secrets: inherit`',
      'Nothing — a called workflow receives all caller secrets automatically',
    ],
    answerIndex: 2,
    explanation:
      '`secrets: inherit` forwards every secret the calling workflow can see, in place of an explicit name-by-name map. Nothing is passed implicitly: without `inherit` or explicit names, the called workflow sees none of the caller’s secrets.',
    docId: 'reuse-workflows',
  },
  {
    id: 'gh200-d1-q05',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-jobs-steps',
    kind: 'single',
    stem: 'In a workflow, job `deploy` may start only after job `build` has finished successfully. Which key expresses that?',
    options: [
      '`order: build`',
      '`needs: build`',
      '`after: build`',
      '`depends_on: build`',
    ],
    answerIndex: 1,
    explanation:
      '`needs: build` creates the dependency: `deploy` waits for `build`, and it is skipped entirely when `build` fails. Chains of `needs` form a graph GitHub executes in parallel wherever nothing forces an ordering.',
    docId: 'workflow-syntax',
  },
  {
    id: 'gh200-d1-q06',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-jobs-steps',
    kind: 'single',
    stem: 'A cleanup step must run at the end of the job even when earlier steps failed. Which `if:` condition does that?',
    options: [
      '`if: success()`',
      '`if: failure()`',
      '`if: cancelled()`',
      '`if: always()`',
    ],
    answerIndex: 3,
    explanation:
      '`always()` lets a step run no matter how the preceding ones ended — the tool for cleanup and reporting. `failure()` runs only after a failure, `cancelled()` only when the run was cancelled, and `success()` is the default you never need to write.',
    docId: 'workflow-syntax',
  },
  {
    id: 'gh200-d1-q07',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-commands-env',
    kind: 'single',
    stem: 'A step computes `VERSION=2.1.0`, and later steps in the same job need it as an environment variable. Which mechanism does that?',
    options: [
      'Append `VERSION=2.1.0` to the `$GITHUB_ENV` file',
      'Print `VERSION=2.1.0` with `echo` so the runner captures stdout',
      'Declare it in the workflow-level `env:` block when authoring',
      'Add the line to `$GITHUB_PATH`',
    ],
    answerIndex: 0,
    explanation:
      'A line appended to `$GITHUB_ENV` becomes an environment variable for every later step in the job. Plain `echo` only writes to the log, workflow `env:` is fixed at authoring time, and `$GITHUB_PATH` extends `PATH` with directories, not variables.',
    docId: 'use-variables',
  },
  {
    id: 'gh200-d1-q08',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-service-containers',
    kind: 'single',
    stem: 'A job starts a Redis service container and its steps talk to it on `localhost:6379`. Which `ports` entry makes that work?',
    options: [
      '`ports: - 6379` (container port only)',
      '`ports: - 127.0.0.1:6379` (host address only)',
      '`ports: - 6379:6379` (host:container)',
      'No `ports` key — service containers are always reachable on localhost',
    ],
    answerIndex: 2,
    explanation:
      'Service-container ports are written `host:container`, so `6379:6379` publishes the container’s Redis to the job on the runner host’s localhost. Without the mapping the port is not exposed to the job at all, and a lone number leaves the host side unspecified.',
    docId: 'service-containers',
  },
  {
    id: 'gh200-d1-q09',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-matrix',
    kind: 'single',
    stem: 'A 12-combination matrix should always run to completion so the team sees every failure, not just the first. Which setting does that?',
    options: [
      '`continue-on-error: true` on the job',
      '`strategy:\n  fail-fast: false`',
      '`strategy:\n  max-parallel: 12`',
      '`retry: full` on the failing job',
    ],
    answerIndex: 1,
    explanation:
      '`fail-fast: false` stops GitHub from cancelling the remaining in-flight combinations when one fails, so the whole matrix reports. `max-parallel` caps concurrency, and `continue-on-error` merely repaints failure as success — it does not keep the matrix running.',
    docId: 'workflow-syntax',
  },
  {
    id: 'gh200-d1-q10',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-yaml-anchors',
    kind: 'single',
    stem: 'Several jobs in one workflow file repeat the same three steps. Which feature collapses the duplication — and what is its reach?',
    options: [
      'A reusable workflow — usable across files and repositories',
      'A composite action — usable across repositories once published',
      'A workflow template — copied into each repository',
      'YAML anchors and aliases — but only inside that one file',
    ],
    answerIndex: 3,
    explanation:
      'An anchor (`&name`) marks a block once and an alias (`*name`) expands it again — inside a single file, which is exactly the fix for repeated steps. Crossing files or repositories needs reusable workflows or composite actions, because anchors never leave their document.',
    docId: 'reuse-config',
  },
  {
    id: 'gh200-d1-q11',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-authoring-tooling',
    kind: 'single',
    stem: 'While editing a workflow in VS Code, a developer wants unknown keys and broken indentation flagged before anything is pushed. What provides that?',
    options: [
      'The GitHub CLI, via `gh workflow lint`',
      'The GitHub Actions extension with the published workflow schema, validating as you type',
      'The web editor on github.com only — desktop editors cannot validate workflows',
      'Nothing — a workflow can only be validated by running it',
    ],
    answerIndex: 1,
    explanation:
      'Editor tooling — the GitHub Actions extension plus the workflow JSON schema — marks invalid keys and structure while you type. Pushing to watch the run fail also works, but it is the slow way to learn about a typo.',
    docId: 'gh-docs-actions',
  },
  {
    id: 'gh200-d1-q12',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-cache-artifacts-retention',
    kind: 'single',
    stem: 'A cache step must try the exact npm lockfile key first, then fall back to any cache saved on the same branch, then the default branch. Which arrangement does that?',
    options: [
      '`key` holds the exact hash; `restore-keys` lists the broader prefixes in fallback order',
      '`restore-keys` holds the exact hash; `key` lists the broader prefixes',
      'Three stacked cache steps, one per fallback level',
      '`key` accepts a list and the action tries each entry in order',
    ],
    answerIndex: 0,
    explanation:
      '`key` names the exact hit to look for; `restore-keys` lists progressively looser prefixes tried on a miss — branch-scoped entries before the default-branch prefix. A fallback restore is then resaved under the exact key once the step completes.',
    docId: 'dependency-caching',
  },
  {
    id: 'gh200-d1-q13',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-summaries-badges',
    kind: 'single',
    stem: 'A workflow should publish a human-readable report — tables, lists, rendered markdown — right on the run page. Which mechanism does that?',
    options: [
      'Echo markdown into the job log between `::group::` markers',
      'Append markdown to the `$GITHUB_STEP_SUMMARY` environment file',
      'Upload a `summary.md` artifact next to the build outputs',
      'Have the workflow open a pull request that carries the report',
    ],
    answerIndex: 1,
    explanation:
      'Whatever a step appends to `$GITHUB_STEP_SUMMARY` renders as markdown on the run page under the job — the built-in home for test tables and release notes. Logs and artifacts hold the same text, but nothing renders them as a report.',
    docId: 'workflow-commands',
  },
  {
    id: 'gh200-d1-q14',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-triggers',
    kind: 'multi',
    stem: 'Which of these can start a workflow? Choose all that apply.',
    options: [
      'A cron schedule via `on: schedule`',
      'A manual run started from the Actions tab via `workflow_dispatch`',
      'A `create` event, such as a new branch or tag',
      'A commit made locally that has not been pushed',
      'Any repository settings change, whatever it is',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Workflows start on GitHub-side signals: schedules, manual dispatch, and repository events like branch or tag creation all qualify. A commit that never reaches GitHub triggers nothing, and settings changes are not workflow events by themselves.',
    docId: 'workflow-events',
  },
  {
    id: 'gh200-d1-q15',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-matrix',
    kind: 'multi',
    stem: 'Which statements about `strategy.matrix` are true? Choose all that apply.',
    options: [
      '`include` adds extra combinations on top of the ones generated from the matrix keys',
      'Setting `fail-fast: false` makes failed combinations retry automatically',
      '`max-parallel: 1` runs the matrix combinations one at a time',
      'Steps read matrix values through the `strategy` context',
      'Every combination of the matrix keys becomes its own job run',
    ],
    answerIndexes: [0, 2, 4],
    explanation:
      'Matrix keys multiply into one run per combination, `include` layers on more, and `max-parallel` throttles how many run at once. Values are read through the `matrix` context — there is no `strategy` context — and `fail-fast` cancels or allows runs, it never retries them.',
    docId: 'workflow-syntax',
  },
  {
    id: 'gh200-d1-q16',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-service-containers',
    kind: 'multi',
    stem: 'Which statements about service containers are true? Choose all that apply.',
    options: [
      'They are Docker containers started before the job’s steps run',
      'The `options:` key passes extra Docker flags, such as `--health-cmd`',
      'They keep running after the job completes, for later debugging',
      'Steps reach them through mapped ports on the runner’s localhost',
      'They can only run images hosted on Docker Hub',
    ],
    answerIndexes: [0, 1, 3],
    explanation:
      'Service containers come up alongside the job and answer on localhost through the mapped ports, with `options:` carrying health checks and other Docker flags. They are torn down with the job, and any registry the runner can pull from works — not just Docker Hub.',
    docId: 'service-containers',
  },
  {
    id: 'gh200-d1-q17',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-matrix',
    kind: 'fill',
    stem: 'Fill in both blanks so the job runs once per OS-and-Node combination and installs the matching Node version.',
    codeTemplate:
      'name: Cross-platform CI\non: push\njobs:\n  test:\n    runs-on: ${{ matrix.os }}\n    strategy:\n      ___:\n        os: [ubuntu-latest, windows-latest]\n        node: [18, 20]\n    steps:\n      - uses: actions/setup-node@v4\n        with:\n          node-version: ${{ ___ }}\n',
    blanks: [
      { answer: 'matrix', alternatives: [] },
      { answer: 'matrix.node', alternatives: [] },
    ],
    explanation:
      'The `matrix:` key sits under `strategy`, and its lists multiply into one job per combination; steps read the current values through the `matrix` context — here `${{ matrix.node }}`. Two OSes times two Node versions means four runs of the same job.',
    docId: 'workflow-syntax',
  },
  {
    id: 'gh200-d1-q18',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-contexts-expressions',
    kind: 'fill',
    stem: 'Complete the branch guard and the commit capture.',
    codeTemplate:
      "name: Guarded deploy\non: push\njobs:\n  deploy:\n    if: github.___ == 'refs/heads/main'\n    runs-on: ubuntu-latest\n    steps:\n      - run: ./deploy.sh\n        env:\n          COMMIT: ${{ ___.sha }}\n",
    blanks: [
      { answer: 'ref', alternatives: [] },
      { answer: 'github', alternatives: [] },
    ],
    explanation:
      'The `github` context carries the event payload: `github.ref` is the full ref that triggered the run, so comparing it to `refs/heads/main` gates deploys to the default branch, and `github.sha` is the exact commit being built.',
    docId: 'contexts',
  },
  {
    id: 'gh200-d1-q19',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-passing-data',
    kind: 'bug',
    stem: 'The second step should print `1.4.0` but the version never arrives. One line fails to expose the output — click it.',
    codeLines: [
      'name: Pass the version along',
      'on: push',
      'jobs:',
      '  build:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - id: prep',
      '        run: echo "version=1.4.0"',
      '      - run: echo "Version is ${{ steps.prep.outputs.version }}"',
    ],
    buggyLineIndex: 7,
    explanation:
      'Step outputs are set by appending `key=value` lines to the `$GITHUB_OUTPUT` file: `echo "version=1.4.0" >> $GITHUB_OUTPUT`. Echoing to stdout only writes to the log, so `steps.prep.outputs.version` stays empty downstream even though the step succeeded.',
    docId: 'workflow-commands',
  },
  {
    id: 'gh200-d1-q20',
    cert: 'gh200',
    domainId: 'gh200-d1',
    subSkillId: 'd1-jobs-steps',
    kind: 'order',
    stem: 'Put one workflow run in execution order, from trigger to report.',
    items: [
      'A developer pushes a commit to the repository',
      'GitHub matches the event against the workflow’s `on` triggers',
      'A runner is allocated for each job in the workflow',
      'The job’s steps run in their listed order',
      'The outcome lands on the Actions tab and any status badge updates',
    ],
    explanation:
      'An event fires, the trigger filters decide whether the workflow starts, jobs receive runners, steps run top to bottom inside each job, and only then do the run history and badges reflect the result. Every troubleshooting session starts by locating a run inside that sequence.',
    docId: 'workflow-syntax',
  },
];
