import type { Question } from '../types';

/**
 * GH-200 domain 4 practice bank — Manage GitHub Actions for the enterprise
 * (20 questions). Governing reusable components, organizational use
 * policies, GitHub-hosted versus self-hosted runners, networking and IP
 * allow lists, runner groups, preinstalled software, and scoping secrets
 * and variables. Mix: 13 single, 3 multi, 4 coding items (a vars-vs-secrets
 * fill-in, two spot-the-bugs, and a runner onboarding ordering).
 */
export const questions: Question[] = [
  {
    id: 'gh200-d4-q01',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-runner-choice',
    kind: 'single',
    stem: 'Builds need a GPU pool, a route into the private network, and full control of the base image. Which runner model fits?',
    options: [
      'GitHub-hosted runners with a larger size',
      'Self-hosted runners on your own machines',
      'GitHub-hosted runners with `runs-on: gpu`',
      'Service containers with extra options',
    ],
    answerIndex: 1,
    explanation:
      'Custom hardware, network position, and OS control are the three classic reasons to self-host: your machines, registered with GitHub, targeted by label. GitHub-hosted runners offer managed convenience and bigger sizes, never your GPUs or your subnet.',
    docId: 'self-hosted-runners',
  },
  {
    id: 'gh200-d4-q02',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-runner-choice',
    kind: 'single',
    stem: 'A team has no hardware, no special network needs, and wants zero maintenance of build machines. What is the sensible default?',
    options: [
      'Self-hosted runners in autoscaling containers',
      'GitHub-hosted runners — patched and managed by GitHub',
      'A single oversized self-hosted VM under a desk',
      'Running workflows locally with the `act` tool',
    ],
    answerIndex: 1,
    explanation:
      'GitHub-hosted runners arrive maintained: images are updated, software is preinstalled, and each job gets a clean machine. Self-hosting buys control at the price of operating the fleet — a price this team has no reason to pay.',
    docId: 'github-hosted-runners',
  },
  {
    id: 'gh200-d4-q03',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-runner-groups',
    kind: 'single',
    stem: 'An organization wants its payment-team runners usable only by payment-team repositories. Which mechanism does that?',
    options: [
      'Runner labels named after the repositories',
      'A runner group with access restricted to selected repositories',
      'A separate GitHub organization',
      'An IP allow list on the runners',
    ],
    answerIndex: 1,
    explanation:
      'Runner groups are the policy boundary: create a group, register the runners into it, and scope which repositories — or teams — may use it. Labels route jobs; groups decide who is allowed to route jobs there at all.',
    docId: 'runner-groups',
  },
  {
    id: 'gh200-d4-q04',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-org-policies',
    kind: 'single',
    stem: 'An organization must permit only `actions/*` and its own internal actions. Where is that configured?',
    options: [
      'In each workflow’s `permissions:` block',
      'In organization Actions settings, as an allow list of actions and reusable workflows',
      'In the enterprise billing page',
      'In each repository’s branch protection rules',
    ],
    answerIndex: 1,
    explanation:
      'Organization Actions settings control what may run: allow all, allow local only, or allow a specified list of actions and reusable workflows — patterns like `actions/*` included. The `permissions:` block scopes tokens, which is a different axis of control entirely.',
    docId: 'org-actions-policy',
  },
  {
    id: 'gh200-d4-q05',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-org-policies',
    kind: 'single',
    stem: 'Workflows from first-time outside contributors keep running before anyone reviews them. Which org setting addresses exactly this?',
    options: [
      'Requiring approval for workflows from first-time contributors',
      'Disabling Actions on all public repositories',
      'Setting default workflow permissions to read-only',
      'Requiring signed commits',
    ],
    answerIndex: 0,
    explanation:
      'The approval setting gates workflow runs from new external contributors until a maintainer with write access approves them. Read-only tokens limit blast radius but do not withhold execution, and disabling Actions forgoes the project’s automation outright.',
    docId: 'org-actions-policy',
  },
  {
    id: 'gh200-d4-q06',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-networking',
    kind: 'single',
    stem: 'What does an enterprise IP allow list actually restrict?',
    options: [
      'Which IP addresses GitHub-hosted runners may reach',
      'Which IP addresses can access the enterprise over supported interfaces, like the web UI, API, and git',
      'Which runners may register with the organization',
      'Which regions workflows may deploy to',
    ],
    answerIndex: 1,
    explanation:
      'An IP allow list locks the enterprise’s front door — web, API, and git access from approved addresses only. It governs who can talk to GitHub, not what the runners reach outbound; that egress side lives in your own network design.',
    docId: 'ip-allow-lists',
  },
  {
    id: 'gh200-d4-q07',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-networking',
    kind: 'single',
    stem: 'Self-hosted runners sit in a subnet that must reach GitHub over HTTPS, and GitHub’s responses must survive the allow list. What is the documented mechanism for that pairing?',
    options: [
      'Open the allow list to the whole internet permanently',
      'Add the runner egress addresses to the allow list, using the meta API’s CIDR list where the product supports it',
      'Route runner traffic through a third-party proxy GitHub whitelists',
      'Disable the allow list whenever jobs are queued',
    ],
    answerIndex: 1,
    explanation:
      'Runners need bidirectional reachability, so the documented path is allow-listing the addresses runners use — the meta API publishes GitHub’s ranges for exactly this kind of configuration. The alternatives are either security theatre or a permanent hole.',
    docId: 'ip-allow-lists',
  },
  {
    id: 'gh200-d4-q08',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-preinstalled',
    kind: 'single',
    stem: 'A job assumes the AWS CLI is present on `ubuntu-latest` and it is. Where would you check what else ships on that image?',
    options: [
      'The runner image repository’s installed-software tables',
      'The workflow syntax reference',
      'The organization’s runner groups page',
      'The GitHub changelog only',
    ],
    answerIndex: 0,
    explanation:
      'Each GitHub-hosted image publishes its preinstalled software in the runner-images repository — the canonical inventory before you add an install step. Trusting the image blindly works until the day the tool you assumed moves.',
    docId: 'runner-images',
  },
  {
    id: 'gh200-d4-q09',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-preinstalled',
    kind: 'single',
    stem: 'A pipeline needs Node 22, which is not the image’s default. What is the dependable approach?',
    options: [
      'Assume the image updates soon and pin nothing',
      'Set it up explicitly in the job with the setup action, versioned',
      'Bake a custom Docker image per workflow',
      'Ask developers to install Node manually before pushing',
    ],
    answerIndex: 1,
    explanation:
      'Explicit setup steps — like `actions/setup-node` with the exact version — make the toolchain part of the workflow’s own definition instead of an accident of the image. Preinstalled software is a convenience, never a contract.',
    docId: 'github-hosted-runners',
  },
  {
    id: 'gh200-d4-q10',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-secrets-variables',
    kind: 'single',
    stem: 'A secret named `PROD_KEY` exists at organization, repository, and environment level, and the job references that environment. Which value does `${{ secrets.PROD_KEY }}` read?',
    options: [
      'The organization-level value, as the broadest scope',
      'The environment-level value, as the closest scope',
      'All three concatenated',
      'The job fails for a name conflict',
    ],
    answerIndex: 1,
    explanation:
      'When one name exists at several levels, the closest wins: environment over repository over organization. Shadowing is deliberate — broad defaults with narrow overrides, and no failure, ever, for reusing a name across scopes.',
    docId: 'use-secrets',
  },
  {
    id: 'gh200-d4-q11',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-secrets-variables',
    kind: 'single',
    stem: 'Where should a deployment domain like `app.example.com` live, given it is configuration rather than a credential?',
    options: [
      'In a secret, to keep it private',
      'In a configuration variable, read through the `vars` context',
      'Hard-coded in every workflow that needs it',
      'In an artifact downloaded at run time',
    ],
    answerIndex: 1,
    explanation:
      'Secrets are for values that must stay hidden; anything else belongs in variables, read with `${{ vars.NAME }}` and changeable without touching YAML. Hard-coded values spread silently and demand a pull request to rotate.',
    docId: 'use-variables',
  },
  {
    id: 'gh200-d4-q12',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-govern-components',
    kind: 'single',
    stem: 'Thirty repositories should consume one centrally maintained, versioned CI workflow owned by the platform team. Which governance arrangement fits?',
    options: [
      'A reusable workflow in a central repository, allowed by organization policy and called with `uses:`',
      'A composite action copied into each repository’s `.github/`',
      'One giant workflow dispatched manually per repository',
      'A wiki page describing the steps each team should reimplement',
    ],
    answerIndex: 0,
    explanation:
      'A reusable workflow gives the platform team one file, one version, and one place to fix things: callers pin it with `uses: owner/repo/path@ref`, and the organization’s allow list governs who may call what. Copies and wikis drift; references do not.',
    docId: 'reuse-workflows',
  },
  {
    id: 'gh200-d4-q13',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-runner-choice',
    kind: 'single',
    stem: 'A workflow says `runs-on: [self-hosted, linux, gpu]`. What does that label list mean?',
    options: [
      'Run the job three times, once per label',
      'The job may run on any runner that has all of those labels',
      'The job runs on a GitHub-hosted runner in the gpu region',
      'The labels are documentation only; any runner may pick the job up',
    ],
    answerIndex: 1,
    explanation:
      'A self-hosted job lands on a runner whose labels include every label in `runs-on` — `self-hosted` plus your own taxonomy. Label sets are how one fleet serves many teams without queues colliding, and the match is conjunctive.',
    docId: 'self-hosted-runners',
  },
  {
    id: 'gh200-d4-q14',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-org-policies',
    kind: 'multi',
    stem: 'Which organizational Actions policies are real? Choose all that apply.',
    options: [
      'Restricting which actions may run, via an allow list',
      'Allow lists may reference actions only by exact commit SHA',
      'Requiring approval before workflows from new contributors run',
      'Organization policy overrides an enterprise-level allow list',
      'Disabling Actions for selected repositories in the organization',
    ],
    answerIndexes: [0, 2, 4],
    explanation:
      'Org settings can allow-list by pattern or SHA, gate first-time contributors, and switch Actions off per repository — but the allow list accepts friendly refs, not SHAs only, and an enterprise policy is the ceiling an organization cannot exceed.',
    docId: 'org-actions-policy',
  },
  {
    id: 'gh200-d4-q15',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-runner-choice',
    kind: 'multi',
    stem: 'Which statements about runner models are true? Choose all that apply.',
    options: [
      'GitHub-hosted runners are maintained, patched, and provided fresh per job by GitHub',
      'Self-hosted runners suit custom hardware, private networks, and OS control',
      'Self-hosted runners are recommended for public repositories',
      'Runner groups scope which repositories may use a set of self-hosted runners',
      'GitHub-hosted runners can join your VPN automatically',
    ],
    answerIndexes: [0, 1, 3],
    explanation:
      'Managed versus owned is the whole trade: GitHub hosts and refreshes theirs; yours bring control and responsibility. Public repositories are the documented anti-case for self-hosting, and no hosted runner ever joins your private network.',
    docId: 'self-hosted-runners',
  },
  {
    id: 'gh200-d4-q16',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-secrets-variables',
    kind: 'multi',
    stem: 'Which statements about scoping secrets and variables are true? Choose all that apply.',
    options: [
      'Both exist at organization, repository, and environment level',
      'Environment-scoped values reach only jobs that reference that environment',
      'Organization secrets are automatically available to every repository in the organization',
      'Variables are the right home for non-sensitive configuration like image names',
      'A secret’s value can be read back later through the REST API',
    ],
    answerIndexes: [0, 1, 3],
    explanation:
      'The three scopes apply to secrets and variables alike, with the closest scope winning. But organization-level values must be explicitly granted to repositories, and secrets are write-only — you can list names, never read values back.',
    docId: 'use-secrets',
  },
  {
    id: 'gh200-d4-q17',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-secrets-variables',
    kind: 'fill',
    stem: 'Route each value to its context: the public domain through variables, the credential through secrets.',
    codeTemplate:
      'name: Configured build\non: push\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: ./build.sh --domain ${{ ___.DEPLOY_DOMAIN }}\n        env:\n          TOKEN: ${{ ___.ORG_TOKEN }}\n',
    blanks: [
      { answer: 'vars', alternatives: [] },
      { answer: 'secrets', alternatives: [] },
    ],
    explanation:
      'Two contexts, two jobs: `vars` serves configuration stored as variables, `secrets` serves credentials stored masked. Routing each value to the right context is the daily habit this domain wants you to have.',
    docId: 'use-variables',
  },
  {
    id: 'gh200-d4-q18',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-runner-choice',
    kind: 'bug',
    stem: 'The installer step is a PowerShell script, but the job never gets past it on the runner shown. Click the misconfigured line.',
    codeLines: [
      'name: Windows installer',
      'on: push',
      'jobs:',
      '  package:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - run: ./build-windows-msi.ps1',
    ],
    buggyLineIndex: 4,
    explanation:
      'A PowerShell script needs a Windows runner: line 5 should say `runs-on: windows-latest`. The job as written hands a `.ps1` to a Linux machine — the script is fine, the venue is wrong.',
    docId: 'github-hosted-runners',
  },
  {
    id: 'gh200-d4-q19',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-org-policies',
    kind: 'bug',
    stem: 'Organization policy allows only `actions/*` and internal actions. This workflow fails with `action not allowed`. Click the line that violates the policy.',
    codeLines: [
      'name: CI',
      'on: push',
      'jobs:',
      '  build:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: some-rand0m-user/super-linter@v3',
      '      - run: npm test',
    ],
    buggyLineIndex: 7,
    explanation:
      'The checkout step matches the `actions/*` pattern; the third-party linter does not, and the allow list rejects it at run time. The organization lists exactly what may execute — reading a `uses:` line against that list is the review habit.',
    docId: 'org-actions-policy',
  },
  {
    id: 'gh200-d4-q20',
    cert: 'gh200',
    domainId: 'gh200-d4',
    subSkillId: 'd4-runner-groups',
    kind: 'order',
    stem: 'Put the onboarding of a new self-hosted runner for a team in order.',
    items: [
      'Create a runner group in organization settings and scope which repositories may use it',
      'Register the runner: download and configure it on the machine, then start the service',
      'Confirm labels so workflows can target the runner precisely',
      'Verify the runner appears Idle in the organization’s runner list',
      'Run a workflow whose `runs-on:` targets those labels and watch it land',
    ],
    explanation:
      'Policy first, machine second: the group decides who may use the runner before it exists, registration puts it on the network, labels make it addressable, the Idle status proves the connection, and only then does a real job land on it.',
    docId: 'runner-groups',
  },
];
