import type { Question } from '../types';

/**
 * GH-200 domain 2 practice bank — Consume and troubleshoot workflows (20
 * questions). Reading triggers and effects, diagnosing failed runs from
 * logs, expanding anchors and matrix axes, rerunning failed jobs, locating
 * logs and artifacts, starter and org templates, reusable vs composite,
 * and disabling versus deleting. Mix: 13 single, 3 multi, 4 coding items
 * (an anchor fill-in, two log-diagnosis spot-the-bugs, and a rerun
 * ordering).
 */
export const questions: Question[] = [
  {
    id: 'gh200-d2-q01',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-read-config',
    kind: 'single',
    stem: 'A teammate hands you `on: push: branches: [main]` and asks when the workflow runs. What is the honest answer?',
    options: [
      'On any push to any branch in the repository',
      'On pushes that update `main`, including merges and fast-forwards that land on it',
      'Only on direct pushes by administrators',
      'On pushes to `main` and on pull requests targeting `main`',
    ],
    answerIndex: 1,
    explanation:
      'The `branches` filter matches pushes whose head ref is `main` — however the commits got there. A pull request merge that updates `main` arrives as a push event, while the pull request itself is a different trigger entirely.',
    docId: 'workflow-events',
  },
  {
    id: 'gh200-d2-q02',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-read-config',
    kind: 'single',
    stem: 'A nightly run failed at 03:00 and you were not watching. Where do you look first for the shortest path to the error?',
    options: [
      'The workflow file in `.github/workflows/`',
      'The failed run on the Actions tab — its annotations point at the failing steps',
      'The repository’s audit log',
      'The emails GitHub sends for every green run',
    ],
    answerIndex: 1,
    explanation:
      'Run history is the entry point: open the run, and annotations summarize the errors GitHub extracted, each linking straight to the failing step’s expanded log. The workflow file matters after you know what broke, and green runs send no mail.',
    docId: 'view-run-history',
  },
  {
    id: 'gh200-d2-q03',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-diagnose-failures',
    kind: 'single',
    stem: 'A workflow triggers fine but the first `run:` step fails immediately with `No such file or directory` when touching repository files. What is the classic cause?',
    options: [
      'The runner is out of disk space',
      'The `actions/checkout` step is missing, so the repository was never copied onto the runner',
      'The workflow YAML is indented incorrectly',
      'The `GITHUB_TOKEN` lacks write permissions',
    ],
    answerIndex: 1,
    explanation:
      'Jobs start on an empty workspace: until `actions/checkout` copies the repository onto the runner, no project files exist there. A missing checkout is one of the most common first-step failures, and permissions have nothing to do with it.',
    docId: 'troubleshoot-workflows',
  },
  {
    id: 'gh200-d2-q04',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-diagnose-failures',
    kind: 'single',
    stem: 'A matrix run failed in 3 of 10 combinations. What is the cheapest path to a clean, fully green run?',
    options: [
      'Re-run all jobs and hope the flaky ones pass this time',
      'Re-run failed jobs — only the 3 failed combinations execute again',
      'Edit the matrix to drop the failing combinations',
      'Delete the run and push a new commit',
    ],
    answerIndex: 1,
    explanation:
      'Re-run failed jobs recreates exactly the failed combinations, keeping the passed ones green in place. Re-running everything burns the minutes you already paid for, and deleting a run erases the evidence you were about to learn from.',
    docId: 'view-run-history',
  },
  {
    id: 'gh200-d2-q05',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-expand-config',
    kind: 'single',
    stem: 'The Actions tab shows a job named `verify (18, ubuntu-latest)`. What is that name telling you?',
    options: [
      'The workflow file name and its author',
      'The values from the matrix combination this particular job ran with',
      'The runner’s host name and its CPU count',
      'The job’s retry count and queue position',
    ],
    answerIndex: 1,
    explanation:
      'Matrix jobs are displayed as the job name plus the axis values in parentheses, so `verify (18, ubuntu-latest)` is the `verify` job for Node 18 on Ubuntu — reading the axis off the display is half of expanding a matrix by eye.',
    docId: 'view-run-history',
  },
  {
    id: 'gh200-d2-q06',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-logs-artifacts',
    kind: 'single',
    stem: 'An auditor needs the raw logs of a specific run and wants to fetch them programmatically. Which surface serves them?',
    options: [
      'The Actions REST API, with the run id under `/repos/{owner}/{repo}/actions/runs/{run_id}/logs`',
      'The git protocol, by cloning the `.github/logs` branch',
      'The GraphQL API only — REST has no Actions endpoints',
      'There is no API; logs are downloadable from the browser alone',
    ],
    answerIndex: 0,
    explanation:
      'The Actions REST API exposes run logs at the runs endpoint, returning an archive you can script against for audits and retention. REST covers Actions thoroughly — and no repository branch ever stores run logs.',
    docId: 'rest-actions',
  },
  {
    id: 'gh200-d2-q07',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-logs-artifacts',
    kind: 'single',
    stem: 'A build publishes a test report as an artifact. Three weeks later a developer cannot download it. Most likely reason?',
    options: [
      'Artifacts are encrypted per runner and unreadable elsewhere',
      'The artifact passed its retention period and was deleted',
      'Artifacts can only be downloaded while the run is in progress',
      'Artifacts require the `packages: write` permission',
    ],
    answerIndex: 1,
    explanation:
      'Artifacts live only as long as the retention setting allows — then they are garbage-collected, and the run page shows nothing to download. Grab what you need within the window, or raise retention if the reports must outlive it.',
    docId: 'store-artifacts',
  },
  {
    id: 'gh200-d2-q08',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-templates',
    kind: 'single',
    stem: 'Where do starter workflows surface when a developer clicks "New workflow" from a repository’s Actions tab?',
    options: [
      'From GitHub’s curated set plus any templates your organization publishes',
      'Only from GitHub’s curated set — organizations cannot add their own',
      'From every workflow file in every public repository you follow',
      'From the repository’s `docs/` directory',
    ],
    answerIndex: 0,
    explanation:
      'The New workflow page offers GitHub’s starter set alongside templates your organization publishes, so company-standard pipelines sit next to the defaults. Choosing one copies the YAML into your `.github/workflows/` to edit freely.',
    docId: 'workflow-templates',
  },
  {
    id: 'gh200-d2-q09',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-templates',
    kind: 'single',
    stem: 'An organization wants its 40 repositories to start from the same hardened CI template. Where do the template files live?',
    options: [
      'In each repository, synced by hand',
      'In the organization’s `.github` repository, under `workflow-templates/`',
      'In a special branch of every repository named `templates`',
      'In the organization’s profile README',
    ],
    answerIndex: 1,
    explanation:
      'Workflow templates for an organization live in its `.github` repository inside `workflow-templates/`, each with a metadata file that controls how it appears in the New workflow list. Repositories then start from one maintained source instead of forty copies.',
    docId: 'workflow-templates',
  },
  {
    id: 'gh200-d2-q10',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-reusable-vs-composite',
    kind: 'single',
    stem: 'A team wants to call the same set of steps from many workflows in one repository, running inside the calling job with no extra runner. Which construct fits?',
    options: [
      'A reusable workflow',
      'A composite action',
      'A starter workflow copied into each repository',
      'A workflow template with YAML anchors',
    ],
    answerIndex: 1,
    explanation:
      'A composite action bundles steps that execute inside the caller’s job on the caller’s runner — no new job, no new machine. A reusable workflow brings its own job and runner, which is exactly the overhead this team wants to avoid.',
    docId: 'create-composite-action',
  },
  {
    id: 'gh200-d2-q11',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-reusable-vs-composite',
    kind: 'single',
    stem: 'Twelve repositories must run an identical, centrally versioned deploy job — one fix should reach all of them. Which construct fits?',
    options: [
      'A composite action referenced by path in each repository',
      'A reusable workflow, called with `uses:` and pinned to a ref',
      'A YAML anchor shared through a symlink',
      'Copying the deploy job into each repository’s workflow',
    ],
    answerIndex: 1,
    explanation:
      'A reusable workflow is called with `uses:` — including from another repository, pinned to a tag or SHA — so one central file serves many callers and one merge propagates everywhere. Anchors cannot cross files, and copies drift.',
    docId: 'reuse-workflows',
  },
  {
    id: 'gh200-d2-q12',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-disable-vs-delete',
    kind: 'single',
    stem: 'A nightly job is too noisy for the next two weeks, but the team wants its configuration intact for later. What is the right move?',
    options: [
      'Delete the workflow file from the default branch',
      'Disable the workflow from the Actions tab',
      'Comment out the whole YAML file',
      'Rename `.github/workflows/` to `.github/workflows-off/`',
    ],
    answerIndex: 1,
    explanation:
      'Disabling a workflow stops its triggers immediately while keeping the file, its runs, and one click to re-enable. Deleting the file or mangling its path loses that round trip and buries the intent in git history instead.',
    docId: 'disable-workflows',
  },
  {
    id: 'gh200-d2-q13',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-disable-vs-delete',
    kind: 'single',
    stem: 'What is the practical difference between disabling a workflow and deleting its file?',
    options: [
      'Deleting erases the workflow’s past runs along with the file',
      'Disabling stops the triggers while keeping the file — one click re-enables it later',
      'They are the same action under two names',
      'Disabling also removes the workflow from the Actions tab',
    ],
    answerIndex: 1,
    explanation:
      'Disabling is the pause button: the documented way to stop a workflow without deleting the file from the repository, and Enable brings it straight back. Deleting is the permanent route — you would restore it from git history, not from a button.',
    docId: 'disable-workflows',
  },
  {
    id: 'gh200-d2-q14',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-diagnose-failures',
    kind: 'multi',
    stem: 'Which statements about diagnosing failed runs are true? Choose all that apply.',
    options: [
      'Annotations on the run page summarize detected errors and link into the logs',
      'Re-run failed jobs repeats only the combinations that failed',
      'Runner debug logs can be enabled for a re-run when the normal logs are not enough',
      'Deleting the workflow file deletes its run history',
      'A failed job always means the workflow YAML itself is invalid',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Annotations, selective re-runs, and debug logging are the diagnosis loop. Run history outlives the workflow file, and plenty of failures come from the code or environment on a perfectly valid workflow.',
    docId: 'view-run-history',
  },
  {
    id: 'gh200-d2-q15',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-reusable-vs-composite',
    kind: 'multi',
    stem: 'Which statements correctly separate reusable workflows from composite actions? Choose all that apply.',
    options: [
      'A reusable workflow runs as its own job, on its own runner',
      'A composite action’s steps execute inside the calling job',
      'Both can be versioned and called with `uses:` pinned to a ref',
      'A composite action declares its own `runs-on:` in `action.yml`',
      'Calling a reusable workflow removes the need for `needs:` between jobs',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'The split is the unit: reusable workflows contribute jobs with their own runners, composite actions contribute steps inside yours. Both are referenced with `uses:` and pinned like any action; neither knows about your dependency graph.',
    docId: 'reuse-workflows',
  },
  {
    id: 'gh200-d2-q16',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-templates',
    kind: 'multi',
    stem: 'Which statements about starter and organization workflow templates are true? Choose all that apply.',
    options: [
      'Choosing a starter workflow copies its YAML into your repository to edit',
      'An organization publishes its own templates from its `.github` repository',
      'Template metadata files control the category and description shown in the picker',
      'Templates update your workflow automatically whenever the template changes',
      'Only GitHub can author templates that appear in the New workflow list',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'A template is a starting point: the picker (GitHub’s starters plus your organization’s) copies YAML into `.github/workflows/`, after which it is yours. Nothing flows back later — when the template improves, you re-copy deliberately.',
    docId: 'workflow-templates',
  },
  {
    id: 'gh200-d2-q17',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-expand-config',
    kind: 'fill',
    stem: 'Two jobs share one step list: define an anchor named `shared` on the first, then reuse it with an alias.',
    codeTemplate:
      'name: DRY steps\non: push\njobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps: &___\n      - uses: actions/checkout@v4\n      - run: npm run lint\n  audit:\n    runs-on: ubuntu-latest\n    steps: *___\n',
    blanks: [
      { answer: 'shared', alternatives: [] },
      { answer: 'shared', alternatives: [] },
    ],
    explanation:
      'The anchor `&shared` tags the step list where it is first written; the alias `*shared` expands that same list for the second job. Anchor and alias must agree on the name, and both must live in this one file — that is the whole scope of YAML reuse.',
    docId: 'reuse-config',
  },
  {
    id: 'gh200-d2-q18',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-diagnose-failures',
    kind: 'bug',
    stem: "The test step fails with `Error: Cannot find module 'jest'` — a devDependency. The log points at step 3, but the cause sits earlier. Click the line at fault.",
    codeLines: [
      'name: PR checks',
      'on: pull_request',
      'jobs:',
      '  verify:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - run: npm install --production',
      '      - run: npm test',
    ],
    buggyLineIndex: 7,
    explanation:
      'The error surfaces in step 3, but step 2 planted it: `npm install --production` skips devDependencies, so the test tooling never installed. `npm ci` installs everything the lockfile declares — the read-the-whole-log lesson is that the failing step is not always the guilty one.',
    docId: 'troubleshoot-workflows',
  },
  {
    id: 'gh200-d2-q19',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-diagnose-failures',
    kind: 'bug',
    stem: 'The job reports green and ships an image — but the image was built from stale code, because the build actually failed and nothing stopped the pipeline. Click the line that let the failure through.',
    codeLines: [
      'name: Build and ship',
      'on: push',
      'jobs:',
      '  build:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - run: make build',
      '        continue-on-error: true',
      '      - run: docker push myapp:latest',
    ],
    buggyLineIndex: 8,
    explanation:
      '`continue-on-error: true` converts the build’s failure into a warning, so the job marches on and pushes whatever the previous build left behind. Reserve it for steps whose failure genuinely should not gate the pipeline — a build step is the opposite of that.',
    docId: 'troubleshoot-workflows',
  },
  {
    id: 'gh200-d2-q20',
    cert: 'gh200',
    domainId: 'gh200-d2',
    subSkillId: 'd2-expand-config',
    kind: 'order',
    stem: 'A matrix run failed overnight in a few combinations. Put the recovery in order.',
    items: [
      'Open the failed run on the Actions tab',
      'Expand the matrix to see which job combinations failed',
      'Choose Re-run failed jobs',
      'Watch the re-run recreate only the failed combinations',
      'If the re-run fails again, read the failed jobs’ logs for the real cause',
    ],
    explanation:
      'Scope, re-run, then diagnose what persists: see which combinations failed, re-run exactly those, and only dig into logs when the failure survives a clean retry. Flakes die at step 3; real bugs introduce themselves at step 5.',
    docId: 'view-run-history',
  },
];
