import type { Question } from '../types';

/**
 * GH-200 domain 3 practice bank — Author and maintain actions (20
 * questions). Action types and immutability, metadata and structure,
 * workflow commands from inside actions, distribution public and private,
 * versioning and release strategy. Mix: 13 single, 3 multi, 4 coding items
 * (two action.yml fill-ins, a missing-shell spot-the-bug, and a release
 * ordering).
 */
export const questions: Question[] = [
  {
    id: 'gh200-d3-q01',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-action-types',
    kind: 'single',
    stem: 'Which action type packages everything — toolchain, dependencies, scripts — inside an image you fully control?',
    options: [
      'A composite action',
      'A JavaScript action',
      'A Docker action',
      'A starter workflow',
    ],
    answerIndex: 2,
    explanation:
      'A Docker action builds its environment from a Dockerfile you author, so the action runs inside exactly the image you shipped. The price is a Linux-only runtime and slower cold starts, which is why the lighter types come first when they suffice.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q02',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-action-types',
    kind: 'single',
    stem: 'A team wants to bundle five existing steps — two `run:` scripts and three `uses:` of other actions — into one reusable unit that runs inside the caller’s job. Which type fits?',
    options: [
      'A composite action',
      'A Docker action',
      'A reusable workflow',
      'An organization workflow template',
    ],
    answerIndex: 0,
    explanation:
      'Composite actions exist precisely for this: a list of steps, including `uses:` of other actions, executed inside the caller’s job with no runtime of their own. Reusable workflows would spin up their own job and runner instead.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q03',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-action-types',
    kind: 'single',
    stem: 'A JavaScript action’s `action.yml` says `using: node20`. What does that declare?',
    options: [
      'The Node version the runner must install before the action runs',
      'The runtime GitHub uses to execute the action’s compiled entrypoint',
      'A Docker image tagged node20',
      'The minimum runner generation the action supports',
    ],
    answerIndex: 1,
    explanation:
      '`using:` names the runtime the runner executes your `main` file with — Node 20 in this case, already available on the runner rather than installed by it. Docker actions declare `using: docker` plus an `image` instead.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q04',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-structure-metadata',
    kind: 'single',
    stem: 'What must exist at the root of a repository for GitHub to treat a directory as an action?',
    options: [
      'A `Dockerfile`',
      'An `action.yml` (or `action.yaml`) metadata file',
      'A `main.workflow` file',
      'A `package.json` with an `action` field',
    ],
    answerIndex: 1,
    explanation:
      'The metadata file `action.yml` — or `action.yaml`, either name works — is the contract that makes an action an action: it declares the type, inputs, outputs, and entrypoint. Everything else in the repository serves what that file describes.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q05',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-structure-metadata',
    kind: 'single',
    stem: 'An input is declared `required: true` with no default. What happens when a caller omits it?',
    options: [
      'The workflow fails with a validation error before the job starts',
      'The action receives an empty string and decides for itself',
      'GitHub prompts the caller interactively',
      'The input is silently dropped from the `inputs` context',
    ],
    answerIndex: 0,
    explanation:
      'Required means required: the workflow referencing the action fails validation up front, telling you which input is missing, rather than letting the action run half-configured. Optional inputs are the ones that fall back to their `default`.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q06',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-commands-in-actions',
    kind: 'single',
    stem: 'From JavaScript action code, what is the toolkit equivalent of emitting a `key=value` output line?',
    options: [
      '`console.log` with a `::output` prefix',
      "`core.setOutput('key', value)`",
      '`process.env.OUTPUT_KEY = value`',
      'Writing straight to stdout — the runner parses everything',
    ],
    answerIndex: 1,
    explanation:
      'The actions toolkit wraps every workflow command: `core.setOutput` emits the properly escaped `::set-output` machinery for you, just as `core.debug`, `core.warning`, and `core.exportVariable` wrap their commands. Hand-rolled prefixes only look like the real thing.',
    docId: 'workflow-commands',
  },
  {
    id: 'gh200-d3-q07',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-commands-in-actions',
    kind: 'single',
    stem: 'An action logs diagnostic detail through debug commands, but users report seeing nothing. Why?',
    options: [
      'Debug output requires debug logging to be enabled for the run',
      'Debug commands only work in Docker actions',
      'The runner strips debug lines from composite actions',
      'Debug output is reserved for GitHub’s own actions',
    ],
    answerIndex: 0,
    explanation:
      'Debug lines are emitted always but displayed only when the run re-runs with debug logging enabled (or the `ACTIONS_STEP_DEBUG` secret is set). That is the design: verbose diagnostics stay out of the way until someone asks for them.',
    docId: 'workflow-commands',
  },
  {
    id: 'gh200-d3-q08',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-distribution',
    kind: 'single',
    stem: 'An enterprise wants internal actions shared company-wide but invisible to the public. What is the supported path?',
    options: [
      'Publish to the Marketplace with hidden visibility',
      'Keep the actions in internal repositories and allow them via enterprise sharing',
      'Ship them as encrypted archives downloaded by each workflow',
      'Fork them into every repository that needs them',
    ],
    answerIndex: 1,
    explanation:
      'Actions live in repositories, and an enterprise can share the ones in its internal repositories with all its organizations — no Marketplace, no public exposure. Workflows then reference them by `owner/repo/path@ref` like any other action.',
    docId: 'share-with-enterprise',
  },
  {
    id: 'gh200-d3-q09',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-distribution',
    kind: 'single',
    stem: 'What does listing an action in the GitHub Marketplace give consumers?',
    options: [
      'Automatic security scanning of every release',
      'A discoverable, versioned catalog page with the action’s releases and README',
      'Faster runner allocation for workflows that use it',
      'A guarantee the action is officially maintained by GitHub',
    ],
    answerIndex: 1,
    explanation:
      'Marketplace listing is distribution and discovery: a public page where each release tag is documented and installable by name. It confers no special runtime treatment — and certainly no GitHub endorsement beyond the verified-publisher badges it shows.',
    docId: 'publish-actions',
  },
  {
    id: 'gh200-d3-q10',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-versioning',
    kind: 'single',
    stem: 'A maintainer releases `v2.0.0`, then `v2.1.0` with a fix. Consumers pinned to `@v2` should get the fix automatically. Which release strategy does that?',
    options: [
      'Semver releases with a moving major tag that is re-pointed at each minor release',
      'Only ever publishing full commit SHAs to consumers',
      'Releasing fixes as new major versions',
      'Tagging releases only on a schedule, never on demand',
    ],
    answerIndex: 0,
    explanation:
      'The documented strategy: cut `v2.1.0`, then move the `v2` tag to it, so `@v2` consumers receive the fix on their next run while anyone needing to freeze can still pin `@v2.0.0` or a SHA. Breaking changes are exactly what bumps the major.',
    docId: 'release-actions',
  },
  {
    id: 'gh200-d3-q11',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-versioning',
    kind: 'single',
    stem: 'An action’s next release renames an input — a breaking change. What does the maintainer owe consumers?',
    options: [
      'A patch release; consumers will adapt',
      'A new major version tag, with the old major kept working for existing users',
      'Nothing — inputs are not part of the contract',
      'A force-push of the existing tag to the new code',
    ],
    answerIndex: 1,
    explanation:
      'Renaming an input breaks every workflow that passes the old name, so it lands as a new major tag (`v3`) while `v2` keeps serving the old contract. Force-moving an existing tag silently breaks the very consumers who pinned for stability.',
    docId: 'release-actions',
  },
  {
    id: 'gh200-d3-q12',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-troubleshoot-actions',
    kind: 'single',
    stem: 'A workflow in another repository fails with `unable to resolve action … repository not found` for your brand-new action. The action works in its own repo. Most likely cause?',
    options: [
      'The action’s `action.yml` is malformed',
      'The action repository is private and not shared with the caller’s scope',
      'The caller’s runner lacks internet access',
      'The action must be published to the Marketplace before any external use',
    ],
    answerIndex: 1,
    explanation:
      'A private action resolves only where it is shared — inside its own repository, the enterprises or organizations it was shared with, or nowhere else. Marketplace publishing is one distribution route, never a prerequisite for sharing code that is properly visible.',
    docId: 'share-with-enterprise',
  },
  {
    id: 'gh200-d3-q13',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-troubleshoot-actions',
    kind: 'single',
    stem: 'A Docker action runs fine in CI on `ubuntu-latest` but fails on `macos-latest` runners. Why?',
    options: [
      'Docker actions require a Linux runner — they do not run on macOS or Windows runners',
      'The image needs rebuilding for ARM',
      'macOS runners block all container jobs by policy',
      'The `action.yml` is missing a macOS entrypoint',
    ],
    answerIndex: 0,
    explanation:
      'Docker actions execute in Linux containers, and GitHub’s macOS runners do not run them — the constraint is documented with the metadata itself. Composite or JavaScript actions are the portable answer when the pipeline must build on every OS.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q14',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-action-types',
    kind: 'multi',
    stem: 'Which statements about the three action types are true? Choose all that apply.',
    options: [
      'A JavaScript action runs code directly on the runner under its declared Node runtime',
      'A Docker action executes inside a container built from your Dockerfile',
      'A composite action bundles steps, including `uses:` of other actions, with no runtime of its own',
      'Docker actions run natively on Windows and macOS runners',
      'Only composite actions can be published to the Marketplace',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'The three types are one ladder of isolation: JavaScript runs on the runner, Docker brings its own container (Linux runners only), composite brings nothing — just steps folded into the caller. All three may be listed on the Marketplace.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q15',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-structure-metadata',
    kind: 'multi',
    stem: 'Which statements about `action.yml` are true? Choose all that apply.',
    options: [
      '`name` and `description` are required metadata',
      'Inputs can declare `required`, `default`, and a description shown to callers',
      'Composite outputs map names to expressions like a step’s output',
      '`runs.using` is optional when a `main` entrypoint is present',
      'The `branding` icon and color are required fields',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'The metadata contract: a required `name` and `description`, documented inputs with defaults, and — for composites — outputs resolved through `value:` expressions. `runs.using` is mandatory whenever there is a `runs` block, while `branding` is pure cosmetics and optional.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q16',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-versioning',
    kind: 'multi',
    stem: 'Which are sound release practices for a published action? Choose all that apply.',
    options: [
      'Tag each release so consumers can reference a stable point',
      'Deleting a published tag silently upgrades consumers to the newest code',
      'Maintain a moving major tag, like `v2`, alongside patch and minor tags',
      'Let consumers pin to a full commit SHA when they need exact reproducibility',
      'Push releases only to the default branch, never as tags',
    ],
    answerIndexes: [0, 2, 3],
    explanation:
      'Tags are the consumer-facing contract: exact releases to pin to, a moving major for automatic fixes, SHAs when reproducibility is non-negotiable. Deleting tags or shipping only to a branch leaves consumers with no stable reference at all.',
    docId: 'release-actions',
  },
  {
    id: 'gh200-d3-q17',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-structure-metadata',
    kind: 'fill',
    stem: 'Complete the composite action’s declaration: the type and the shell each `run:` step must name.',
    codeTemplate:
      'name: Setup Terraform\ndescription: Installs the Terraform CLI\nruns:\n  ___: composite\n  steps:\n    - run: ./install.sh\n      ___: bash\n',
    blanks: [
      { answer: 'using', alternatives: [] },
      { answer: 'shell', alternatives: [] },
    ],
    explanation:
      '`using: composite` declares the type inside `runs`, and every `run:` step in a composite must state its `shell` — there is no default the runner may assume. Get either wrong and the action fails before your script ever executes.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q18',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-structure-metadata',
    kind: 'fill',
    stem: 'Give the input its fallback and point the output at a step’s value.',
    codeTemplate:
      'name: Setup tool\ndescription: Installs the CLI tool\ninputs:\n  version:\n    description: Version to install\n    required: false\n    ___: latest\noutputs:\n  install-path:\n    description: Where the tool was installed\n    value: ${{ ___.install.outputs.path }}\n',
    blanks: [
      { answer: 'default', alternatives: [] },
      { answer: 'steps', alternatives: [] },
    ],
    explanation:
      'An optional input falls back through `default`, and a composite action’s outputs are computed from `value:` expressions — typically `${{ steps.<id>.outputs.<name> }}` reading a step the action itself ran. Both keys are how actions advertise their contract.',
    docId: 'metadata-syntax',
  },
  {
    id: 'gh200-d3-q19',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-troubleshoot-actions',
    kind: 'bug',
    stem: 'The action fails on first use with `Required property "shell" is missing`. Exactly one step is missing its declaration — click it.',
    codeLines: [
      'name: Greet',
      'description: Prints a greeting',
      'runs:',
      '  using: composite',
      '  steps:',
      '    - run: echo "Hello"',
      '    - run: echo "Done"',
      '      shell: bash',
    ],
    buggyLineIndex: 5,
    explanation:
      'In a composite action every `run:` step needs an explicit `shell:` — line 6 has one, line 5 does not, and the failure names the missing property precisely. The fix is one line of `shell: bash`, not a rethink of the action.',
    docId: 'create-composite-action',
  },
  {
    id: 'gh200-d3-q20',
    cert: 'gh200',
    domainId: 'gh200-d3',
    subSkillId: 'd3-versioning',
    kind: 'order',
    stem: 'Put a new action release in order, from code to consumers.',
    items: [
      'Land the change on the action’s default branch',
      'Run the action’s test workflows against that ref',
      'Update `action.yml` if inputs, outputs, or branding changed',
      'Tag the release — the version tag, plus the moving major tag',
      'Publish or update the Marketplace listing pointing at the tag',
    ],
    explanation:
      'Ship in order: merge, test what you merged, reconcile the metadata, then cut tags and point the listing at them. Consumers pin the tags — so the tags are the last thing you touch, after everything they refer to is true.',
    docId: 'release-actions',
  },
];
