import type { Question } from '../types';

/**
 * GH-900 domain 3 practice bank — Collaborate using GitHub (20 questions).
 *
 * Original items covering issues, pull requests, discussions, linking and
 * filtering, notifications, and the gists/wikis/Pages trio. Mix: 13 single,
 * 4 multi, 3 coding.
 */
export const questions: Question[] = [
  {
    id: 'gh900-d3-q01',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-issues-prs-discussions',
    kind: 'single',
    stem: 'A tester finds a crash in the checkout flow. Which GitHub surface should carry the report?',
    options: [
      'An issue — the trackable unit of work for bugs and tasks',
      'A discussion — the place for open-ended conversation',
      'A gist — the place for sharing code snippets',
      'A wiki page — the place for documentation',
    ],
    answerIndex: 0,
    explanation:
      'Issues track work: they carry assignees, labels, milestones, and cross-references, and they close when the fixing pull request merges. Discussions hold ideas; gists and wikis hold content.',
    docId: 'about-issues',
  },
  {
    id: 'gh900-d3-q02',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-issues-prs-discussions',
    kind: 'single',
    stem: 'What is a pull request, in one sentence?',
    options: [
      'A proposal to merge one branch into another, with the diff, review, and discussion attached',
      'A request for somebody to pull your repository',
      'A copy of the repository for independent work',
      'An automated deployment pipeline',
    ],
    answerIndex: 0,
    explanation:
      'A pull request says "here is a branch; I propose merging it, here is exactly what changes, review it" — the conversation, reviews, and checks all hang off that proposal.',
    docId: 'about-pull-requests',
  },
  {
    id: 'gh900-d3-q03',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-issues-prs-discussions',
    kind: 'single',
    stem: 'The team debates "should we drop support for Node 16?" — an open-ended question with no code to merge. Which surface fits?',
    options: [
      'A discussion, built for conversations and community Q&A',
      'A pull request, so the debate happens next to code',
      'An issue with the `question` label',
      'A fork of the repository',
    ],
    answerIndex: 0,
    explanation:
      'Discussions are for open-ended topics — questions, ideas, announcements — organized in categories and marked answered, without the merge-or-close pressure of an issue.',
    docId: 'about-discussions',
  },
  {
    id: 'gh900-d3-q04',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-linking-filtering',
    kind: 'single',
    stem: 'A pull request description ends with `Closes #12`. What happens?',
    options: [
      'Issue #12 automatically closes when the pull request merges into the default branch',
      'Issue #12 closes the moment the pull request is opened',
      'Nothing — `Closes` is decorative text',
      'The pull request merges itself when issue #12 is closed',
    ],
    answerIndex: 0,
    explanation:
      'Closing keywords link the pull request to the issue so the issue shuts automatically on merge — into the default branch specifically. Opening the PR alone leaves the issue open.',
    docId: 'linking-pr-to-issue',
  },
  {
    id: 'gh900-d3-q05',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-linking-filtering',
    kind: 'single',
    stem: '`Closes #12` sits in a pull request that merges into a long-lived feature branch, not `main`. Does issue #12 close?',
    options: [
      'No — the automatic close fires only on merges into the default branch',
      'Yes — any merge closes the linked issue',
      'Yes, but only after a maintainer approves',
      'No — closing keywords never work on branches',
    ],
    answerIndex: 0,
    explanation:
      'The auto-close behavior triggers when the pull request reaches the default branch. Merging elsewhere (like a staging or feature branch) leaves the issue open — the link stays, the close does not fire.',
    docId: 'linking-pr-to-issue',
  },
  {
    id: 'gh900-d3-q06',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-linking-filtering',
    kind: 'single',
    stem: 'Maintainers want every new bug report to arrive with steps to reproduce and environment details. What should they set up?',
    options: [
      'Issue templates in `.github/ISSUE_TEMPLATE/`',
      'A CODEOWNERS file',
      'A protected branch rule',
      'A pull request template',
    ],
    answerIndex: 0,
    explanation:
      'Issue templates present structured forms for common reports — bug, feature, config — so the information arrives complete. Pull request templates shape PR descriptions instead, and the other options are unrelated.',
    docId: 'issue-pr-templates',
  },
  {
    id: 'gh900-d3-q07',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-linking-filtering',
    kind: 'single',
    stem: 'In the issues list, a maintainer types `is:open label:bug assignee:@me`. What appears?',
    options: [
      'Open issues labeled `bug` and assigned to the person searching',
      'All issues that mention the word bug',
      'Closed issues anyone assigned to them',
      'Every pull request in the repository',
    ],
    answerIndex: 0,
    explanation:
      'The issue list doubles as a search engine: qualifiers like `is:open`, `label:`, and `assignee:@me` intersect, so the list shows exactly the open bugs assigned to you.',
    docId: 'filtering-issues',
  },
  {
    id: 'gh900-d3-q08',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-notifications',
    kind: 'single',
    stem: 'Priya left one comment on a stranger’s issue and now gets notified about every reply. Why?',
    options: [
      'Participating in a conversation subscribes her to its thread',
      'She is following the repository author',
      'GitHub notifies everyone in the organization',
      'Commenting assigns the issue to her',
    ],
    answerIndex: 0,
    explanation:
      'You are automatically subscribed to threads you participate in — authoring, commenting, or being @mentioned. Participating is one of the two main notification sources, alongside deliberately watching a repository.',
    docId: 'about-notifications',
  },
  {
    id: 'gh900-d3-q09',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-notifications',
    kind: 'single',
    stem: 'A developer wants to hear about every issue and pull request in a repository, not just threads they join. What should they do?',
    options: [
      'Watch the repository',
      'Star the repository',
      'Fork the repository',
      'Add themselves to CODEOWNERS for `*`',
    ],
    answerIndex: 0,
    explanation:
      'Watching opts into notifications for all conversation in a repository. Starring only bookmarks; forking copies code; a catch-all CODEOWNERS entry is a review-routing hack, not a subscription.',
    docId: 'about-notifications',
  },
  {
    id: 'gh900-d3-q10',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-notifications',
    kind: 'single',
    stem: 'Notifications are flooding in from a repository the developer no longer cares about. What stops them at the source?',
    options: [
      'Unwatch the repository (or set it to ignore)',
      'Delete the account and start again',
      'Close every issue in the repository',
      'Turn off email everywhere and check the site hourly',
    ],
    answerIndex: 0,
    explanation:
      'Notification volume is controlled per repository: unwatch stops the subscription, and ignore silences even @mentions from it. Global notification settings then shape how arriving notifications reach you.',
    docId: 'about-notifications',
  },
  {
    id: 'gh900-d3-q11',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-gists-wikis-pages',
    kind: 'single',
    stem: 'A developer wants to share a 20-line regex with a colleague for quick review. Which GitHub surface is built for that?',
    options: [
      'A gist — a snippet with its own URL, comments, and versioning',
      'A full repository with a README',
      'A GitHub Pages site',
      'An issue on the colleague’s repository',
    ],
    answerIndex: 0,
    explanation:
      'Gists are mini-repositories for single snippets: forkable, commentable, versioned. A full repository is heavyweight for one file, and Pages or issues solve different problems entirely.',
    docId: 'about-gists',
  },
  {
    id: 'gh900-d3-q12',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-gists-wikis-pages',
    kind: 'single',
    stem: 'Where should a project’s long-form handbook — setup guides, architecture notes, FAQ — live when it needs easy collaborative editing?',
    options: [
      'The repository wiki, a set of linked Markdown pages',
      'The commit messages',
      'A secret gist per chapter',
      'The LICENSE file',
    ],
    answerIndex: 0,
    explanation:
      'The wiki holds multi-page Markdown documentation right beside the code, editable in the browser and versioned. It suits manuals and handbooks; gists suit snippets; licenses grant rights.',
    docId: 'about-wikis',
  },
  {
    id: 'gh900-d3-q13',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-gists-wikis-pages',
    kind: 'single',
    stem: 'A student wants to publish a portfolio page straight from a repository named after the project. What is the fit?',
    options: [
      'GitHub Pages, which serves a static site directly from the repository',
      'A GitHub gist with HTML in it',
      'A discussion pinned to the repository',
      'GitHub Desktop',
    ],
    answerIndex: 0,
    explanation:
      'GitHub Pages turns repository content into a published website — pick a branch and a theme and the site builds. Gists hold snippets, and the other options are not publishing surfaces.',
    docId: 'about-github-pages',
  },
  {
    id: 'gh900-d3-q14',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-issues-prs-discussions',
    kind: 'multi',
    stem: 'Which features ship with every issue? Choose all that apply.',
    options: [
      'Labels for classification',
      'Assignees for ownership',
      'Milestones for grouping toward a target',
      'Code-owner review approvals before merging',
      'Automatic merges into the default branch',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Issues carry labels, assignees, and milestones out of the box. Review approvals and merging code belong to pull requests, not issues — the tracker records work, the pull request delivers it.',
    docId: 'about-issues',
  },
  {
    id: 'gh900-d3-q15',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-issues-prs-discussions',
    kind: 'multi',
    stem: 'Which statements about pull requests are true? Choose all that apply.',
    options: [
      'A pull request shows the diff between two branches',
      'Reviewers leave comments and approve or request changes',
      'A pull request can be opened as a draft to signal work in progress',
      'Anyone on the internet can merge a pull request in any public repository',
      'Pull requests can only target the default branch as their base',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Pull requests package a diff, a conversation, and a review workflow — including drafts for early feedback. Merging stays gated by permissions, and the base branch is a choice: any branch can receive a proposal.',
    docId: 'about-pull-requests',
  },
  {
    id: 'gh900-d3-q16',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-notifications',
    kind: 'multi',
    stem: 'Which situations generate a notification for you by default? Choose all that apply.',
    options: [
      'Someone @mentions your username',
      'Someone comments on an issue you opened',
      'You are assigned an issue or pull request',
      'Any repository on GitHub gains a star',
      'A stranger forks a repository you have never touched',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Notifications follow @mentions, assignments, and threads you participate in or watch. The rest of the platform’s activity stays quiet unless you subscribed to it.',
    docId: 'about-notifications',
  },
  {
    id: 'gh900-d3-q17',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-gists-wikis-pages',
    kind: 'multi',
    stem: 'Which statements about gists, wikis, and GitHub Pages are true? Choose all that apply.',
    options: [
      'Gists are mini-repositories for sharing snippets',
      'Wikis hold multi-page Markdown documentation beside the code',
      'Pages publishes a website from repository content',
      'Secret gists are visible only to the account that created them',
      'Pages sites can only use a custom domain',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Gists share snippets, wikis document, Pages publishes. A secret gist is unlisted, not access-controlled — anyone with the URL can read it — and Pages ships a default `github.io` domain, custom domains optional.',
    docId: 'about-gists',
  },
  {
    id: 'gh900-d3-q18',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-issues-prs-discussions',
    kind: 'order',
    stem: 'Order the steps for contributing to a repository you cannot push to directly.',
    items: [
      'Fork the repository',
      'Clone your fork locally',
      'Create a branch for the change',
      'Commit and push the branch to your fork',
      'Open a pull request toward the upstream repository',
    ],
    explanation:
      'Without write access you work through a fork: copy, branch, commit in your copy, then propose the change upstream. This loop is the heart of open source contribution on GitHub.',
    docId: 'about-pull-requests',
  },
  {
    id: 'gh900-d3-q19',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-linking-filtering',
    kind: 'bug',
    stem: 'This pull request description is meant to close issue #12 automatically when it merges. One line breaks that promise. Click it.',
    codeLines: [
      '## What changes',
      'Rewrites the header component for small screens.',
      '',
      '## Linked issue',
      'This PR handles #12',
    ],
    buggyLineIndex: 4,
    explanation:
      '`handles` is not a closing keyword — GitHub links nothing and closes nothing. It must read `Closes #12`, `Fixes #12`, or `Resolves #12` for the issue to shut automatically on merge.',
    docId: 'linking-pr-to-issue',
  },
  {
    id: 'gh900-d3-q20',
    cert: 'gh900',
    domainId: 'gh900-d3',
    subSkillId: 'd3-issues-prs-discussions',
    kind: 'bug',
    stem: 'A pull request should carry a typo fix into the default branch. One setting sends it to the wrong place. Click the broken line.',
    codeLines: [
      '# Pull request setup',
      'base: feature/nav-redesign',
      'compare: fix-typo',
      'title: Fix typo in README',
    ],
    buggyLineIndex: 1,
    explanation:
      'The base is where the change lands, and a typo fix belongs in the default branch — `main`. Basing it on `feature/nav-redesign` tucks the fix into an unrelated long-lived branch instead of shipping it.',
    docId: 'about-pull-requests',
  },
];
