import type { Question } from '../types';

/**
 * GH-900 domain 6 practice bank — Privacy, security, and administration
 * (20 questions). 2FA and passkeys, the permission ladder, EMU, visibility,
 * branch protection, org administration. Mix: 13 single, 4 multi, 3 coding —
 * including the ordering drills for enabling 2FA and branch protection.
 */
export const questions: Question[] = [
  {
    id: 'gh900-d6-q01',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-2fa-passkeys',
    kind: 'single',
    stem: 'What does enabling two-factor authentication change about signing in to GitHub?',
    options: [
      'After the password, a second factor — a code or security credential — is also required',
      'The password becomes optional',
      'GitHub sends a new password by email each week',
      'Nothing changes; it only affects the profile badge',
    ],
    answerIndex: 0,
    explanation:
      '2FA stacks a second proof on top of the password — typically a time-based code or a passkey — so a stolen password alone no longer opens the account.',
    docId: 'configure-2fa',
  },
  {
    id: 'gh900-d6-q02',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-2fa-passkeys',
    kind: 'single',
    stem: 'What makes a passkey more phishing-resistant than a one-time code sent by SMS?',
    options: [
      'It is a cryptographic credential bound to the device and the real GitHub domain, so a fake site cannot capture it',
      'It is longer than six digits',
      'It changes every 30 seconds, unlike SMS codes',
      'It is stored in the browser’s cache',
    ],
    answerIndex: 0,
    explanation:
      'Passkeys are origin-bound key pairs — the authentication happens with the genuine site, so a look-alike phishing page gets nothing usable. SMS codes can be relayed or intercepted; that is the gap passkeys close.',
    docId: 'about-passkeys',
  },
  {
    id: 'gh900-d6-q03',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-2fa-passkeys',
    kind: 'single',
    stem: 'A developer wants to contribute code on GitHub.com. What is GitHub’s policy on 2FA for them?',
    options: [
      '2FA is required to contribute code on GitHub.com',
      '2FA is required only for organization owners',
      '2FA is optional for everyone and always will be',
      '2FA is required only when signing in from a new country',
    ],
    answerIndex: 0,
    explanation:
      'GitHub requires two-factor authentication for code contributors on GitHub.com — securing the software supply chain one account at a time, and making "how do I enable 2FA" a genuinely practical exam answer.',
    docId: 'configure-2fa',
  },
  {
    id: 'gh900-d6-q04',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-permissions-roles',
    kind: 'single',
    stem: 'A long-trusted volunteer should manage issues, labels, and milestones — but must not write code. Which repository role is the smallest that fits?',
    options: [
      'Triage',
      'Write',
      'Maintain',
      'Admin',
    ],
    answerIndex: 0,
    explanation:
      'The organization repository-role ladder is read → triage → write → maintain → admin. Triage manages the issue tracker without push access — exactly a moderator’s job description.',
    docId: 'repository-roles',
  },
  {
    id: 'gh900-d6-q05',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-permissions-roles',
    kind: 'single',
    stem: 'Which repository role suits a deputy maintainer who should run the repository day to day but not change dangerous settings or access?',
    options: [
      'Maintain',
      'Read',
      'Triage',
      'Admin',
    ],
    answerIndex: 0,
    explanation:
      'Maintain grants repository management — issues, milestones, project boards — while reserving settings and access control for admin. It is the "trusted, but the keys stay with admin" tier.',
    docId: 'repository-roles',
  },
  {
    id: 'gh900-d6-q06',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-permissions-roles',
    kind: 'single',
    stem: 'What is the difference between organization roles and repository roles?',
    options: [
      'Organization roles govern the organization itself (owner, member, plus base permissions); repository roles grant per-repository capabilities',
      'They are two names for the same ladder',
      'Organization roles only apply to public repositories',
      'Repository roles outrank organization roles',
    ],
    answerIndex: 0,
    explanation:
      'Two different ladders: org roles manage the organization (membership, billing, defaults), while repository roles (read through admin) apply to one repository. Teams are how the latter get delivered in bulk.',
    docId: 'roles-in-an-organization',
  },
  {
    id: 'gh900-d6-q07',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-org-settings-teams',
    kind: 'single',
    stem: 'An administrator is tired of granting repository access person by person. What is the recommended pattern?',
    options: [
      'Give the permission to a team once — every member inherits it',
      'Create a shared personal account named `dev-team`',
      'Email credentials to new joiners',
      'Make everyone an organization owner',
    ],
    answerIndex: 0,
    explanation:
      'Teams are the delivery mechanism for access: group people, grant the team its role, and membership does the rest — new joiners get everything on arrival, leavers lose it on removal. Team-based access over per-person grants is nearly an exam answer verbatim.',
    docId: 'about-teams',
  },
  {
    id: 'gh900-d6-q08',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-emu-policy',
    kind: 'single',
    stem: 'With Enterprise Managed Users, where do members’ accounts come from and how do they sign in?',
    options: [
      'The enterprise’s identity provider provisions them, and members sign in with corporate credentials',
      'Members create personal accounts and link them by email',
      'GitHub generates anonymous accounts for each member',
      'Members sign in with a shared enterprise password',
    ],
    answerIndex: 0,
    explanation:
      'EMU moves identity to the enterprise: accounts are provisioned and managed through the company’s IdP, sign-in uses corporate credentials, and the enterprise controls the account lifecycle and where it can act.',
    docId: 'enterprise-managed-users',
  },
  {
    id: 'gh900-d6-q09',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-visibility-protection',
    kind: 'single',
    stem: 'Which visibility settings can a repository have?',
    options: [
      'Public, private, and — on organization paid plans — internal',
      'Public and hidden',
      'Public, private, and archived',
      'Visible and invisible',
    ],
    answerIndex: 0,
    explanation:
      'Visibility is who can see the code: public (everyone), private (invited collaborators only), internal (all members of the organization). Archiving is a frozen state, not a visibility.',
    docId: 'setting-repository-visibility',
  },
  {
    id: 'gh900-d6-q10',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-visibility-protection',
    kind: 'single',
    stem: 'An organization on a paid plan sets a repository to `internal`. Who can see it?',
    options: [
      'Every member of the organization, by default',
      'Only invited collaborators',
      'Anyone on the internet',
      'Only organization owners',
    ],
    answerIndex: 0,
    explanation:
      'Internal is the "inside the company" tier: organization members see it without individual invitations, while the outside world cannot — inner-source work without making it public.',
    docId: 'setting-repository-visibility',
  },
  {
    id: 'gh900-d6-q11',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-visibility-protection',
    kind: 'single',
    stem: 'Management demands: "no one pushes directly to `main`, and every change gets at least one review." Which feature makes that an enforced fact?',
    options: [
      'Branch protection on `main` with required pull request reviews',
      'A CONTRIBUTING.md rule asking for reviews',
      'A CODEOWNERS file alone',
      'Renaming `main` to `protected-main`',
    ],
    answerIndex: 0,
    explanation:
      'Documents and CODEOWNERS guide behavior; branch protection enforces it — required reviews, required status checks, no direct pushes. The exam pattern is "guarantee" → branch protection.',
    docId: 'about-protected-branches',
  },
  {
    id: 'gh900-d6-q12',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-org-settings-teams',
    kind: 'single',
    stem: 'An organization owner wants every member of the organization to have 2FA enabled before they can keep contributing. Where is that requirement configured?',
    options: [
      'Organization settings, under the security section',
      'Each repository’s Settings → Branches page',
      'The enterprise billing page',
      'A `.github` repository policy file',
    ],
    answerIndex: 0,
    explanation:
      'Organization-level security settings — including a 2FA requirement for members — belong to the organization administration surface, one level above any repository.',
    docId: 'about-organizations',
  },
  {
    id: 'gh900-d6-q13',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-visibility-protection',
    kind: 'single',
    stem: 'A public repository is switched to private. What happens to the forks that already exist?',
    options: [
      'Existing forks remain visible to the people who made them',
      'All forks are deleted immediately',
      'All forks turn private too',
      'Fork owners receive the repository by transfer',
    ],
    answerIndex: 0,
    explanation:
      'Visibility changes are not retroactive: forks made while the repository was public stay in their owners’ hands — which is why "make it private later" is a weak secrecy strategy.',
    docId: 'setting-repository-visibility',
  },
  {
    id: 'gh900-d6-q14',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-2fa-passkeys',
    kind: 'multi',
    stem: 'Which can serve as a second factor for GitHub 2FA? Choose all that apply.',
    options: [
      'A time-based one-time password (TOTP) app',
      'A passkey or security key',
      'GitHub Mobile approvals',
      'A secret question chosen at signup',
      'A second email address',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'GitHub 2FA accepts TOTP codes, passkeys and security keys, and GitHub Mobile prompts (SMS where available). Secret questions and backup emails are not factors — they are account-recovery fossils.',
    docId: 'configure-2fa',
  },
  {
    id: 'gh900-d6-q15',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-permissions-roles',
    kind: 'multi',
    stem: 'Which statements about repository roles in an organization are true? Choose all that apply.',
    options: [
      'Triage can manage labels and close issues without pushing code',
      'Write can push branches and merge pull requests',
      'Admin controls repository settings and access',
      'Read can merge pull requests into protected branches',
      'Admin access is required before anyone can push a branch',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'The ladder read → triage → write → maintain → admin stacks capabilities cleanly. Read is view-only and merges nothing — and pushing a branch needs just write, not admin.',
    docId: 'repository-roles',
  },
  {
    id: 'gh900-d6-q16',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-visibility-protection',
    kind: 'multi',
    stem: 'Which rules can branch protection enforce on `main`? Choose all that apply.',
    options: [
      'Require pull request reviews before merging',
      'Require status checks (like CI) to pass',
      'Require every open issue to be closed before merging',
      'Restrict who can push to the branch',
      'Automatically delete old issues',
    ],
    answerIndexes: [0, 1, 3],
    explanation:
      'Branch protection is the rulebook for a branch: required reviews, passing checks, restricted pushers, even read-only locks. Open issues never gate a merge — that is tracker territory, not branch policy.',
    docId: 'about-protected-branches',
  },
  {
    id: 'gh900-d6-q17',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-emu-policy',
    kind: 'multi',
    stem: 'Which statements about Enterprise Managed Users are true? Choose all that apply.',
    options: [
      'Member accounts are provisioned by the enterprise identity provider',
      'Members authenticate with corporate credentials',
      'The enterprise governs the accounts’ lifecycle',
      'EMU accounts can contribute to any public repository without restriction',
      'EMU replaces the need for organizations',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'EMU centralizes identity: IdP-provisioned accounts, corporate sign-in, enterprise-managed lifecycle — and those accounts are restricted to the enterprise’s corner of GitHub, not open contributors. Organizations still exist inside it.',
    docId: 'enterprise-managed-users',
  },
  {
    id: 'gh900-d6-q18',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-2fa-passkeys',
    kind: 'order',
    stem: 'Order the steps for enabling 2FA with an authenticator app.',
    items: [
      'Install a TOTP authenticator app on the phone',
      'Open Settings → Password and authentication',
      'Scan the QR code with the app',
      'Enter the six-digit code the app generates to confirm',
      'Download the recovery codes',
    ],
    explanation:
      'Setup runs app-first: get an authenticator, start in account settings, bind it by scanning, prove it with a live code, then bank the recovery codes — losing the phone without those codes is a support ticket.',
    docId: 'configure-2fa',
  },
  {
    id: 'gh900-d6-q19',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-visibility-protection',
    kind: 'order',
    stem: 'Order the steps for protecting the default branch so every change is reviewed and green.',
    items: [
      'Open the repository Settings → Branches page',
      'Add a branch protection rule for `main`',
      'Require one approving review before merging',
      'Require status checks to pass',
      'Save the rule and verify a direct push is rejected',
    ],
    explanation:
      'Protection flows: settings → rule → requirements → save → verify. The last step matters: enforcement is proven by GitHub refusing a direct push, not by the checkbox existing.',
    docId: 'about-protected-branches',
  },
  {
    id: 'gh900-d6-q20',
    cert: 'gh900',
    domainId: 'gh900-d6',
    subSkillId: 'd6-visibility-protection',
    kind: 'bug',
    stem: 'The requirement: no direct pushes to `main` and at least one review — enforced, not requested. One line in the plan fails that requirement. Click it.',
    codeLines: [
      'Document the review rule in CONTRIBUTING.md',
      'Enable a branch protection rule on main',
      'Require one approving review before merge',
      'Require status checks to pass before merge',
    ],
    buggyLineIndex: 0,
    explanation:
      'A CONTRIBUTING.md rule is a request — it cannot stop anyone. Only the branch protection rule enforces: requiring reviews and checks makes "no direct pushes, always reviewed" a technical fact.',
    docId: 'about-protected-branches',
  },
];
