import type { Question } from '../types';

/**
 * GH-900 domain 2 practice bank — Work with GitHub repositories (20 questions).
 *
 * Original items from the public outline: repository anatomy, key community
 * files, template repositories, file management, insights, and maintenance.
 * Mix: 13 single, 4 multi, 3 coding.
 */
export const questions: Question[] = [
  {
    id: 'gh900-d2-q01',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-repo-structure-key-files',
    kind: 'single',
    stem: 'A visitor opens a repository page for the first time. Which file’s content appears front and center below the file list?',
    options: [
      'The README, rendered on the repository home page',
      'The LICENSE, printed in full at the top',
      'The most recent commit message',
      'The CONTRIBUTING.md guidelines',
    ],
    answerIndex: 0,
    explanation:
      'GitHub renders the README on the repository’s front page, which is why it should say what the project is, how to install it, and how to start. Other community files render when you open them, not on the landing page.',
    docId: 'about-readmes',
  },
  {
    id: 'gh900-d2-q02',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-repo-structure-key-files',
    kind: 'single',
    stem: 'A team publishes a utility library with no LICENSE file. What may others legally assume they can do with the code?',
    options: [
      'Nothing beyond viewing it — without a license, all rights stay with the authors',
      'They may reuse it freely because it is public',
      'Public code is automatically placed in the public domain',
      'The MIT license applies by default to public repositories',
    ],
    answerIndex: 0,
    explanation:
      'Copyright does not vanish when code becomes public. Without an explicit license, nobody receives reuse, modification, or distribution rights — the default is "all rights reserved". Choosing and committing a license grants those permissions.',
    docId: 'licensing-a-repository',
  },
  {
    id: 'gh900-d2-q03',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-repo-structure-key-files',
    kind: 'single',
    stem: 'New contributors keep opening pull requests with missing tests and wrong branch names. Which file should the maintainers add to spell out their expectations?',
    options: [
      'CONTRIBUTING.md',
      'CODEOWNERS',
      'SECURITY.md',
      '.gitignore',
    ],
    answerIndex: 0,
    explanation:
      'CONTRIBUTING.md communicates how to participate — style, tests, branch naming, PR etiquette — and GitHub links it when someone opens an issue or PR. CODEOWNERS routes reviews, SECURITY.md handles vulnerability reports.',
    docId: 'contributing-guidelines',
  },
  {
    id: 'gh900-d2-q04',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-repo-structure-key-files',
    kind: 'single',
    stem: 'Every pull request that touches `docs/` should be reviewed by the documentation team before merging. Which file automates that routing?',
    options: [
      'CODEOWNERS, which auto-requests review from the owners of matching paths',
      'CONTRIBUTING.md, which GitHub parses for review rules',
      'A `docs-review.yml` file at the repository root',
      'SECURITY.md with a reviewers section',
    ],
    answerIndex: 0,
    explanation:
      'CODEOWNERS maps path patterns like `docs/` or `*.md` to owners; GitHub automatically requests their review when a pull request changes those paths. It routes reviews — it does not enforce merges by itself.',
    docId: 'about-code-owners',
  },
  {
    id: 'gh900-d2-q05',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-maintenance',
    kind: 'single',
    stem: 'A security researcher finds a flaw in your open source project. Where should the repository tell them to report it privately?',
    options: [
      'SECURITY.md — the security policy shown under the Security tab',
      'A public issue labeled `security`',
      'The README’s changelog section',
      'A comment on the latest release',
    ],
    answerIndex: 0,
    explanation:
      'SECURITY.md states where and how to report vulnerabilities privately. Public issues are the wrong channel — they advertise the flaw before a fix ships.',
    docId: 'add-security-policy',
  },
  {
    id: 'gh900-d2-q06',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-templates-and-branches',
    kind: 'single',
    stem: 'Your team stamps out identical starter repos: same README, same CI workflow, same ignore file. What is the built-in GitHub feature for this?',
    options: [
      'A template repository, whose "Use this template" button creates a fresh repository with the same files',
      'A fork, which copies the repository with its full history',
      'A GitHub gist',
      'Re-cloning and deleting `.git` by hand every time',
    ],
    answerIndex: 0,
    explanation:
      'Marking a repository as a template adds a "Use this template" action that starts a brand-new repository from its contents — fresh history, no shared lineage. A fork stays linked to the upstream and carries its history.',
    docId: 'template-repositories',
  },
  {
    id: 'gh900-d2-q07',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-templates-and-branches',
    kind: 'single',
    stem: 'Which statement correctly separates a template repository from a fork?',
    options: [
      'A template starts a new history; a fork copies history and stays linked to its upstream',
      'A fork starts a new history; a template copies history and stays linked',
      'Both create fresh histories with no upstream link',
      'Both copy history and stay linked to the upstream',
    ],
    answerIndex: 0,
    explanation:
      'Templates are molds: new repository, empty history, no relationship to the mold. Forks are contributions-in-waiting: full copy of history, linked so you can open pull requests back upstream and sync changes down.',
    docId: 'template-repositories',
  },
  {
    id: 'gh900-d2-q08',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-managing-files',
    kind: 'single',
    stem: 'Which ways can a file land in a GitHub repository? Pick the true statement.',
    options: [
      'Through the web editor, a Git push, the API, or by uploading in the file list — all become commits on a branch',
      'Only by `git push` from a local clone',
      'Only through the web interface',
      'Uploads and web edits bypass commits entirely',
    ],
    answerIndex: 0,
    explanation:
      'However a file arrives — browser edit, drag-and-drop upload, API call, or push — the change is recorded as a commit on a branch. The route differs; the mechanism does not.',
    docId: 'gh-docs-repositories',
  },
  {
    id: 'gh900-d2-q09',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-managing-files',
    kind: 'single',
    stem: 'A build directory keeps regenerating and cluttering diffs. Where should the team record that it must never be committed?',
    options: [
      '`.gitignore`, listing the paths Git should leave untracked',
      'CONTRIBUTING.md, in a paragraph about tidiness',
      'CODEOWNERS, pointing the path at a robot account',
      'The repository description field',
    ],
    answerIndex: 0,
    explanation:
      '`.gitignore` lists files and directories Git should not track, so generated artifacts never reach diffs or history. Anything already committed must be removed from the index too — ignoring alone does not untrack it.',
    docId: 'gh-docs-repositories',
  },
  {
    id: 'gh900-d2-q10',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-insights-metrics',
    kind: 'single',
    stem: 'A maintainer wants to see commit frequency, contribution counts, and how quickly pull requests get handled over the last month. Where should they look?',
    options: [
      'The Insights tab, which graphs repository activity',
      'The repository’s releases page',
      'The traffic badge on the README',
      'GitHub Sponsors',
    ],
    answerIndex: 0,
    explanation:
      'The Insights tab aggregates a repository’s activity into graphs — commits, contributors, pull request lifecycle, and more — turning raw history into trends a maintainer can act on.',
    docId: 'about-repository-graphs',
  },
  {
    id: 'gh900-d2-q11',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-insights-metrics',
    kind: 'single',
    stem: 'What does starring a repository do?',
    options: [
      'Bookmarks it for you and counts as a signal of interest',
      'Subscribes you to every notification from it',
      'Adds it to your organization',
      'Requests review access',
    ],
    answerIndex: 0,
    explanation:
      'A star is a bookmark plus a popularity signal — it shows in the star count and your starred list. Watching is what subscribes you to notifications, and it is a different button.',
    docId: 'about-repository-graphs',
  },
  {
    id: 'gh900-d2-q12',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-maintenance',
    kind: 'single',
    stem: 'A user owns eight repositories and keeps pasting the same bug-report template into each one. What is the least-effort fix?',
    options: [
      'Create a `.github` repository — its default community health files apply to every repository they own',
      'Email the template to reporters',
      'Turn every repository into a template',
      'Pin the template as a starred gist',
    ],
    answerIndex: 0,
    explanation:
      'A repository named `.github` under your account supplies default community health files — issue templates, pull request template, CONTRIBUTING, SECURITY, and more — to all your repositories unless a repository overrides them with its own.',
    docId: 'community-health-files',
  },
  {
    id: 'gh900-d2-q13',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-maintenance',
    kind: 'single',
    stem: 'Which set of files best describes the community standards GitHub checks on the Community Standards page?',
    options: [
      'README, license, contributing guide, code of conduct, security policy, and issue templates',
      'Source code, tests, and CI configuration',
      'Release tags, changelog, and binaries',
      'Branch protection rules and deploy keys',
    ],
    answerIndex: 0,
    explanation:
      'The community standards checklist tracks the files that make a repository welcoming and safe to use: documentation, licensing, contribution guidance, conduct, security reporting, and templates for issues and pull requests.',
    docId: 'community-health-files',
  },
  {
    id: 'gh900-d2-q14',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-repo-structure-key-files',
    kind: 'multi',
    stem: 'Which files help a newcomer answer "what is this and may I use it?" Choose all that apply.',
    options: [
      'README.md',
      'LICENSE',
      'CONTRIBUTING.md',
      'node_modules/',
      'The CI workflow file',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'README explains the project, LICENSE grants usage rights, CONTRIBUTING shows how to participate. Dependency folders and CI wiring are plumbing — useful, but not community orientation.',
    docId: 'about-readmes',
  },
  {
    id: 'gh900-d2-q15',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-repo-structure-key-files',
    kind: 'multi',
    stem: 'Which statements about CODEOWNERS are true? Choose all that apply.',
    options: [
      'It maps file paths to the people or teams responsible for them',
      'GitHub automatically requests review from owners when their paths change',
      'It can live in the repository root or in `.github/`',
      'It blocks merges that the owners have not approved by itself',
      'It replaces the need for a CONTRIBUTING guide',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'CODEOWNERS declares ownership and auto-requests reviews. Enforcement — blocking a merge without approval — comes from branch protection rules, not the file itself, and it says nothing about contribution guidance.',
    docId: 'about-code-owners',
  },
  {
    id: 'gh900-d2-q16',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-insights-metrics',
    kind: 'multi',
    stem: 'What can you learn from a repository’s Insights tab? Choose all that apply.',
    options: [
      'How commits and contributors trend over time',
      'How long pull requests stay open before merging',
      'Which files changed most often',
      'The credit card used for the organization’s billing',
      'The passwords of contributors',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Insights turns repository history into graphs: commit pace, contributor activity, pull request and issue lifecycle, code frequency. It never exposes private billing or credentials — those are not activity data.',
    docId: 'about-repository-graphs',
  },
  {
    id: 'gh900-d2-q17',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-templates-and-branches',
    kind: 'multi',
    stem: 'A repository is marked as a template. Which statements are true? Choose all that apply.',
    options: [
      'Anyone with access can generate a new repository from it with one click',
      'The generated repository starts with a fresh commit history',
      'The generated repository is not a fork of the template',
      'Generating from the template deletes the template repository',
      'Files from the template cannot be changed in the new repository',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'A template is a reusable mold: "Use this template" produces an independent repository with its own history that you can change freely. The template itself stays untouched and reusable.',
    docId: 'template-repositories',
  },
  {
    id: 'gh900-d2-q18',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-managing-files',
    kind: 'order',
    stem: 'Order the steps to publish a brand-new local project as a GitHub repository.',
    items: [
      'Create an empty repository on GitHub',
      'Copy its URL and clone it locally',
      'Copy the project files in and stage them',
      'Commit the first snapshot',
      'Push the branch to GitHub',
    ],
    explanation:
      'The classic publish loop: make the remote, clone it, fill it, commit, push. Cloning first means the local folder is already connected to the right remote from the start.',
    docId: 'creating-a-repository',
  },
  {
    id: 'gh900-d2-q19',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-templates-and-branches',
    kind: 'order',
    stem: 'Order the steps to start working from a template repository.',
    items: [
      'Open the template repository page',
      'Click "Use this template"',
      'Name and create the new repository',
      'Clone the new repository locally',
      'Customize the files and push',
    ],
    explanation:
      'Templates flow: start from the mold, name your copy, clone it down, then make it yours. Every step keeps the template itself pristine for the next person.',
    docId: 'template-repositories',
  },
  {
    id: 'gh900-d2-q20',
    cert: 'gh900',
    domainId: 'gh900-d2',
    subSkillId: 'd2-managing-files',
    kind: 'bug',
    stem: 'A reviewer inspects the committed file tree below. One entry should never have been committed. Click the offending line.',
    codeLines: [
      'README.md',
      'LICENSE',
      '.gitignore',
      'CONTRIBUTING.md',
      'node_modules/',
    ],
    buggyLineIndex: 4,
    explanation:
      '`node_modules/` is a regenerable dependency folder — it belongs in `.gitignore`, not in history, where it bloats every clone. Source files like the README, license, and contributing guide are exactly what should be committed.',
    docId: 'gh-docs-repositories',
  },
];
