import type { Question } from '../types';

/**
 * GH-900 domain 5 practice bank — Manage projects with GitHub (20 questions).
 * Projects, views and layouts, labels and milestones, saved replies and
 * assignees, built-in automations, insights. Mix: 13 single, 4 multi,
 * 3 coding.
 */
export const questions: Question[] = [
  {
    id: 'gh900-d5-q01',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-projects-layouts',
    kind: 'single',
    stem: 'A scrum team wants one flexible surface to plan and track their sprint — mixing issues, pull requests, and rough notes. What should they use?',
    options: [
      'A GitHub Project with table, board, and roadmap layouts',
      'A repository wiki',
      'A milestone per person',
      'A long-lived branch named `planning`',
    ],
    answerIndex: 0,
    explanation:
      'Projects are GitHub’s planning surface: pull in issues and pull requests, add draft items, slice the work through multiple views, and watch progress with insights. Wikis document; milestones and branches serve other jobs.',
    docId: 'about-projects',
  },
  {
    id: 'gh900-d5-q02',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-projects-layouts',
    kind: 'single',
    stem: 'Which kinds of items can live in a Project?',
    options: [
      'Issues, pull requests, and draft issues',
      'Only issues',
      'Commits and tags',
      'Repository releases and deploy keys',
    ],
    answerIndex: 0,
    explanation:
      'A Project holds any mix of issues, pull requests, and draft issues — the drafts capture ideas that are not yet worth a full issue. Commits, tags, and releases are repository history, not planning items.',
    docId: 'about-projects',
  },
  {
    id: 'gh900-d5-q03',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-projects-layouts',
    kind: 'single',
    stem: 'A project has one view grouped by status as a board, and another view grouped by assignee as a table. How is this possible?',
    options: [
      'Each view keeps its own layout, grouping, and filters — views are alternate lenses on the same items',
      'Each project can only define one view',
      'The team maintains two separate Projects',
      'Boards and tables cannot show the same items',
    ],
    answerIndex: 0,
    explanation:
      'Views are saved perspectives: same project, same items, different layout, grouping, and filtering. You add as many views as useful — a board for the standup, a table for triage, a roadmap for the long arc.',
    docId: 'project-view-layouts',
  },
  {
    id: 'gh900-d5-q04',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-labels-milestones',
    kind: 'single',
    stem: 'A maintainer wants newcomers to find all "good first issue" work quickly. What is the lightest built-in mechanism?',
    options: [
      'Labels — classify items and filter on them, including default labels like `good first issue`',
      'A milestone named `newcomers`',
      'A new repository for easy tasks',
      'Renaming branches to start with `easy-`',
    ],
    answerIndex: 0,
    explanation:
      'Labels classify issues and pull requests; `good first issue` even ships as a default label and powers discovery pages for contributors. Milestones group by deadline, not by audience.',
    docId: 'managing-labels',
  },
  {
    id: 'gh900-d5-q05',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-labels-milestones',
    kind: 'single',
    stem: 'What is a milestone for?',
    options: [
      'Grouping issues and pull requests toward a goal with a target date',
      'Labeling items by difficulty',
      'Marking a release tag in Git history',
      'Granting a contributor write access',
    ],
    answerIndex: 0,
    explanation:
      'A milestone is a dated bucket: attach the work that must land, and its page charts completion as items close — the sprint or release pulse. Labels classify; tags mark releases; access is roles.',
    docId: 'about-milestones',
  },
  {
    id: 'gh900-d5-q06',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-labels-milestones',
    kind: 'single',
    stem: 'Opening a milestone page, what does the team see at a glance?',
    options: [
      'A progress breakdown — how many of its issues and pull requests are open versus closed',
      'The repository’s commit graph',
      'A list of everyone who ever starred the repository',
      'The label definitions for the repository',
    ],
    answerIndex: 0,
    explanation:
      'The milestone page aggregates its items’ state into progress, so "are we going to make the date?" is answerable in one look — that is the whole reason to group work by milestone.',
    docId: 'about-milestones',
  },
  {
    id: 'gh900-d5-q07',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-saved-replies-assignees',
    kind: 'single',
    stem: 'A maintainer types the same "please add reproduction steps" response ten times a week. Which feature removes the repetition?',
    options: [
      'Saved replies — canned responses inserted with a click',
      'Milestones',
      'Custom project fields',
      'Branch protection',
    ],
    answerIndex: 0,
    explanation:
      'Saved replies store your frequent responses and insert them into any comment box, keeping triage consistent and fast. They are personal settings, not repository configuration.',
    docId: 'about-saved-replies',
  },
  {
    id: 'gh900-d5-q08',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-saved-replies-assignees',
    kind: 'single',
    stem: 'What does assigning an issue communicate?',
    options: [
      'That a specific person is responsible for moving it forward',
      'That the issue is fixed',
      'That the issue is blocked',
      'That the issue must close within 24 hours',
    ],
    answerIndex: 0,
    explanation:
      'Assignment is the ownership signal — the assignee owes the next action. It changes nothing about the issue’s state or deadline; status and dates live elsewhere (labels, milestones, projects).',
    docId: 'about-saved-replies',
  },
  {
    id: 'gh900-d5-q09',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-labels-milestones',
    kind: 'single',
    stem: 'Which of these is a built-in project automation?',
    options: [
      'When an issue in the project closes, its item moves to Done automatically',
      'Auto-deleting closed issues after a week',
      'Auto-merging pull requests assigned to the project',
      'Auto-creating a repository for every draft item',
    ],
    answerIndex: 0,
    explanation:
      'Built-in automations handle the mechanical state sync — closing an issue or merging a PR can flip its project item to Done. Merges and deletions stay human decisions.',
    docId: 'built-in-automations',
  },
  {
    id: 'gh900-d5-q10',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-project-insights',
    kind: 'single',
    stem: 'Stakeholders ask "is the current plan on track?" Which Project feature answers with charts instead of opinions?',
    options: [
      'Project insights — graphs of item completion over time, by field',
      'The repository star count',
      'The contributors graph',
      'The pull request review count',
    ],
    answerIndex: 0,
    explanation:
      'Insights chart the project’s own history — items completed over time, sliced by status, assignee, or any custom field — turning the board into evidence about pace and trajectory.',
    docId: 'about-project-insights',
  },
  {
    id: 'gh900-d5-q11',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-project-insights',
    kind: 'single',
    stem: 'A program manager needs to share project insights with people who are not repository collaborators. What is possible?',
    options: [
      'Insights can be shared so viewers can see the charts without project edit rights',
      'Nothing — insights are private to project administrators forever',
      'Insights must be screenshotted and emailed',
      'Sharing requires transferring the project to an organization',
    ],
    answerIndex: 0,
    explanation:
      'Project insights are shareable: expose the charts to a wider audience while editing stays with project members. The data follows the project, not the repository permission list.',
    docId: 'about-project-insights',
  },
  {
    id: 'gh900-d5-q12',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-projects-layouts',
    kind: 'single',
    stem: 'During planning, someone floats an idea that is too vague for a real issue. How can it still join the sprint board?',
    options: [
      'Add it as a draft issue item in the Project',
      'Open a placeholder issue and close it immediately',
      'Put it in the wiki and hope',
      'Tag the next release with it',
    ],
    answerIndex: 0,
    explanation:
      'Draft issues are project-native placeholder items: they sit on the board like any item, and convert into real issues when the idea firms up. No repository noise in the meantime.',
    docId: 'about-projects',
  },
  {
    id: 'gh900-d5-q13',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-projects-layouts',
    kind: 'single',
    stem: 'A team wants to slice project items by "Priority" and "Team" on top of status. What mechanism adds those columns?',
    options: [
      'Custom fields on the Project (single select, number, date, iteration…)',
      'Extra repositories',
      'New default labels',
      'A second GitHub account',
    ],
    answerIndex: 0,
    explanation:
      'Projects grow their own metadata: custom fields of several types, defined per project, usable for grouping, filtering, and sorting — status and dates come built in, priority and team are yours to add.',
    docId: 'about-projects',
  },
  {
    id: 'gh900-d5-q14',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-projects-layouts',
    kind: 'multi',
    stem: 'Which item types can you add to a GitHub Project? Choose all that apply.',
    options: [
      'An existing issue',
      'An existing pull request',
      'A draft issue',
      'A git commit',
      'A repository release',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Projects plan: issues, pull requests, and drafts. Commits and releases belong to repository history — a board tracks work, not code artifacts.',
    docId: 'about-projects',
  },
  {
    id: 'gh900-d5-q15',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-labels-milestones',
    kind: 'multi',
    stem: 'Which statements about labels are true? Choose all that apply.',
    options: [
      'Labels classify issues and pull requests',
      'You can filter issue lists by label',
      'Repositories ship with default labels like `bug` and `enhancement`',
      'Anyone can create labels in any repository',
      'Labels can set a due date on an issue',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Labels classify and filter, with a default set out of the box; deadlines live on milestones, not labels. Creating or editing labels requires write access — visitors cannot redefine your taxonomy.',
    docId: 'managing-labels',
  },
  {
    id: 'gh900-d5-q16',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-labels-milestones',
    kind: 'multi',
    stem: 'Which statements about milestones are true? Choose all that apply.',
    options: [
      'A milestone has a target due date',
      'Issues and pull requests can both belong to a milestone',
      'A milestone page tracks completion progress',
      'Closing a milestone deletes its issues',
      'Milestones replace the need for labels',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Milestones are dated containers for issues and pull requests, charting completion as work closes. Closing one closes nothing and deletes nothing — and labels still classify within it.',
    docId: 'about-milestones',
  },
  {
    id: 'gh900-d5-q17',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-projects-layouts',
    kind: 'multi',
    stem: 'Which statements about project views are true? Choose all that apply.',
    options: [
      'A project can have multiple saved views',
      'Each view can use a different layout, such as table, board, or roadmap',
      'Each view can group, sort, and filter differently',
      'Every project is limited to a single board layout',
      'Views are separate copies of the items',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Views are lenses, not copies: many views, each with its own layout and slicing, over one shared set of items. The "one board per project" world ended when views arrived.',
    docId: 'project-view-layouts',
  },
  {
    id: 'gh900-d5-q18',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-projects-layouts',
    kind: 'order',
    stem: 'Order the steps for standing up a new Project for a team.',
    items: [
      'Create the Project',
      'Add items — issues, pull requests, and drafts',
      'Define custom fields like Priority or Team',
      'Build the views the team needs (board, table, roadmap)',
      'Review insights as work progresses',
    ],
    explanation:
      'Setup flows container-first: create the project, fill it with items, enrich with fields, shape views for each audience, then let insights narrate progress from real activity.',
    docId: 'about-projects',
  },
  {
    id: 'gh900-d5-q19',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-labels-milestones',
    kind: 'order',
    stem: 'Order the lifecycle of a milestone.',
    items: [
      'Create the milestone with a due date and description',
      'Attach the issues and pull requests that must land',
      'Close the tracked work as pull requests merge',
      'Watch the milestone progress as items complete',
      'Close the milestone when the goal date arrives',
    ],
    explanation:
      'A milestone ages well only in this order: define the target, commit the work to it, burn it down while watching progress, then close it out — open issues left behind are a planning signal, not an error.',
    docId: 'about-milestones',
  },
  {
    id: 'gh900-d5-q20',
    cert: 'gh900',
    domainId: 'gh900-d5',
    subSkillId: 'd5-labels-milestones',
    kind: 'bug',
    stem: 'A team wrote this triage plan. One step misuses milestones. Click the offending line.',
    codeLines: [
      'Create a "triage" label to classify incoming issues',
      'Create milestone "Sprint 42" with a due date',
      'Assign every new issue to milestone "Backlog"',
      'Add the sprint issues to the Sprint 42 board view',
    ],
    buggyLineIndex: 2,
    explanation:
      'Milestones are dated goals, not buckets for all incoming work — parking everything in a "Backlog" milestone makes progress meaningless. New issues stay unlabeled-by-milestone; a project view or label serves as the backlog.',
    docId: 'about-milestones',
  },
];
