import type { Question } from '../types';

/**
 * GH-900 domain 7 practice bank — Explore the GitHub community (20 questions).
 * Sponsors, following, Marketplace, InnerSource, forks, templates, and how to
 * find somewhere to contribute. Mix: 13 single, 4 multi, 3 coding.
 */
export const questions: Question[] = [
  {
    id: 'gh900-d7-q01',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-open-source-sponsors',
    kind: 'single',
    stem: 'A library your product depends on has saved your team hundreds of hours. What does GitHub Sponsors let you do about that?',
    options: [
      'Fund the maintainers with one-time or recurring payments',
      'Buy a support contract with an SLA',
      'Hire the maintainers as contractors automatically',
      'Donate compute credits for their CI',
    ],
    answerIndex: 0,
    explanation:
      'GitHub Sponsors is the platform’s funding rail: sponsor an individual or project once or monthly, and GitHub covers the payment fees so the full amount lands with the maintainer.',
    docId: 'github-sponsors',
  },
  {
    id: 'gh900-d7-q02',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-open-source-sponsors',
    kind: 'single',
    stem: 'What is the difference between starring a project and sponsoring it?',
    options: [
      'A star bookmarks it and signals interest; sponsorship sends money to sustain it',
      'A star notifies the maintainer; sponsorship does not',
      'Stars are public but sponsorships are secret',
      'There is no difference — sponsorship is a paid star',
    ],
    answerIndex: 0,
    explanation:
      'Stars are applause — bookmarks that feed discovery. Sponsors are fuel — actual money that keeps maintainers maintaining. Both are visible on the repository; only one pays the rent.',
    docId: 'github-sponsors',
  },
  {
    id: 'gh900-d7-q03',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-following',
    kind: 'single',
    stem: 'You follow a developer whose libraries you admire. Where does their public activity now show up?',
    options: [
      'In your personal dashboard feed',
      'In your email inbox as attachments',
      'In every repository you own',
      'In your commit messages',
    ],
    answerIndex: 0,
    explanation:
      'Following adds a person’s public activity to the feed on your dashboard — a lightweight way to keep tabs on people whose work teaches you things.',
    docId: 'following-people',
  },
  {
    id: 'gh900-d7-q04',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-following',
    kind: 'single',
    stem: 'How do you keep an eye on what an organization — say, the one behind your database — releases?',
    options: [
      'Follow the organization; its activity joins your dashboard feed',
      'Star every repository it owns',
      'Email the organization’s contact address weekly',
      'Fork all of its repositories',
    ],
    answerIndex: 0,
    explanation:
      'Organizations can be followed just like people, folding their public activity into your feed — one follow instead of starring dozens of repositories.',
    docId: 'following-organizations',
  },
  {
    id: 'gh900-d7-q05',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-following',
    kind: 'single',
    stem: 'Following a person and watching a repository are easy to mix up. Which sentence is correct?',
    options: [
      'Following shapes your dashboard feed; watching subscribes you to a repository’s notifications',
      'Following sends notifications; watching fills your feed',
      'Both do exactly the same thing on different pages',
      'Neither affects anything until you enable email',
    ],
    answerIndex: 0,
    explanation:
      'Follow = feed content about a person or organization. Watch = notifications about a repository’s conversations. One is for staying inspired, the other for staying informed.',
    docId: 'following-people',
  },
  {
    id: 'gh900-d7-q06',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-marketplace',
    kind: 'single',
    stem: 'A team wants CI previews on every pull request and auto-labeling of stale issues. Where do they look first?',
    options: [
      'GitHub Marketplace — the catalog of apps and Actions that extend repositories',
      'The GitHub REST API reference',
      'GitHub Sponsors',
      'Their enterprise billing page',
    ],
    answerIndex: 0,
    explanation:
      'Marketplace lists apps and Actions you can install or plug into repositories — CI, labeling, security scanning, and thousands of other capabilities somebody has already built.',
    docId: 'github-marketplace',
  },
  {
    id: 'gh900-d7-q07',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-marketplace',
    kind: 'single',
    stem: 'Which kinds of things does GitHub Marketplace offer?',
    options: [
      'Apps and Actions that extend repositories and organizations',
      'Physical merchandise',
      'Official GitHub employment contracts',
      'Second-hand developer hardware',
    ],
    answerIndex: 0,
    explanation:
      'Marketplace is a software catalog: GitHub Apps and ready-made Actions, installable per repository or organization. No t-shirts, no laptops, no jobs.',
    docId: 'github-marketplace',
  },
  {
    id: 'gh900-d7-q08',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-innersource',
    kind: 'single',
    stem: 'A large company wants its 40 teams to collaborate on internal code the way strangers collaborate on open source. What is this practice called?',
    options: [
      'InnerSource — applying open source practices inside the organization',
      'OuterSource',
      'Enterprise forking',
      'Private crowdfunding',
    ],
    answerIndex: 0,
    explanation:
      'InnerSource borrows the machinery of open source — transparent repositories, contribution guidelines, public-by-default inside the walls — so any team can contribute to any internal project through pull requests.',
    docId: 'innersource-module',
  },
  {
    id: 'gh900-d7-q09',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-innersource',
    kind: 'single',
    stem: 'Which practice best exemplifies InnerSource inside a company?',
    options: [
      'Internal repositories stay readable across the org, with CONTRIBUTING guides and issues open to all employees',
      'Each team keeps its repositories invisible to other teams',
      'All code review happens by email attachments',
      'The security team approves every character of every pull request',
    ],
    answerIndex: 0,
    explanation:
      'InnerSource lives on internal transparency: readable repositories, discoverable issues, and contribution norms — so a developer in another team can fix a bug where they found it instead of filing a ticket and waiting.',
    docId: 'innersource-best-practices',
  },
  {
    id: 'gh900-d7-q10',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-forks-templates-discovery',
    kind: 'single',
    stem: 'What is a fork?',
    options: [
      'A copy of a repository under your own account, linked to the original so you can propose changes back',
      'A completely unrelated copy with no connection to the original',
      'A branch that lives on someone else’s repository',
      'A compressed download of the source',
    ],
    answerIndex: 0,
    explanation:
      'A fork is your server-side copy of someone’s repository: you get full history, the link to upstream stays, and your branches can flow back as pull requests — the standard route when you lack write access.',
    docId: 'about-forks',
  },
  {
    id: 'gh900-d7-q11',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-forks-templates-discovery',
    kind: 'single',
    stem: 'What distinguishes `git clone` from forking on GitHub?',
    options: [
      'Clone gives you a local working copy; a fork gives you a GitHub-hosted copy you can propose changes from',
      'Clone and fork are two commands for the same thing',
      'Cloning requires write access; forking does not',
      'A fork is local; a clone is on GitHub',
    ],
    answerIndex: 0,
    explanation:
      'They answer different needs: clone = get the code onto your machine; fork = get a copy onto GitHub under your account so pull requests back to the original are possible. Contribution typically does both.',
    docId: 'about-forks',
  },
  {
    id: 'gh900-d7-q12',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-forks-templates-discovery',
    kind: 'single',
    stem: 'A teacher found a repository whose file structure is perfect for class assignments, but students’ work must be entirely independent. What should students click?',
    options: [
      '"Use this template" — a fresh repository with no link or shared history',
      '"Fork" — a linked copy under each student’s account',
      '"Star" — a bookmark of the repository',
      '"Watch" — notifications for the repository',
    ],
    answerIndex: 0,
    explanation:
      'Template = fresh start (new history, no upstream relationship). Fork = contribution copy (linked, history intact). Independent student projects want the former; proposing fixes back to the teacher’s original wants the latter.',
    docId: 'template-repositories',
  },
  {
    id: 'gh900-d7-q13',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-open-source-sponsors',
    kind: 'single',
    stem: 'A newcomer wants to start contributing but has no idea where. What is the documented first move?',
    options: [
      'Explore GitHub for projects and topics, filtering for `good first issue` labels',
      'Email the maintainers of the Linux kernel',
      'Open a pull request to the most starred repository',
      'Pay for a GitHub Enterprise plan first',
    ],
    answerIndex: 0,
    explanation:
      'GitHub’s own guide to finding ways to contribute: browse topics and projects you already use, then filter repositories for `good first issue` — labels maintained exactly for newcomers.',
    docId: 'ways-to-contribute',
  },
  {
    id: 'gh900-d7-q14',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-open-source-sponsors',
    kind: 'multi',
    stem: 'Which statements about GitHub Sponsors are true? Choose all that apply.',
    options: [
      'You can sponsor individual maintainers',
      'You can sponsor projects and organizations',
      'Sponsorships can be one-time or recurring',
      'Sponsors automatically receive write access to the repository',
      'Only large companies can be sponsors',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Sponsors handles people and projects, once or monthly, from anyone with a payment method. Money never buys commit rights — access is a roles decision, not a billing one.',
    docId: 'github-sponsors',
  },
  {
    id: 'gh900-d7-q15',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-marketplace',
    kind: 'multi',
    stem: 'Which statements about GitHub Marketplace are true? Choose all that apply.',
    options: [
      'It lists GitHub Apps and Actions',
      'Listings can be installed for a repository or an organization',
      'Listings cover categories like CI, code review, and security',
      'Everything in Marketplace is built and operated by GitHub itself',
      'Marketplace requires an enterprise account',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Marketplace aggregates third-party (and some first-party) apps and Actions, installable at repository or organization scope. Most of the catalog is community-built, and browsing needs no enterprise plan.',
    docId: 'github-marketplace',
  },
  {
    id: 'gh900-d7-q16',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-innersource',
    kind: 'multi',
    stem: 'Which practices belong to InnerSource? Choose all that apply.',
    options: [
      'Discoverable, readable internal repositories across the organization',
      'Contribution guidelines for internal projects',
      'Accepting pull requests from any internal team',
      'Publishing all company code publicly on GitHub.com',
      'Removing team ownership of repositories',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'InnerSource is open source’s culture, kept inside: transparent internal repos, contribution norms, cross-team pull requests. Nothing goes public, and owning teams stay — they just accept guests.',
    docId: 'innersource-module',
  },
  {
    id: 'gh900-d7-q17',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-forks-templates-discovery',
    kind: 'multi',
    stem: 'Which are recognized first steps for contributing to an unfamiliar open source project? Choose all that apply.',
    options: [
      'Read the README and CONTRIBUTING guide',
      'Look for issues labeled `good first issue`',
      'Check existing issues and pull requests before opening your own',
      'Push your branch straight to the upstream repository',
      'Start by rewriting the project’s architecture',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Etiquette is the entry ticket: read the norms, pick a starter issue, make sure you are not the third person on the same bug. Direct pushes upstream are what write access — and tact — prevent.',
    docId: 'ways-to-contribute',
  },
  {
    id: 'gh900-d7-q18',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-forks-templates-discovery',
    kind: 'order',
    stem: 'Order the classic first-contribution flow for a project you cannot push to directly.',
    items: [
      'Find a project and read its README and CONTRIBUTING guide',
      'Pick an issue labeled good first issue',
      'Fork the repository and create a branch',
      'Commit the fix and push it to your fork',
      'Open a pull request upstream',
    ],
    explanation:
      'Explore first, then a starter issue, then the mechanics — fork, branch, commit, push, propose. The order exists because a PR that ignores the project’s norms creates work for exactly the people you hoped to help.',
    docId: 'ways-to-contribute',
  },
  {
    id: 'gh900-d7-q19',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-forks-templates-discovery',
    kind: 'bug',
    stem: 'A developer plans to propose a fix to an open source project. One step in the plan will not produce a pull request. Click the broken line.',
    codeLines: [
      'Fork the project repository',
      'Create a branch for the fix',
      'Commit and push the branch to the fork',
      'Click "Use this template" to generate the pull request',
    ],
    buggyLineIndex: 3,
    explanation:
      '"Use this template" stamps out a brand-new repository — it opens nothing and stays unlinked. Pull requests are opened from your pushed branch toward the upstream repository.',
    docId: 'about-forks',
  },
  {
    id: 'gh900-d7-q20',
    cert: 'gh900',
    domainId: 'gh900-d7',
    subSkillId: 'd7-innersource',
    kind: 'bug',
    stem: 'A company writes this InnerSource rollout plan. One line defeats the whole idea. Click it.',
    codeLines: [
      'Make internal repositories discoverable across the org',
      'Add a CONTRIBUTING guide to each major repository',
      'Label cross-team-friendly issues with "help wanted"',
      'Keep every repository visible only to its owning team',
    ],
    buggyLineIndex: 3,
    explanation:
      'InnerSource runs on internal transparency: if other teams cannot read the repository, guidelines and labels are decoration. Visibility across the organization is the precondition, not an option.',
    docId: 'innersource-best-practices',
  },
];
