import type { Question } from '../types';

/**
 * GH-900 domain 1 practice bank — Git and GitHub basics (20 questions).
 *
 * Every item is original: written from the public skills outline and the
 * official docs, with invented scenarios. Mix: 13 single, 4 multi, and 3
 * coding items (GitHub Flow ordering among them).
 */
export const questions: Question[] = [
  {
    id: 'gh900-d1-q01',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-version-control',
    kind: 'single',
    stem: 'A four-person team edits trip reports in a shared network folder. Every week someone pastes over a colleague’s file and the wording is gone forever. Which capability does version control add that fixes this?',
    options: [
      'It records every change as a recoverable snapshot, so any earlier version can be restored and compared',
      'It locks each file so only one person can edit it at a time',
      'It backs up the folder to the cloud once per night',
      'It emails a copy of every file to the whole team after each edit',
    ],
    answerIndex: 0,
    explanation:
      'Version control keeps the project’s full history — who changed what, when, and why — so you can revert to any previous state and compare versions. File locking and nightly backups do not give you per-change history or easy merging of parallel work.',
    docId: 'about-git',
  },
  {
    id: 'gh900-d1-q02',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-version-control',
    kind: 'single',
    stem: 'A developer finishes commits while on a flight with no internet, then syncs after landing. Which Git property makes this possible?',
    options: [
      'Git is distributed — each collaborator holds the full repository history locally',
      'Git queues commits in the cloud and replays them when you reconnect',
      'Git only stores the latest snapshot, so there is nothing to sync',
      'Git requires a central server to authorize every commit',
    ],
    answerIndex: 0,
    explanation:
      'Because Git is distributed, your clone contains the complete history, and committing, branching, and diffing are local operations. Network access is only needed to push, pull, or fetch when you exchange work with others.',
    docId: 'about-git',
  },
  {
    id: 'gh900-d1-q03',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-git-vs-github',
    kind: 'single',
    stem: 'A teammate drafts a script and includes the line `git pull-request`. It fails. Why?',
    options: [
      'A pull request is a GitHub collaboration feature, not a Git command',
      'The command exists but needs the `--web` flag',
      'Pull requests only work from GitHub Desktop',
      'Git commands must run inside a pull request',
    ],
    answerIndex: 0,
    explanation:
      'Git handles local version control; the pull request — proposing a merge, collecting review, hosting the discussion — lives on GitHub. There is no `git pull-request` subcommand in Git itself.',
    docId: 'hello-world',
  },
  {
    id: 'gh900-d1-q04',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-git-vs-github',
    kind: 'single',
    stem: 'Which of these tasks can be completed entirely in Git on your own machine, with no GitHub connection?',
    options: [
      'Creating a branch, staging files, and committing a snapshot',
      'Requesting a review on a pull request',
      'Filing an issue on a repository you do not own',
      'Watching a repository for notifications',
    ],
    answerIndex: 0,
    explanation:
      'Branching, staging, committing, merging, and inspecting history are local Git operations. Reviews, issues, notifications, and pull request conversations are GitHub features that need the hosting layer.',
    docId: 'about-git',
  },
  {
    id: 'gh900-d1-q05',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-repos-commits-branches',
    kind: 'single',
    stem: 'What exactly is a commit?',
    options: [
      'A saved snapshot of the staged files, carrying a message, author, and timestamp',
      'A compressed backup of the whole repository folder',
      'A note appended to the previous commit without a new snapshot',
      'A copy of the files uploaded to GitHub',
    ],
    answerIndex: 0,
    explanation:
      'A commit records the state of whatever you staged, plus metadata — author, time, and a message explaining why. It is not a folder backup or an upload; pushing to GitHub is a separate step.',
    docId: 'hello-world',
  },
  {
    id: 'gh900-d1-q06',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-repos-commits-branches',
    kind: 'single',
    stem: 'A team names one branch the agreed source of truth that stays deployable and receives merged work. What is this branch conventionally called?',
    options: [
      'The default branch, usually `main`',
      'The release tag',
      'The origin remote',
      'The staging clone',
    ],
    answerIndex: 0,
    explanation:
      'Every repository has a default branch — `main` by convention — which is the source of truth other branches merge into. Tags mark releases, and `origin` is the nickname of the remote server.',
    docId: 'github-flow',
  },
  {
    id: 'gh900-d1-q07',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-account-types',
    kind: 'single',
    stem: 'A study group wants a shared place that owns their repositories, with teams and permission levels. Which GitHub account type fits?',
    options: [
      'An organization — a shared owner for repositories, teams, and roles',
      'A second personal account shared by everyone',
      'An enterprise with a billing plan',
      'A gist with collaborators',
    ],
    answerIndex: 0,
    explanation:
      'Organizations are shared accounts for groups: they own repositories and organize people into teams with roles. Sharing one personal account breaks identity and attribution, and an enterprise is for many organizations under one owner.',
    docId: 'types-of-github-accounts',
  },
  {
    id: 'gh900-d1-q08',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-account-types',
    kind: 'single',
    stem: 'A company wants one invoice and centralized security policy across its twelve GitHub organizations. What should it set up?',
    options: [
      'An enterprise, which centralizes billing, policy, and security across organizations',
      'A team in each organization',
      'One organization with twelve owners',
      'A repository with a billing README',
    ],
    answerIndex: 0,
    explanation:
      'The enterprise tier sits above organizations: unified billing, central policy, and security management across every organization it contains. Teams and owners operate inside a single organization.',
    docId: 'types-of-github-accounts',
  },
  {
    id: 'gh900-d1-q09',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-github-flow',
    kind: 'single',
    stem: 'In GitHub flow, why is each change built on its own short-lived branch?',
    options: [
      'The default branch stays deployable, and each branch carries one reviewable idea',
      'Branches are required because Git forbids committing to the default branch',
      'Short branches use less storage on GitHub',
      'Every branch automatically deploys to production',
    ],
    answerIndex: 0,
    explanation:
      'GitHub flow keeps the default branch always shippable; topic branches isolate one idea each so review stays small and merges stay safe. Git does not forbid direct commits — that is a convention (later enforced with branch protection).',
    docId: 'github-flow',
  },
  {
    id: 'gh900-d1-q10',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-markdown',
    kind: 'single',
    stem: 'An issue body contains `- [ ] book the venue` and `- [x] send invites`. What happens on the issue page?',
    options: [
      'Checkboxes render and the issue shows a task-progress indicator that updates as boxes are ticked',
      'The lines render as plain hyphen bullets; the brackets are ignored',
      'GitHub opens a pull request for each unticked task',
      'The issue is automatically assigned to the repository owner',
    ],
    answerIndex: 0,
    explanation:
      'Task list syntax (`- [ ]` / `- [x]`) renders interactive checkboxes and drives a progress bar on the issue — a detail the exam likes because it is specific and visual.',
    docId: 'markdown-formatting',
  },
  {
    id: 'gh900-d1-q11',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-markdown',
    kind: 'single',
    stem: 'Which syntax renders the words `ship it` in bold in an issue comment?',
    options: [
      '`**ship it**`',
      '`__ship it__` in angle brackets',
      '`# ship it`',
      '``` - ship it - ```',
    ],
    answerIndex: 0,
    explanation:
      'Double asterisks mark bold (`**bold**`) and single asterisks mark italics. A single `#` makes a heading, and a leading `-` makes a list item — neither styles text as bold.',
    docId: 'markdown-formatting',
  },
  {
    id: 'gh900-d1-q12',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-desktop-mobile',
    kind: 'single',
    stem: 'A designer is comfortable in a GUI and avoids the terminal. Which tool lets them branch, view diffs, and open pull requests visually on their own machine?',
    options: [
      'GitHub Desktop',
      'GitHub Mobile',
      'The REST API',
      'Codespaces',
    ],
    answerIndex: 0,
    explanation:
      'GitHub Desktop is the visual Git client: branches, diffs, and pull requests without typing commands. Mobile handles review and triage on the go, the API is for programs, and Codespaces is a cloud environment for running code.',
    docId: 'github-desktop',
  },
  {
    id: 'gh900-d1-q13',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-desktop-mobile',
    kind: 'single',
    stem: 'Which task is GitHub Mobile genuinely good for while commuting?',
    options: [
      'Reviewing a pull request, leaving a comment, and merging it',
      'Authoring a new dev container configuration',
      'Debugging a failing workflow by editing its YAML inline',
      'Generating a new SSH key pair for the laptop you left at home',
    ],
    answerIndex: 0,
    explanation:
      'GitHub Mobile shines at review and triage — reading and merging pull requests, handling issues and notifications. Deep configuration editing and key management belong on a real machine.',
    docId: 'github-mobile',
  },
  {
    id: 'gh900-d1-q14',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-version-control',
    kind: 'multi',
    stem: 'Which benefits does version control actually provide? Choose all that apply.',
    options: [
      'Restoring any earlier version of a file',
      'Comparing two versions to see exactly what changed',
      'Letting several people work in parallel and blending their changes',
      'Guaranteeing that merged code is bug-free',
      'Automatically writing the project documentation',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Version control gives recoverable history, precise diffs, and safe parallel work. It says nothing about code correctness — that is what review, tests, and CI are for — and it documents changes, not the product itself.',
    docId: 'about-git',
  },
  {
    id: 'gh900-d1-q15',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-repos-commits-branches',
    kind: 'multi',
    stem: 'Which statements about branches are true? Choose all that apply.',
    options: [
      'A branch is a movable label pointing at a line of commits',
      'Branches let several people work without stepping on each other',
      'By convention the default branch is called `main`',
      'A branch physically duplicates the repository folder on disk',
      'Branches can only be created on the GitHub website',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Branches are lightweight labels that keep parallel lines of work separate — creatable locally in Git or on GitHub. No folder duplication happens; Git tracks lines of commits, not copies of files.',
    docId: 'github-flow',
  },
  {
    id: 'gh900-d1-q16',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-account-types',
    kind: 'multi',
    stem: 'Which statements about GitHub account types are correct? Choose all that apply.',
    options: [
      'A personal account is your individual identity on GitHub',
      'An organization can own repositories and group members into teams',
      'An organization signs in through one shared account that everyone uses',
      'An enterprise manages multiple organizations under one owner',
      'Public repositories require an organization',
    ],
    answerIndexes: [0, 1, 3],
    explanation:
      'Personal accounts are identities; organizations are shared owners with teams; enterprises centralize policy and billing across organizations — and members are always personal accounts. Any account type, including personal ones, can own public repositories.',
    docId: 'types-of-github-accounts',
  },
  {
    id: 'gh900-d1-q17',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-github-flow',
    kind: 'multi',
    stem: 'Which are real steps of GitHub flow? Choose all that apply.',
    options: [
      'Create a branch for your change',
      'Commit your work with messages explaining why',
      'Open a pull request and discuss the change',
      'Push straight to the default branch to ship faster',
      'Rebase every other branch before merging',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'GitHub flow is branch → commit → pull request → review → merge into the default branch (then delete the branch). Skipping review with direct pushes, like forced rebasing of other branches, is not the flow at all.',
    docId: 'github-flow',
  },
  {
    id: 'gh900-d1-q18',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-github-flow',
    kind: 'order',
    stem: 'Order the GitHub flow steps from start to finish.',
    items: [
      'Create a topic branch for the change',
      'Commit your work to the branch',
      'Open a pull request',
      'Review and discuss with the team',
      'Merge into the default branch',
    ],
    explanation:
      'GitHub flow: branch for one idea, commit as you go, open the pull request early to start the conversation, review together, then merge — and delete the branch afterwards.',
    docId: 'github-flow',
  },
  {
    id: 'gh900-d1-q19',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-repos-commits-branches',
    kind: 'order',
    stem: 'Order the everyday loop for publishing a small change from your laptop.',
    items: [
      'Create and switch to a new branch',
      'Edit the file',
      'Stage the change with `git add`',
      'Commit with a message',
      'Push the branch to GitHub',
    ],
    explanation:
      'The loop is always: branch, edit, stage, commit, push. Staging picks what goes into the snapshot, the commit records it, and pushing shares the branch so a pull request can follow.',
    docId: 'hello-world',
  },
  {
    id: 'gh900-d1-q20',
    cert: 'gh900',
    domainId: 'gh900-d1',
    subSkillId: 'd1-repos-commits-branches',
    kind: 'bug',
    stem: 'A developer follows the loop below to propose a typo fix. One line defeats the purpose of the branch. Click the broken line.',
    codeLines: [
      'git switch -c fix-typo',
      'git add README.md',
      'git commit -m "Fix typo in setup steps"',
      'git push -u origin main',
    ],
    buggyLineIndex: 3,
    explanation:
      'The work lives on `fix-typo`, but the push targets `main` — publishing straight to the default branch instead of the branch just created. It should be `git push -u origin fix-typo`, so the change can go through a pull request.',
    docId: 'hello-world',
  },
];
