import type { Question } from '../types';

/**
 * GH-900 domain 4 practice bank — Apply modern development practices (20
 * questions). Actions shape, Copilot tiers and agents, Codespaces and dev
 * containers, github.dev. Mix: 13 single, 4 multi, and 3 coding items that
 * all exercise real workflow YAML (two fill-in, one spot-the-bug).
 */
export const questions: Question[] = [
  {
    id: 'gh900-d4-q01',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-actions-purpose',
    kind: 'single',
    stem: 'In one sentence, what is GitHub Actions?',
    options: [
      'An automation layer that runs workflows in response to repository events',
      'A code editor that runs in the browser',
      'A hosting service for static websites',
      'A package registry for dependencies',
    ],
    answerIndex: 0,
    explanation:
      'Actions is event-driven automation: a push, pull request, schedule, or release starts a workflow — a YAML file in `.github/workflows/` — that runs your jobs on GitHub-hosted machines.',
    docId: 'gh-docs-actions',
  },
  {
    id: 'gh900-d4-q02',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-actions-purpose',
    kind: 'single',
    stem: 'Which of these can trigger a GitHub Actions workflow?',
    options: [
      'A push, a pull request, a schedule, or the publication of a release',
      'Only pushes to the default branch',
      'Only manual runs started by an administrator',
      'Any edit made in the GitHub UI',
    ],
    answerIndex: 0,
    explanation:
      'Workflows hook into a long list of events — pushes, pull requests, schedules, releases, issues, and more — plus manual dispatch. Restricting triggers to pushes is a choice a workflow makes, not a limit of the platform.',
    docId: 'gh-docs-actions',
  },
  {
    id: 'gh900-d4-q03',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-actions-purpose',
    kind: 'single',
    stem: 'Where must workflow files live for GitHub Actions to find them?',
    options: [
      'In the `.github/workflows/` directory of the repository',
      'In the repository root, with a `.workflow` extension',
      'Inside the `.devcontainer/` directory',
      'Anywhere, as long as the file is named `ci.yml`',
    ],
    answerIndex: 0,
    explanation:
      'GitHub discovers workflows in `.github/workflows/` — that fixed location is what turns a YAML file into automation that shows up on the Actions tab.',
    docId: 'gh-docs-actions',
  },
  {
    id: 'gh900-d4-q04',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-actions-purpose',
    kind: 'single',
    stem: 'Which nesting correctly describes a workflow’s anatomy?',
    options: [
      'A workflow contains jobs, and each job contains steps',
      'A job contains workflows, and each workflow contains steps',
      'Steps contain jobs, and jobs contain events',
      'Events contain steps, and steps contain runners',
    ],
    answerIndex: 0,
    explanation:
      'The shape GH-900 wants: an event triggers a workflow; the workflow holds jobs (which run on their own runners); each job runs steps in order. Learning the containment order makes every YAML file readable.',
    docId: 'gh-docs-actions',
  },
  {
    id: 'gh900-d4-q05',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-copilot',
    kind: 'single',
    stem: 'A company wants organization-level policy over who can use Copilot and which models are allowed. Which plan tier provides those controls?',
    options: [
      'Copilot Business (and Enterprise above it)',
      'Copilot Free for individuals',
      'Any tier — policies exist everywhere',
      'None — Copilot policy is per repository',
    ],
    answerIndex: 0,
    explanation:
      'Organization-wide policy — who has access, which features and models — arrives with Copilot Business and continues in Enterprise. Individual plans have no organizational management surface.',
    docId: 'copilot-plans',
  },
  {
    id: 'gh900-d4-q06',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-copilot',
    kind: 'single',
    stem: 'In the IDE, a developer asks Copilot to "add pagination to the list view, install the dependency, and run the tests". Copilot edits several files and executes terminal commands across iterations. What is this capability called?',
    options: [
      'Agent Mode in the IDE',
      'The Copilot cloud agent',
      'Code completions',
      'GitHub Pages',
    ],
    answerIndex: 0,
    explanation:
      'Agent Mode works inside your IDE on your local checkout: it plans multi-file work, runs terminal commands, and iterates on results — versus completions, which only suggest text as you type.',
    docId: 'copilot-agent-mode',
  },
  {
    id: 'gh900-d4-q07',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-copilot',
    kind: 'single',
    stem: 'A maintainer assigns a well-scoped issue to Copilot. Later, a pull request appears from a separate workspace for the team to review. Which feature did this?',
    options: [
      'The Copilot cloud agent',
      'Agent Mode in the IDE',
      'A GitHub Actions schedule',
      'A codespace template',
    ],
    answerIndex: 0,
    explanation:
      'The cloud agent works on GitHub itself: hand it an issue and it develops on its own branch in its own workspace, then opens a pull request you review like any contributor’s.',
    docId: 'copilot-cloud-agent',
  },
  {
    id: 'gh900-d4-q08',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-copilot',
    kind: 'single',
    stem: 'Which sentence correctly separates Copilot’s two agent surfaces?',
    options: [
      'Agent Mode works in your IDE on your local checkout; the cloud agent works on GitHub and opens a pull request',
      'Agent Mode runs on GitHub servers; the cloud agent runs on your laptop',
      'Both run on your laptop with identical capabilities',
      'Both run on GitHub and always open pull requests',
    ],
    answerIndex: 0,
    explanation:
      'The exam loves this split: same idea, different venue. Agent Mode = IDE + your checkout; cloud agent = GitHub workspace + a pull request for review. Where the work happens is the differentiator.',
    docId: 'copilot-cloud-agent',
  },
  {
    id: 'gh900-d4-q09',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-codespaces-devcontainers',
    kind: 'single',
    stem: 'A new hire waits three days to get a laptop configured with the team’s toolchain. Which GitHub feature exists precisely to remove that wait?',
    options: [
      'Codespaces — a full cloud development environment ready in seconds',
      'GitHub Pages — a website documenting the setup steps',
      'GitHub Mobile — for configuring laptops remotely',
      'GitHub Sponsors — funding to buy a faster laptop',
    ],
    answerIndex: 0,
    explanation:
      'A codespace is a container-based environment — editor, terminal, tools — that spins up from the repository, so "getting set up" stops being a rite of passage.',
    docId: 'what-are-codespaces',
  },
  {
    id: 'gh900-d4-q10',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-codespaces-devcontainers',
    kind: 'single',
    stem: 'What makes a codespace reproducible — the same tools and extensions for everyone who opens one?',
    options: [
      'A dev container definition committed to the repository (`.devcontainer/`)',
      'Each developer configuring their own machine identically',
      'A wiki page listing the required tools',
      'Nothing — codespaces pick random tool versions',
    ],
    answerIndex: 0,
    explanation:
      'The dev container pins the image, tools, extensions, and settings as code in the repository. Everyone’s codespace builds from that definition, ending "works on my machine" stories.',
    docId: 'dev-containers',
  },
  {
    id: 'gh900-d4-q11',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-githubdev',
    kind: 'single',
    stem: 'While browsing a repository on github.com, a developer presses the `.` (period) key. What happens?',
    options: [
      'The repository opens in github.dev, a browser-based VS Code editor',
      'The repository’s README reloads',
      'A new codespace starts and billing begins',
      'Nothing — that shortcut is desktop-only',
    ],
    answerIndex: 0,
    explanation:
      'The period key is the shortcut into github.dev (equivalently, swap `github.com` for `github.dev` in the URL): the repo opens in a web-based editor tied to your GitHub identity.',
    docId: 'githubdev-editor',
  },
  {
    id: 'gh900-d4-q12',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-githubdev',
    kind: 'single',
    stem: 'A technical writer needs to fix a typo in the docs and open a pull request from the browser — without spinning up a whole environment. Which surface fits exactly?',
    options: [
      'github.dev — quick edits and PRs, nothing executing',
      'A codespace — because editing requires a container',
      'GitHub Desktop — because every edit needs a local clone',
      'The Copilot cloud agent — because it edits files for you',
    ],
    answerIndex: 0,
    explanation:
      'github.dev is the light-edit middle ground: full editor in the browser, no terminal or process execution. When you need to build, run, or debug, that is the codespace’s job.',
    docId: 'githubdev-editor',
  },
  {
    id: 'gh900-d4-q13',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-codespaces-devcontainers',
    kind: 'single',
    stem: 'Where can a developer review, reopen, or delete the codespaces they have created across repositories?',
    options: [
      'Their personal codespaces page at github.com/codespaces',
      'Each repository’s Insights tab',
      'The organization’s billing page only',
      'GitHub Mobile exclusively',
    ],
    answerIndex: 0,
    explanation:
      'Your codespaces are gathered under your account at github.com/codespaces — one place to manage, stop, and delete environments (and where personal timeout settings live), regardless of which repository spawned them.',
    docId: 'codespaces-list',
  },
  {
    id: 'gh900-d4-q14',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-actions-purpose',
    kind: 'multi',
    stem: 'Which tasks can GitHub Actions workflows take over? Choose all that apply.',
    options: [
      'Running tests on every pull request',
      'Building and deploying a site on merge',
      'Running a scheduled nightly cleanup job',
      'Hosting your production database',
      'Editing files on your personal laptop while it is closed',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Workflows automate repository work: test, build, deploy, schedule. They run on GitHub’s machines — not your laptop — and they do not host stateful services like databases.',
    docId: 'gh-docs-actions',
  },
  {
    id: 'gh900-d4-q15',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-codespaces-devcontainers',
    kind: 'multi',
    stem: 'Which statements about Codespaces are true? Choose all that apply.',
    options: [
      'A codespace is a cloud-hosted development environment',
      'Codespaces can be opened in the browser or from supported local editors',
      'A dev container definition makes environments reproducible',
      'Codespaces replace the need for Git',
      'Codespaces can run forever at no cost',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Codespaces give everyone a container environment built from a committed definition — from a browser or your editor. They sit on top of Git, not instead of it, and usage is metered, not unlimited.',
    docId: 'what-are-codespaces',
  },
  {
    id: 'gh900-d4-q16',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-copilot',
    kind: 'multi',
    stem: 'Which are real Copilot capabilities on GitHub today? Choose all that apply.',
    options: [
      'Inline code completions in supported editors',
      'Chat about your code in the editor',
      'An agent that takes an issue and opens a pull request',
      'Silently merging pull requests without human review',
      'Writing commit messages as its only function',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'Copilot spans completions, chat, and agents that propose changes for review. Merging without humans is not a Copilot feature — review stays a person’s call.',
    docId: 'copilot-get-started',
  },
  {
    id: 'gh900-d4-q17',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-githubdev',
    kind: 'multi',
    stem: 'Which statements correctly compare github.dev and a codespace? Choose all that apply.',
    options: [
      'github.dev opens with the `.` key on any repository',
      'github.dev cannot run your code or a terminal',
      'A codespace can build, run, and debug the project',
      'github.dev requires a paid Codespaces plan',
      'A codespace cannot be opened in a browser',
    ],
    answerIndexes: [0, 1, 2],
    explanation:
      'github.dev is free light editing in the browser — no execution, no codespace billing. A codespace is the executing environment, and it opens from the browser or your editor alike.',
    docId: 'githubdev-editor',
  },
  {
    id: 'gh900-d4-q18',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-actions-purpose',
    kind: 'fill',
    stem: 'Complete the workflow so it triggers on pushes to the `main` branch.',
    codeTemplate:
      'name: CI\n___:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm test\n',
    blanks: [{ answer: 'on', alternatives: [] }],
    explanation:
      'The `on` key declares the workflow’s triggers. Without it the file is not attached to any event, so nothing — not even a push to `main` — starts it.',
    docId: 'gh-docs-actions',
  },
  {
    id: 'gh900-d4-q19',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-actions-purpose',
    kind: 'fill',
    stem: 'Fill in both blanks: the workflow’s job list and the runner selection.',
    codeTemplate:
      'name: Deploy\non:\n  push:\n    branches: [main]\n___:\n  deploy:\n    ___: ubuntu-latest\n    steps:\n      - run: ./deploy.sh\n',
    blanks: [
      { answer: 'jobs', alternatives: [] },
      { answer: 'runs-on', alternatives: ['runs_on'] },
    ],
    explanation:
      'Jobs live under the `jobs` key, and each job names its runner with `runs-on` — here GitHub’s `ubuntu-latest` image. Those two keys carry almost every workflow you will read.',
    docId: 'gh-docs-actions',
  },
  {
    id: 'gh900-d4-q20',
    cert: 'gh900',
    domainId: 'gh900-d4',
    subSkillId: 'd4-actions-purpose',
    kind: 'bug',
    stem: 'This workflow is meant to run `npm test` inside the `test` job. One line sits at the wrong indentation, so the job never sees its step. Click the misindented line.',
    codeLines: [
      'name: CI',
      'on: push',
      'jobs:',
      '  test:',
      '    runs-on: ubuntu-latest',
      '  steps:',
      '    - run: npm test',
    ],
    buggyLineIndex: 5,
    explanation:
      '`steps:` is indented as a sibling of the `test:` job instead of inside it, so the job owns no steps and the workflow is invalid. In YAML, indentation is structure: steps must nest under their job.',
    docId: 'gh-docs-actions',
  },
];
