import { q } from "../_build";

const T = ["lab-coding", "lab-06"];

export const LAB06 = [
  q({ id: "q-lab06-1", domainId: "d2", moduleId: "m06", lessonId: "l0602", difficulty: "challenge", type: "codeReading",
    tags: T,
    prompt: "Harbor finance reports **intermittently disagree** with the warehouse on voyage subtotals because readers overlap in-flight UPDATEs. Writers must **not** wait on reporting SELECTs. Dirty reads (uncommitted prices) are forbidden.\n\nWhat should you enable?",
    options: [
      ["a", "Read Committed Snapshot Isolation (RCSI) so readers use row versions and do not take shared locks"],
      ["b", "`SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED` or `NOLOCK` on every report"],
      ["c", "Table-level exclusive locks on dbo.Voyage during reports"],
      ["d", "Query Store only — it prevents writers from modifying rows that reports need"],
    ],
    correct: ["a"],
    explanation: "RCSI (database option `READ_COMMITTED_SNAPSHOT ON`) gives committed, versioned reads without blocking writers. NOLOCK/READ UNCOMMITTED allow dirty reads, which the stem forbids. Escalating to table X locks increases blocking. Query Store records plans; it is not a concurrency control." }),
  q({ id: "q-lab06-2", domainId: "d2", moduleId: "m06", lessonId: "l0602", difficulty: "advanced", type: "multi",
    tags: T,
    prompt: "Query Store is on. Query 42's **latest** plan is 20× slower than an older `plan_id` after a statistics change (parameter sniffing). You cannot change the application SQL this week.\n\nWhich **two** in-database actions can stabilize it? Each correct answer presents part of the solution.",
    options: [
      ["a", "`sys.sp_query_store_force_plan` to pin the known-good plan_id"],
      ["b", "`sys.sp_query_store_set_hints` to attach an OPTION hint (for example `RECOMPILE` or `OPTIMIZE FOR`) to query_id 42"],
      ["c", "`DBCC FREEPROCCACHE` on a schedule as the only long-term fix"],
      ["d", "`ALTER DATABASE … SET QUERY_STORE = OFF` so the bad plan cannot be stored"],
    ],
    correct: ["a", "b"],
    explanation: "Forcing a plan and Query Store hints both fix the query without a code deploy. Periodic FREEPROCCACHE is a blunt cache flush, not a plan regression strategy. Turning Query Store off removes the evidence and the force/hint mechanism." }),
  q({ id: "q-lab06-3", domainId: "d2", moduleId: "m06", lessonId: "l0602", difficulty: "advanced", type: "codeReading",
    tags: T,
    prompt: "The missing-index DMV reports `equality_columns = '[VoyageDate]'` and `included_columns = '[SubTotal]'` for a report that filters `VoyageDate = @d` and returns `SubTotal`. You decide to accept the shape (knowing DMVs are hints, not orders).\n\nWhich index matches the advice?",
    options: [
      ["a", "`CREATE INDEX IX ON dbo.Voyage(VoyageDate) INCLUDE (SubTotal)`"],
      ["b", "`CREATE INDEX IX ON dbo.Voyage(SubTotal) INCLUDE (VoyageDate)`"],
      ["c", "`CREATE CLUSTERED COLUMNSTORE INDEX IX ON dbo.Voyage` — missing-index DMVs always mean columnstore"],
      ["d", "`CREATE UNIQUE INDEX IX ON dbo.Voyage(VoyageId)` — uniqueness satisfies every equality filter"],
    ],
    correct: ["a"],
    explanation: "Equality/inequality columns become **key** columns; included_columns are non-key INCLUDE (covering). Reversing them cannot seek on VoyageDate. Columnstore is a different design (analytics scans). A unique index on VoyageId does not help a date filter." }),
  q({ id: "q-lab06-4", domainId: "d2", moduleId: "m06", lessonId: "l0603", difficulty: "challenge", type: "debugging",
    tags: T,
    prompt: "Isolation is READ COMMITTED (RCSI off). Session 88 runs `BEGIN TRAN; UPDATE dbo.Gear SET ListPrice += 1 WHERE GearId = 10;` and leaves the transaction open. Session 89's `SELECT ListPrice FROM dbo.Gear WHERE GearId = 10` hangs.\n\nWhich diagnosis is correct?",
    options: [
      ["a", "Session 89 is **blocked** waiting on 88's exclusive lock; it is not a deadlock until a wait cycle exists. 89 proceeds when 88 commits or rolls back"],
      ["b", "SQL Server has deadlocked; both sessions will wait forever unless you restart the instance"],
      ["c", "SELECT never takes or respects locks under READ COMMITTED, so the hang must be a network issue"],
      ["d", "Blocking cannot occur unless Query Store is enabled"],
    ],
    correct: ["a"],
    explanation: "Writers take X locks; readers under locking READ COMMITTED request S locks and wait. A deadlock needs a cycle (88 waits on 89 and 89 waits on 88). The engine does kill a deadlock victim — it does not hang forever. Query Store is unrelated to lock acquisition." }),
  q({ id: "q-lab06-5", domainId: "d2", moduleId: "m06", lessonId: "l0603", difficulty: "advanced", type: "codeReading",
    tags: T,
    prompt: "An on-call engineer needs **who is blocked right now**, by whom, and the blocked statement text.\n\nWhich starting point is appropriate?",
    options: [
      ["a", "`sys.dm_os_waiting_tasks` joined to `sys.dm_exec_requests` / sessions / `sys.dm_exec_sql_text` (and `blocking_session_id`)"],
      ["b", "`sys.dm_db_index_usage_stats` only"],
      ["c", "`sys.dm_db_xtp_checkpoint_files` only"],
      ["d", "Disable Query Store and rerun the workload; wait stats are stored only there"],
    ],
    correct: ["a"],
    explanation: "Live blocking is waiting_tasks + requests/sessions + sql_text (and often `sys.dm_exec_query_plan`). Index usage and In-Memory checkpoint files do not show lock waiters. Query Store is historical plans/runtime, not the live blocking graph." }),
  q({ id: "q-lab06-6", domainId: "d2", moduleId: "m06", lessonId: "l0601", difficulty: "advanced", type: "codeReading",
    tags: T,
    prompt: "You turn on Query Store for Harbor's Azure SQL database so you can compare plans after a compatibility-level change.\n\nWhich statement starts capture, and what does it **not** do by itself?",
    code: `ALTER DATABASE CURRENT SET QUERY_STORE = ON;`,
    options: [
      ["a", "It captures query text, plans, and runtime stats. It does **not** automatically force good plans or enable RCSI"],
      ["b", "It enables RCSI and Always Encrypted"],
      ["c", "It rebuilds every index and clears missing-index DMVs"],
      ["d", "It is a deprecated synonym for `SET AUTOMATIC_TUNING = OFF`"],
    ],
    correct: ["a"],
    explanation: "`SET QUERY_STORE = ON` is the capture switch. Automatic plan correction / forcing is a separate Automatic Tuning (or manual force) step. Isolation and encryption are unrelated database options." }),
];
